/*
 * Decompiled with CFR 0.152.
 */
package com.google.android.gms.internal.measurement;

import com.google.android.gms.internal.measurement.zzka;
import com.google.android.gms.internal.measurement.zzkd;
import com.google.android.gms.internal.measurement.zzkr;

public final class zzkb
extends Enum {
    public static final /* enum */ zzkb zza;
    private static final /* enum */ zzkb zzaa;
    private static final /* enum */ zzkb zzab;
    private static final /* enum */ zzkb zzac;
    private static final /* enum */ zzkb zzad;
    private static final /* enum */ zzkb zzae;
    private static final /* enum */ zzkb zzaf;
    private static final /* enum */ zzkb zzag;
    private static final /* enum */ zzkb zzah;
    private static final /* enum */ zzkb zzai;
    private static final /* enum */ zzkb zzaj;
    private static final /* enum */ zzkb zzak;
    private static final /* enum */ zzkb zzal;
    private static final /* enum */ zzkb zzam;
    private static final /* enum */ zzkb zzan;
    private static final /* enum */ zzkb zzao;
    private static final /* enum */ zzkb zzap;
    private static final /* enum */ zzkb zzaq;
    private static final /* enum */ zzkb zzar;
    private static final /* enum */ zzkb zzas;
    private static final /* enum */ zzkb zzat;
    private static final /* enum */ zzkb zzau;
    private static final /* enum */ zzkb zzav;
    private static final /* enum */ zzkb zzaw;
    private static final /* enum */ zzkb zzax;
    private static final /* enum */ zzkb zzay;
    private static final zzkb[] zzaz;
    public static final /* enum */ zzkb zzb;
    private static final /* synthetic */ zzkb[] zzba;
    private static final /* enum */ zzkb zzc;
    private static final /* enum */ zzkb zzd;
    private static final /* enum */ zzkb zze;
    private static final /* enum */ zzkb zzf;
    private static final /* enum */ zzkb zzg;
    private static final /* enum */ zzkb zzh;
    private static final /* enum */ zzkb zzi;
    private static final /* enum */ zzkb zzj;
    private static final /* enum */ zzkb zzk;
    private static final /* enum */ zzkb zzl;
    private static final /* enum */ zzkb zzm;
    private static final /* enum */ zzkb zzn;
    private static final /* enum */ zzkb zzo;
    private static final /* enum */ zzkb zzp;
    private static final /* enum */ zzkb zzq;
    private static final /* enum */ zzkb zzr;
    private static final /* enum */ zzkb zzs;
    private static final /* enum */ zzkb zzt;
    private static final /* enum */ zzkb zzu;
    private static final /* enum */ zzkb zzv;
    private static final /* enum */ zzkb zzw;
    private static final /* enum */ zzkb zzx;
    private static final /* enum */ zzkb zzy;
    private static final /* enum */ zzkb zzz;
    private final int zzbb;

    static {
        zzkb zzkb2;
        zzkb zzkb3;
        zzkb zzkb4;
        zzkb zzkb5;
        zzkb zzkb6;
        zzkb zzkb7;
        zzkb zzkb8;
        zzkb zzkb9;
        zzkb zzkb10;
        zzkb zzkb11;
        zzkb zzkb12;
        zzkb zzkb13;
        zzkb zzkb14;
        zzkb zzkb15;
        zzkb zzkb16;
        zzkb zzkb17;
        zzkb zzkb18;
        zzkb zzkb19;
        zzkb zzkb20;
        zzkb zzkb21;
        zzkb zzkb22;
        zzkb zzkb23;
        zzkb zzkb24;
        zzkb zzkb25;
        zzkb zzkb26;
        zzkb zzkb27;
        zzkb zzkb28;
        zzkb zzkb29;
        zzkb zzkb30;
        zzkb zzkb31;
        zzkb zzkb32;
        zzkb zzkb33;
        zzkb zzkb34;
        zzkb zzkb35;
        zzkb zzkb36;
        zzkb zzkb37;
        zzkb zzkb38;
        zzkb zzkb39;
        zzkb zzkb40;
        zzkb zzkb41;
        zzkb zzkb42;
        Enum enum_ = zzkd.zza;
        Enum enum_2 = zzkr.zze;
        zzkb[] zzkbArray = zzkb42;
        Enum enum_3 = enum_;
        zzkb[] zzkbArray2 = enum_2;
        zzc = zzkb42 = new zzkb("DOUBLE", 0, 0, (zzkd)enum_, (zzkr)enum_2);
        Enum enum_4 = zzkr.zzd;
        zzkbArray = zzkb41;
        zzkbArray2 = enum_4;
        zzd = zzkb41 = new zzkb("FLOAT", 1, 1, (zzkd)enum_, (zzkr)enum_4);
        Enum enum_5 = zzkr.zzc;
        zzkbArray = zzkb40;
        zzkbArray2 = enum_5;
        zze = zzkb40 = new zzkb("INT64", 2, 2, (zzkd)enum_, (zzkr)enum_5);
        zzkbArray = zzkb39;
        zzf = zzkb39 = new zzkb("UINT64", 3, 3, (zzkd)enum_, (zzkr)enum_5);
        Enum enum_6 = zzkr.zzb;
        zzkbArray = zzkb38;
        zzkbArray2 = enum_6;
        zzg = zzkb38 = new zzkb("INT32", 4, 4, (zzkd)enum_, (zzkr)enum_6);
        zzkbArray = zzkb37;
        zzkbArray2 = enum_5;
        zzh = zzkb37 = new zzkb("FIXED64", 5, 5, (zzkd)enum_, (zzkr)enum_5);
        zzkbArray = zzkb36;
        zzkbArray2 = enum_6;
        zzi = zzkb36 = new zzkb("FIXED32", 6, 6, (zzkd)enum_, (zzkr)enum_6);
        Enum enum_7 = zzkr.zzf;
        zzkbArray = zzkb35;
        zzkbArray2 = enum_7;
        zzj = zzkb35 = new zzkb("BOOL", 7, 7, (zzkd)enum_, (zzkr)enum_7);
        Enum enum_8 = zzkr.zzg;
        zzkbArray = zzkb34;
        zzkbArray2 = enum_8;
        zzk = zzkb34 = new zzkb("STRING", 8, 8, (zzkd)enum_, (zzkr)enum_8);
        zzkr zzkr2 = zzkr.zzj;
        zzkbArray = zzkb33;
        zzkbArray2 = zzkr2;
        zzl = zzkb33 = new zzkb("MESSAGE", 9, 9, (zzkd)enum_, zzkr2);
        Enum enum_9 = zzkr.zzh;
        zzkbArray = zzkb32;
        zzkbArray2 = enum_9;
        zzm = zzkb32 = new zzkb("BYTES", 10, 10, (zzkd)enum_, (zzkr)enum_9);
        zzkbArray = zzkb31;
        zzkbArray2 = enum_6;
        zzn = zzkb31 = new zzkb("UINT32", 11, 11, (zzkd)enum_, (zzkr)enum_6);
        Enum enum_10 = zzkr.zzi;
        zzkbArray = zzkb30;
        zzkbArray2 = enum_10;
        zzo = zzkb30 = new zzkb("ENUM", 12, 12, (zzkd)enum_, (zzkr)enum_10);
        zzkbArray = zzkb29;
        zzkbArray2 = enum_6;
        zzp = zzkb29 = new zzkb("SFIXED32", 13, 13, (zzkd)enum_, (zzkr)enum_6);
        zzkbArray = zzkb28;
        zzkbArray2 = enum_5;
        zzq = zzkb28 = new zzkb("SFIXED64", 14, 14, (zzkd)enum_, (zzkr)enum_5);
        zzkbArray = zzkb27;
        zzkbArray2 = enum_6;
        zzr = zzkb27 = new zzkb("SINT32", 15, 15, (zzkd)enum_, (zzkr)enum_6);
        zzkbArray = zzkb26;
        zzkbArray2 = enum_5;
        zzs = zzkb26 = new zzkb("SINT64", 16, 16, (zzkd)enum_, (zzkr)enum_5);
        zzkbArray = zzkb25;
        zzkbArray2 = zzkr2;
        zzt = zzkb25 = new zzkb("GROUP", 17, 17, (zzkd)enum_, zzkr2);
        zzkd zzkd2 = zzkd.zzb;
        zzkbArray = enum_;
        enum_3 = zzkd2;
        zzkbArray2 = enum_2;
        zzu = enum_ = new zzkb("DOUBLE_LIST", 18, 18, zzkd2, (zzkr)enum_2);
        zzkbArray = zzkb24;
        zzkbArray2 = enum_4;
        zzv = zzkb24 = new zzkb("FLOAT_LIST", 19, 19, zzkd2, (zzkr)enum_4);
        zzkbArray = zzkb23;
        zzkbArray2 = enum_5;
        zzw = zzkb23 = new zzkb("INT64_LIST", 20, 20, zzkd2, (zzkr)enum_5);
        zzkbArray = zzkb22;
        zzx = zzkb22 = new zzkb("UINT64_LIST", 21, 21, zzkd2, (zzkr)enum_5);
        zzkbArray = zzkb21;
        zzkbArray2 = enum_6;
        zzy = zzkb21 = new zzkb("INT32_LIST", 22, 22, zzkd2, (zzkr)enum_6);
        zzkbArray = zzkb20;
        zzkbArray2 = enum_5;
        zzz = zzkb20 = new zzkb("FIXED64_LIST", 23, 23, zzkd2, (zzkr)enum_5);
        zzkbArray = zzkb19;
        zzkbArray2 = enum_6;
        zzaa = zzkb19 = new zzkb("FIXED32_LIST", 24, 24, zzkd2, (zzkr)enum_6);
        zzkbArray = zzkb18;
        zzkbArray2 = enum_7;
        zzab = zzkb18 = new zzkb("BOOL_LIST", 25, 25, zzkd2, (zzkr)enum_7);
        zzkbArray = zzkb17;
        zzkbArray2 = enum_8;
        zzac = zzkb17 = new zzkb("STRING_LIST", 26, 26, zzkd2, (zzkr)enum_8);
        zzkbArray = enum_8;
        zzkbArray2 = zzkr2;
        zzad = enum_8 = new zzkb("MESSAGE_LIST", 27, 27, zzkd2, zzkr2);
        zzkbArray = zzkb16;
        zzkbArray2 = enum_9;
        zzae = zzkb16 = new zzkb("BYTES_LIST", 28, 28, zzkd2, (zzkr)enum_9);
        zzkbArray = enum_9;
        zzkbArray2 = enum_6;
        zzaf = enum_9 = new zzkb("UINT32_LIST", 29, 29, zzkd2, (zzkr)enum_6);
        zzkbArray = zzkb15;
        zzkbArray2 = enum_10;
        zzag = zzkb15 = new zzkb("ENUM_LIST", 30, 30, zzkd2, (zzkr)enum_10);
        zzkbArray = zzkb14;
        zzkbArray2 = enum_6;
        zzah = zzkb14 = new zzkb("SFIXED32_LIST", 31, 31, zzkd2, (zzkr)enum_6);
        zzkbArray = zzkb13;
        zzkbArray2 = enum_5;
        zzai = zzkb13 = new zzkb("SFIXED64_LIST", 32, 32, zzkd2, (zzkr)enum_5);
        zzkbArray = zzkb12;
        zzkbArray2 = enum_6;
        zzaj = zzkb12 = new zzkb("SINT32_LIST", 33, 33, zzkd2, (zzkr)enum_6);
        zzkbArray = zzkb11;
        zzkbArray2 = enum_5;
        zzak = zzkb11 = new zzkb("SINT64_LIST", 34, 34, zzkd2, (zzkr)enum_5);
        zzkd zzkd3 = zzkd.zzc;
        zzkbArray = zzkb10;
        enum_3 = zzkd3;
        zzkbArray2 = enum_2;
        zza = zzkb10 = new zzkb("DOUBLE_LIST_PACKED", 35, 35, zzkd3, (zzkr)enum_2);
        zzkbArray = enum_2;
        zzkbArray2 = enum_4;
        zzal = enum_2 = new zzkb("FLOAT_LIST_PACKED", 36, 36, zzkd3, (zzkr)enum_4);
        zzkbArray = enum_4;
        zzkbArray2 = enum_5;
        zzam = enum_4 = new zzkb("INT64_LIST_PACKED", 37, 37, zzkd3, (zzkr)enum_5);
        zzkbArray = zzkb9;
        zzan = zzkb9 = new zzkb("UINT64_LIST_PACKED", 38, 38, zzkd3, (zzkr)enum_5);
        zzkbArray = zzkb8;
        zzkbArray2 = enum_6;
        zzao = zzkb8 = new zzkb("INT32_LIST_PACKED", 39, 39, zzkd3, (zzkr)enum_6);
        zzkbArray = zzkb7;
        zzkbArray2 = enum_5;
        zzap = zzkb7 = new zzkb("FIXED64_LIST_PACKED", 40, 40, zzkd3, (zzkr)enum_5);
        zzkbArray = zzkb6;
        zzkbArray2 = enum_6;
        zzaq = zzkb6 = new zzkb("FIXED32_LIST_PACKED", 41, 41, zzkd3, (zzkr)enum_6);
        zzkbArray = zzkb5;
        zzkbArray2 = enum_7;
        zzar = zzkb5 = new zzkb("BOOL_LIST_PACKED", 42, 42, zzkd3, (zzkr)enum_7);
        zzkbArray = enum_7;
        zzkbArray2 = enum_6;
        zzas = enum_7 = new zzkb("UINT32_LIST_PACKED", 43, 43, zzkd3, (zzkr)enum_6);
        zzkbArray = zzkb4;
        zzkbArray2 = enum_10;
        zzat = zzkb4 = new zzkb("ENUM_LIST_PACKED", 44, 44, zzkd3, (zzkr)enum_10);
        zzkbArray = enum_10;
        zzkbArray2 = enum_6;
        zzau = enum_10 = new zzkb("SFIXED32_LIST_PACKED", 45, 45, zzkd3, (zzkr)enum_6);
        zzkbArray = zzkb3;
        zzkbArray2 = enum_5;
        zzav = zzkb3 = new zzkb("SFIXED64_LIST_PACKED", 46, 46, zzkd3, (zzkr)enum_5);
        zzkbArray = zzkb2;
        zzkbArray2 = enum_6;
        zzaw = zzkb2 = new zzkb("SINT32_LIST_PACKED", 47, 47, zzkd3, (zzkr)enum_6);
        zzkbArray = enum_6;
        zzkbArray2 = enum_5;
        zzb = enum_6 = new zzkb("SINT64_LIST_PACKED", 48, 48, zzkd3, (zzkr)enum_5);
        zzkbArray = enum_5;
        enum_3 = zzkd2;
        zzkbArray2 = zzkr2;
        zzax = enum_5 = new zzkb("GROUP_LIST", 49, 49, zzkd2, zzkr2);
        zzkd zzkd4 = zzkd.zzd;
        zzkr zzkr3 = zzkr.zza;
        String string2 = "MAP";
        int n3 = 50;
        int n4 = 50;
        zzkbArray = new zzkb(string2, n3, n4, zzkd4, zzkr3);
        zzay = zzkbArray;
        zzkb[] zzkbArray3 = new zzkb[51];
        zzkbArray3[0] = zzkb42;
        int n7 = 1;
        zzkbArray3[n7] = zzkb41;
        zzkbArray3[2] = zzkb40;
        zzkbArray3[3] = zzkb39;
        zzkbArray3[4] = zzkb38;
        zzkbArray3[5] = zzkb37;
        zzkbArray3[6] = zzkb36;
        zzkbArray3[7] = zzkb35;
        zzkbArray3[8] = zzkb34;
        zzkbArray3[9] = zzkb33;
        zzkbArray3[10] = zzkb32;
        zzkbArray3[11] = zzkb31;
        zzkbArray3[12] = zzkb30;
        zzkbArray3[13] = zzkb29;
        zzkbArray3[14] = zzkb28;
        zzkbArray3[15] = zzkb27;
        zzkbArray3[16] = zzkb26;
        zzkbArray3[17] = zzkb25;
        zzkbArray3[18] = enum_;
        zzkbArray3[19] = zzkb24;
        zzkbArray3[20] = zzkb23;
        zzkbArray3[21] = zzkb22;
        zzkbArray3[22] = zzkb21;
        zzkbArray3[23] = zzkb20;
        zzkbArray3[24] = zzkb19;
        zzkbArray3[25] = zzkb18;
        zzkbArray3[26] = zzkb17;
        zzkbArray3[27] = enum_8;
        zzkbArray3[28] = zzkb16;
        zzkbArray3[29] = enum_9;
        zzkbArray3[30] = zzkb15;
        zzkbArray3[31] = zzkb14;
        zzkbArray3[32] = zzkb13;
        zzkbArray3[33] = zzkb12;
        zzkbArray3[34] = zzkb11;
        zzkbArray3[35] = zzkb10;
        zzkbArray3[36] = enum_2;
        zzkbArray3[37] = enum_4;
        zzkbArray3[38] = zzkb9;
        zzkbArray3[39] = zzkb8;
        zzkbArray3[40] = zzkb7;
        zzkbArray3[41] = zzkb6;
        zzkbArray3[42] = zzkb5;
        zzkbArray3[43] = enum_7;
        zzkbArray3[44] = zzkb4;
        zzkbArray3[45] = enum_10;
        zzkbArray3[46] = zzkb3;
        zzkbArray3[47] = zzkb2;
        zzkbArray3[48] = enum_6;
        zzkbArray3[49] = enum_5;
        int n8 = 50;
        zzkbArray3[n8] = zzkbArray;
        zzba = zzkbArray3;
        zzkbArray = zzkb.values();
        zzkbArray3 = new zzkb[zzkbArray.length];
        zzaz = zzkbArray3;
        int n10 = zzkbArray.length;
        for (int i3 = 0; i3 < n10; i3 += n7) {
            enum_3 = zzkbArray[i3];
            zzkbArray2 = zzaz;
            int n14 = ((zzkb)enum_3).zzbb;
            zzkbArray2[n14] = enum_3;
        }
    }

    /*
     * WARNING - Possible parameter corruption
     * WARNING - void declaration
     */
    private zzkb(zzkr zzkr2) {
        void var5_3;
        void var4_2;
        void var2_-1;
        void var1_-1;
        this.zzbb = (int)zzkr2;
        Object object = var4_2.ordinal();
        int n4 = 1;
        if (object != n4) {
            n4 = 3;
            if (object == n4) {
                var5_3.zza();
            }
        } else {
            var5_3.zza();
        }
        Object object2 = zzkd.zza;
        if (var4_2 == object2) {
            object2 = zzka.zza;
            n4 = var5_3.ordinal();
            object = (Object)object2[n4];
        }
    }

    public static zzkb[] values() {
        return (zzkb[])zzba.clone();
    }

    public final int zza() {
        return this.zzbb;
    }
}

