/*
 * Decompiled with CFR 0.152.
 */
package com.google.android.gms.internal.gtm;

import com.google.android.gms.internal.gtm.zzacr;

public final class zzabw
extends Enum {
    public static final /* enum */ zzabw zzA;
    public static final /* enum */ zzabw zzB;
    public static final /* enum */ zzabw zzC;
    public static final /* enum */ zzabw zzD;
    public static final /* enum */ zzabw zzE;
    public static final /* enum */ zzabw zzF;
    public static final /* enum */ zzabw zzG;
    public static final /* enum */ zzabw zzH;
    public static final /* enum */ zzabw zzI;
    public static final /* enum */ zzabw zzJ;
    public static final /* enum */ zzabw zzK;
    public static final /* enum */ zzabw zzL;
    public static final /* enum */ zzabw zzM;
    public static final /* enum */ zzabw zzN;
    public static final /* enum */ zzabw zzO;
    public static final /* enum */ zzabw zzP;
    public static final /* enum */ zzabw zzQ;
    public static final /* enum */ zzabw zzR;
    public static final /* enum */ zzabw zzS;
    public static final /* enum */ zzabw zzT;
    public static final /* enum */ zzabw zzU;
    public static final /* enum */ zzabw zzV;
    public static final /* enum */ zzabw zzW;
    public static final /* enum */ zzabw zzX;
    public static final /* enum */ zzabw zzY;
    private static final zzabw[] zzZ;
    public static final /* enum */ zzabw zza;
    private static final /* synthetic */ zzabw[] zzaa;
    public static final /* enum */ zzabw zzb;
    public static final /* enum */ zzabw zzc;
    public static final /* enum */ zzabw zzd;
    public static final /* enum */ zzabw zze;
    public static final /* enum */ zzabw zzf;
    public static final /* enum */ zzabw zzg;
    public static final /* enum */ zzabw zzh;
    public static final /* enum */ zzabw zzi;
    public static final /* enum */ zzabw zzj;
    public static final /* enum */ zzabw zzk;
    public static final /* enum */ zzabw zzl;
    public static final /* enum */ zzabw zzm;
    public static final /* enum */ zzabw zzn;
    public static final /* enum */ zzabw zzo;
    public static final /* enum */ zzabw zzp;
    public static final /* enum */ zzabw zzq;
    public static final /* enum */ zzabw zzr;
    public static final /* enum */ zzabw zzs;
    public static final /* enum */ zzabw zzt;
    public static final /* enum */ zzabw zzu;
    public static final /* enum */ zzabw zzv;
    public static final /* enum */ zzabw zzw;
    public static final /* enum */ zzabw zzx;
    public static final /* enum */ zzabw zzy;
    public static final /* enum */ zzabw zzz;
    private final int zzab;

    static {
        zzabw zzabw2;
        zzabw zzabw3;
        zzabw zzabw4;
        zzabw zzabw5;
        zzabw zzabw6;
        zzabw zzabw7;
        zzabw zzabw8;
        zzabw zzabw9;
        zzabw zzabw10;
        zzabw zzabw11;
        zzabw zzabw12;
        zzabw zzabw13;
        zzabw zzabw14;
        zzabw zzabw15;
        zzabw zzabw16;
        zzabw zzabw17;
        zzabw zzabw18;
        zzabw zzabw19;
        zzabw zzabw20;
        zzabw zzabw21;
        zzabw zzabw22;
        zzabw zzabw23;
        zzabw zzabw24;
        zzabw zzabw25;
        zzabw zzabw26;
        zzabw zzabw27;
        zzabw zzabw28;
        zzabw zzabw29;
        zzabw zzabw30;
        zzabw zzabw31;
        zzabw zzabw32;
        zzabw zzabw33;
        zzabw[] zzabwArray;
        Enum enum_ = zzacr.zze;
        int n3 = 1;
        zzabw[] zzabwArray2 = zzabwArray;
        zzabwArray = new zzabw("DOUBLE", 0, 0, n3, (zzacr)enum_);
        zza = zzabwArray;
        Enum enum_2 = zzacr.zzd;
        int n4 = 1;
        int n7 = 1;
        int n8 = 1;
        zzabw zzabw34 = zzabw33;
        Enum enum_3 = enum_2;
        zzb = zzabw33 = new zzabw("FLOAT", n8, n4, n7, (zzacr)enum_2);
        Enum enum_4 = zzacr.zzc;
        zzabwArray2 = zzabw34;
        zzc = zzabw34 = new zzabw("INT64", 2, 2, n3, (zzacr)enum_4);
        zzabwArray2 = zzabw32;
        zzd = zzabw32 = new zzabw("UINT64", 3, 3, n3, (zzacr)enum_4);
        Enum enum_5 = zzacr.zzb;
        int n10 = 4;
        zzabw zzabw35 = zzabw31;
        Enum enum_6 = enum_5;
        zze = zzabw31 = new zzabw("INT32", n10, 4, 1, (zzacr)enum_5);
        zzabwArray2 = enum_3;
        zzf = enum_3 = new zzabw("FIXED64", 5, 5, n3, (zzacr)enum_4);
        int n14 = 6;
        zzabwArray2 = zzabw35;
        int n15 = n14;
        zzg = zzabw35 = new zzabw("FIXED32", n14, n14, n3, (zzacr)enum_5);
        Enum enum_7 = zzacr.zzf;
        int n16 = 7;
        int n17 = 1;
        zzabw zzabw36 = zzabw30;
        Enum enum_8 = enum_7;
        zzh = zzabw30 = new zzabw("BOOL", n16, n16, n17, (zzacr)enum_7);
        Enum enum_9 = zzacr.zzg;
        n14 = 8;
        zzabwArray2 = zzabw36;
        n15 = n14;
        zzi = zzabw36 = new zzabw("STRING", n14, n14, n3, (zzacr)enum_9);
        zzacr zzacr2 = zzacr.zzj;
        int n18 = 9;
        zzabw zzabw37 = zzabw29;
        Enum enum_10 = zzacr2;
        zzj = zzabw29 = new zzabw("MESSAGE", n18, n18, 1, zzacr2);
        enum_8 = zzacr.zzh;
        n14 = 10;
        zzabwArray2 = enum_6;
        n15 = n14;
        zzk = enum_6 = new zzabw("BYTES", n14, n14, n3, (zzacr)enum_8);
        n14 = 11;
        zzabwArray2 = zzabw37;
        n15 = n14;
        zzl = zzabw37 = new zzabw("UINT32", n14, n14, n3, (zzacr)enum_5);
        Enum enum_11 = zzacr.zzi;
        int n19 = 12;
        int n20 = 1;
        zzabw zzabw38 = zzabw28;
        n18 = n19;
        Enum enum_12 = enum_11;
        zzm = zzabw28 = new zzabw("ENUM", n19, n19, n20, (zzacr)enum_11);
        n14 = 13;
        zzabwArray2 = zzabw38;
        n15 = n14;
        zzn = zzabw38 = new zzabw("SFIXED32", n14, n14, n3, (zzacr)enum_5);
        n14 = 14;
        zzabwArray2 = zzabw27;
        n15 = n14;
        zzo = zzabw27 = new zzabw("SFIXED64", n14, n14, n3, (zzacr)enum_4);
        n14 = 15;
        zzabwArray2 = zzabw26;
        n15 = n14;
        zzp = zzabw26 = new zzabw("SINT32", n14, n14, n3, (zzacr)enum_5);
        n14 = 16;
        zzabwArray2 = zzabw25;
        n15 = n14;
        zzq = zzabw25 = new zzabw("SINT64", n14, n14, n3, (zzacr)enum_4);
        n14 = 17;
        zzabwArray2 = enum_10;
        n15 = n14;
        zzr = enum_10 = new zzabw("GROUP", n14, n14, n3, zzacr2);
        n14 = 18;
        n3 = 2;
        zzabwArray2 = enum_12;
        n15 = n14;
        zzs = enum_12 = new zzabw("DOUBLE_LIST", n14, n14, n3, (zzacr)enum_);
        n14 = 19;
        zzabwArray2 = zzabw24;
        n15 = n14;
        zzt = zzabw24 = new zzabw("FLOAT_LIST", n14, n14, n3, (zzacr)enum_2);
        n14 = 20;
        zzabwArray2 = zzabw23;
        n15 = n14;
        zzu = zzabw23 = new zzabw("INT64_LIST", n14, n14, n3, (zzacr)enum_4);
        n14 = 21;
        zzabwArray2 = zzabw22;
        n15 = n14;
        zzv = zzabw22 = new zzabw("UINT64_LIST", n14, n14, n3, (zzacr)enum_4);
        n14 = 22;
        zzabwArray2 = zzabw21;
        n15 = n14;
        zzw = zzabw21 = new zzabw("INT32_LIST", n14, n14, n3, (zzacr)enum_5);
        n14 = 23;
        zzabwArray2 = zzabw20;
        n15 = n14;
        zzx = zzabw20 = new zzabw("FIXED64_LIST", n14, n14, n3, (zzacr)enum_4);
        n14 = 24;
        zzabwArray2 = zzabw19;
        n15 = n14;
        zzy = zzabw19 = new zzabw("FIXED32_LIST", n14, n14, n3, (zzacr)enum_5);
        n14 = 25;
        zzabwArray2 = zzabw18;
        n15 = n14;
        zzz = zzabw18 = new zzabw("BOOL_LIST", n14, n14, n3, (zzacr)enum_7);
        n14 = 26;
        zzabwArray2 = zzabw17;
        n15 = n14;
        zzA = zzabw17 = new zzabw("STRING_LIST", n14, n14, n3, (zzacr)enum_9);
        n14 = 27;
        zzabwArray2 = enum_9;
        n15 = n14;
        zzB = enum_9 = new zzabw("MESSAGE_LIST", n14, n14, n3, zzacr2);
        n14 = 28;
        zzabwArray2 = zzabw16;
        n15 = n14;
        zzC = zzabw16 = new zzabw("BYTES_LIST", n14, n14, n3, (zzacr)enum_8);
        n14 = 29;
        zzabwArray2 = enum_8;
        n15 = n14;
        zzD = enum_8 = new zzabw("UINT32_LIST", n14, n14, n3, (zzacr)enum_5);
        n14 = 30;
        zzabwArray2 = zzabw15;
        n15 = n14;
        zzE = zzabw15 = new zzabw("ENUM_LIST", n14, n14, n3, (zzacr)enum_11);
        n14 = 31;
        zzabwArray2 = zzabw14;
        n15 = n14;
        zzF = zzabw14 = new zzabw("SFIXED32_LIST", n14, n14, n3, (zzacr)enum_5);
        n14 = 32;
        zzabwArray2 = zzabw13;
        n15 = n14;
        zzG = zzabw13 = new zzabw("SFIXED64_LIST", n14, n14, n3, (zzacr)enum_4);
        n14 = 33;
        zzabwArray2 = zzabw12;
        n15 = n14;
        zzH = zzabw12 = new zzabw("SINT32_LIST", n14, n14, n3, (zzacr)enum_5);
        n14 = 34;
        zzabwArray2 = zzabw11;
        n15 = n14;
        zzI = zzabw11 = new zzabw("SINT64_LIST", n14, n14, n3, (zzacr)enum_4);
        n14 = 35;
        n3 = 3;
        zzabwArray2 = zzabw10;
        n15 = n14;
        zzJ = zzabw10 = new zzabw("DOUBLE_LIST_PACKED", n14, n14, n3, (zzacr)enum_);
        n14 = 36;
        zzabwArray2 = enum_;
        n15 = n14;
        zzK = enum_ = new zzabw("FLOAT_LIST_PACKED", n14, n14, n3, (zzacr)enum_2);
        n14 = 37;
        zzabwArray2 = enum_2;
        n15 = n14;
        zzL = enum_2 = new zzabw("INT64_LIST_PACKED", n14, n14, n3, (zzacr)enum_4);
        n14 = 38;
        zzabwArray2 = zzabw9;
        n15 = n14;
        zzM = zzabw9 = new zzabw("UINT64_LIST_PACKED", n14, n14, n3, (zzacr)enum_4);
        n14 = 39;
        zzabwArray2 = zzabw8;
        n15 = n14;
        zzN = zzabw8 = new zzabw("INT32_LIST_PACKED", n14, n14, n3, (zzacr)enum_5);
        n14 = 40;
        zzabwArray2 = zzabw7;
        n15 = n14;
        zzO = zzabw7 = new zzabw("FIXED64_LIST_PACKED", n14, n14, n3, (zzacr)enum_4);
        n14 = 41;
        zzabwArray2 = zzabw6;
        n15 = n14;
        zzP = zzabw6 = new zzabw("FIXED32_LIST_PACKED", n14, n14, n3, (zzacr)enum_5);
        n14 = 42;
        zzabwArray2 = zzabw5;
        n15 = n14;
        zzQ = zzabw5 = new zzabw("BOOL_LIST_PACKED", n14, n14, n3, (zzacr)enum_7);
        n14 = 43;
        zzabwArray2 = enum_7;
        n15 = n14;
        zzR = enum_7 = new zzabw("UINT32_LIST_PACKED", n14, n14, n3, (zzacr)enum_5);
        n14 = 44;
        zzabwArray2 = zzabw4;
        n15 = n14;
        zzS = zzabw4 = new zzabw("ENUM_LIST_PACKED", n14, n14, n3, (zzacr)enum_11);
        n14 = 45;
        zzabwArray2 = enum_11;
        n15 = n14;
        zzT = enum_11 = new zzabw("SFIXED32_LIST_PACKED", n14, n14, n3, (zzacr)enum_5);
        n14 = 46;
        zzabwArray2 = zzabw3;
        n15 = n14;
        zzU = zzabw3 = new zzabw("SFIXED64_LIST_PACKED", n14, n14, n3, (zzacr)enum_4);
        n14 = 47;
        zzabwArray2 = zzabw2;
        n15 = n14;
        zzV = zzabw2 = new zzabw("SINT32_LIST_PACKED", n14, n14, n3, (zzacr)enum_5);
        n14 = 48;
        zzabwArray2 = enum_5;
        n15 = n14;
        zzW = enum_5 = new zzabw("SINT64_LIST_PACKED", n14, n14, n3, (zzacr)enum_4);
        n14 = 49;
        n3 = 2;
        zzabwArray2 = enum_4;
        n15 = n14;
        zzX = enum_4 = new zzabw("GROUP_LIST", n14, n14, n3, zzacr2);
        int n21 = 4;
        zzacr zzacr3 = zzacr.zza;
        String string2 = "MAP";
        int n22 = 50;
        zzabwArray2 = new zzabw(string2, n22, n22, n21, zzacr3);
        zzY = zzabwArray2;
        zzabw[] zzabwArray3 = new zzabw[51];
        zzabwArray3[0] = zzabwArray;
        n14 = 1;
        zzabwArray3[n14] = zzabw33;
        zzabwArray3[n3] = zzabw34;
        zzabwArray3[3] = zzabw32;
        zzabwArray3[4] = zzabw31;
        zzabwArray3[5] = enum_3;
        zzabwArray3[6] = zzabw35;
        zzabwArray3[7] = zzabw30;
        zzabwArray3[8] = zzabw36;
        zzabwArray3[9] = zzabw29;
        zzabwArray3[10] = enum_6;
        zzabwArray3[11] = zzabw37;
        zzabwArray3[12] = zzabw28;
        zzabwArray3[13] = zzabw38;
        zzabwArray3[14] = zzabw27;
        zzabwArray3[15] = zzabw26;
        zzabwArray3[16] = zzabw25;
        zzabwArray3[17] = enum_10;
        zzabwArray3[18] = enum_12;
        zzabwArray3[19] = zzabw24;
        zzabwArray3[20] = zzabw23;
        zzabwArray3[21] = zzabw22;
        zzabwArray3[22] = zzabw21;
        zzabwArray3[23] = zzabw20;
        zzabwArray3[24] = zzabw19;
        zzabwArray3[25] = zzabw18;
        zzabwArray3[26] = zzabw17;
        zzabwArray3[27] = enum_9;
        zzabwArray3[28] = zzabw16;
        zzabwArray3[29] = enum_8;
        zzabwArray3[30] = zzabw15;
        zzabwArray3[31] = zzabw14;
        zzabwArray3[32] = zzabw13;
        zzabwArray3[33] = zzabw12;
        zzabwArray3[34] = zzabw11;
        zzabwArray3[35] = zzabw10;
        zzabwArray3[36] = enum_;
        zzabwArray3[37] = enum_2;
        zzabwArray3[38] = zzabw9;
        zzabwArray3[39] = zzabw8;
        zzabwArray3[40] = zzabw7;
        zzabwArray3[41] = zzabw6;
        zzabwArray3[42] = zzabw5;
        zzabwArray3[43] = enum_7;
        zzabwArray3[44] = zzabw4;
        zzabwArray3[45] = enum_11;
        zzabwArray3[46] = zzabw3;
        zzabwArray3[47] = zzabw2;
        zzabwArray3[48] = enum_5;
        zzabwArray3[49] = enum_4;
        n3 = 50;
        zzabwArray3[n3] = zzabwArray2;
        zzaa = zzabwArray3;
        zzabwArray2 = zzabw.values();
        int n24 = zzabwArray2.length;
        Object object = new zzabw[n24];
        zzZ = object;
        for (n15 = 0; n15 < n24; n15 += n14) {
            object = zzabwArray2[n15];
            int n25 = object.zzab;
            zzabwArray = zzZ;
            zzabwArray[n25] = object;
        }
    }

    /*
     * WARNING - Possible parameter corruption
     * WARNING - void declaration
     */
    private zzabw(zzacr object) {
        void var5_3;
        void var4_2;
        void var2_-1;
        void var1_-1;
        this.zzab = (int)object;
        void var6_4 = var4_2 + -1;
        boolean bl2 = true;
        if (var6_4 != bl2) {
            object = 3;
            if (var6_4 == object) {
                var5_3.zza();
            }
        } else {
            var5_3.zza();
        }
        if (var4_2 == bl2) {
            zzacr zzacr2 = zzacr.zza;
            var5_3.ordinal();
        }
    }

    public static zzabw[] values() {
        return (zzabw[])zzaa.clone();
    }

    public final int zza() {
        return this.zzab;
    }
}

