/*
 * Decompiled with CFR 0.152.
 */
package com.google.android.gms.internal.gtm;

import com.google.android.gms.internal.gtm.zzcz;
import com.google.android.gms.internal.gtm.zzda;
import com.google.android.gms.internal.gtm.zzdb;
import com.google.android.gms.internal.gtm.zzdc;
import com.google.android.gms.internal.gtm.zzdd;
import com.google.android.gms.internal.gtm.zzde;
import com.google.android.gms.internal.gtm.zzdf;
import com.google.android.gms.internal.gtm.zzdg;
import com.google.android.gms.internal.gtm.zzdh;
import com.google.android.gms.internal.gtm.zzdi;
import com.google.android.gms.internal.gtm.zzdj;
import com.google.android.gms.internal.gtm.zzdk;
import com.google.android.gms.internal.gtm.zzdl;
import com.google.android.gms.internal.gtm.zzdm;
import com.google.android.gms.internal.gtm.zzdn;
import com.google.android.gms.internal.gtm.zzdo;
import com.google.android.gms.internal.gtm.zzdp;
import com.google.android.gms.internal.gtm.zzdq;
import com.google.android.gms.internal.gtm.zzdr;
import com.google.android.gms.internal.gtm.zzds;
import com.google.android.gms.internal.gtm.zzdt;
import com.google.android.gms.internal.gtm.zzdu;
import com.google.android.gms.internal.gtm.zzdv;
import com.google.android.gms.internal.gtm.zzdw;
import com.google.android.gms.internal.gtm.zzdx;
import com.google.android.gms.internal.gtm.zzdy;
import com.google.android.gms.internal.gtm.zzdz;
import com.google.android.gms.internal.gtm.zzea;
import com.google.android.gms.internal.gtm.zzeb;
import com.google.android.gms.internal.gtm.zzec;
import com.google.android.gms.internal.gtm.zzed;
import com.google.android.gms.internal.gtm.zzee;
import com.google.android.gms.internal.gtm.zzef;
import com.google.android.gms.internal.gtm.zzeg;
import java.util.Collections;
import java.util.HashSet;

public final class zzeh {
    public static final zzeg zzA;
    public static final zzeg zzB;
    public static final zzeg zzC;
    public static final zzeg zzD;
    public static final zzeg zzE;
    public static final zzeg zzF;
    public static final zzeg zza;
    public static final zzeg zzb;
    public static final zzeg zzc;
    public static final zzeg zzd;
    public static final zzeg zze;
    public static final zzeg zzf;
    public static final zzeg zzg;
    public static final zzeg zzh;
    public static final zzeg zzi;
    public static final zzeg zzj;
    public static final zzeg zzk;
    public static final zzeg zzl;
    public static final zzeg zzm;
    public static final zzeg zzn;
    public static final zzeg zzo;
    public static final zzeg zzp;
    public static final zzeg zzq;
    public static final zzeg zzr;
    public static final zzeg zzs;
    public static final zzeg zzt;
    public static final zzeg zzu;
    public static final zzeg zzv;
    public static final zzeg zzw;
    public static final zzeg zzx;
    public static final zzeg zzy;
    public static final zzeg zzz;

    static {
        Object object = new HashSet();
        Collections.synchronizedSet(object);
        object = Boolean.TRUE;
        Object object2 = new zzda();
        zza = zzeg.zza(object, object, (zzef)object2);
        object = new zzdj();
        zzb = zzeg.zza("GAv4", "GAv4-SVC", (zzef)object);
        object = 2000;
        object2 = 20000;
        Object object3 = new zzdu();
        zzc = zzeg.zza(object, object2, (zzef)object3);
        object = 100;
        object2 = new zzdw();
        zzd = zzeg.zza(object, object, (zzef)object2);
        object = 1800000L;
        object2 = 120000L;
        object3 = new zzdx();
        zze = zzeg.zza(object, object2, (zzef)object3);
        object2 = 5000L;
        object3 = new zzdy();
        zzf = zzeg.zza(object2, object2, (zzef)object3);
        object3 = 0x6DDD00L;
        Object object4 = new zzdv();
        zzg = zzeg.zza(object3, object3, (zzef)object4);
        object3 = 32400000L;
        object4 = new zzdz();
        zzh = zzeg.zza(object3, object3, (zzef)object4);
        object3 = 20;
        object4 = new zzea();
        zzi = zzeg.zza(object3, object3, (zzef)object4);
        object4 = new zzeb();
        zzj = zzeg.zza(object3, object3, (zzef)object4);
        object3 = new zzec();
        object4 = "http://www.google-analytics.com";
        zzk = zzeg.zza(object4, object4, (zzef)object3);
        object3 = new zzed();
        object4 = "https://ssl.google-analytics.com";
        zzl = zzeg.zza(object4, object4, (zzef)object3);
        object3 = new zzee();
        object4 = "/collect";
        zzm = zzeg.zza(object4, object4, (zzef)object3);
        object3 = new zzcz();
        object4 = "/batch";
        zzn = zzeg.zza(object4, object4, (zzef)object3);
        object3 = 2036;
        object4 = new zzdb();
        zzo = zzeg.zza(object3, object3, (zzef)object4);
        object3 = new zzdc();
        object4 = "BATCH_BY_COUNT";
        zzp = zzeg.zza(object4, object4, (zzef)object3);
        object3 = new zzdd();
        object4 = "GZIP";
        zzq = zzeg.zza(object4, object4, (zzef)object3);
        object3 = 8192;
        object4 = new zzde();
        zzr = zzeg.zza(object3, object3, (zzef)object4);
        object4 = new zzdf();
        zzs = zzeg.zza(object3, object3, (zzef)object4);
        object4 = new zzdg();
        zzt = zzeg.zza(object3, object3, (zzef)object4);
        object3 = new zzdh();
        object4 = "404,502";
        zzu = zzeg.zza(object4, object4, (zzef)object3);
        object3 = 3600;
        object4 = new zzdi();
        zzv = zzeg.zza(object3, object3, (zzef)object4);
        object3 = 60000;
        object4 = new zzdk();
        zzw = zzeg.zza(object3, object3, (zzef)object4);
        object3 = 61000;
        object4 = new zzdl();
        zzx = zzeg.zza(object3, object3, (zzef)object4);
        object3 = 86400000L;
        object4 = new zzdm();
        zzy = zzeg.zza(object3, object3, (zzef)object4);
        object4 = Boolean.FALSE;
        Object object5 = new zzdn();
        zzz = zzeg.zza(object4, object4, (zzef)object5);
        object5 = 10000L;
        zzdo zzdo2 = new zzdo();
        zzA = zzeg.zza(object5, object5, zzdo2);
        object5 = new zzdp();
        zzB = zzeg.zza(object2, object2, (zzef)object5);
        object5 = new zzdq();
        zzC = zzeg.zza(object, object, (zzef)object5);
        object = new zzdr();
        zzD = zzeg.zza(object3, object3, (zzef)object);
        object = new zzds();
        zzE = zzeg.zza(object2, object2, (zzef)object);
        object = new zzdt();
        zzF = zzeg.zza(object4, object4, (zzef)object);
    }
}

