/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  android.content.pm.ApplicationInfo
 *  android.content.pm.PackageInfo
 *  android.os.Bundle
 *  android.os.Parcel
 *  android.os.Parcelable
 *  android.os.Parcelable$Creator
 */
package com.google.android.gms.internal.ads;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.ads.internal.client.zzdu;
import com.google.android.gms.ads.internal.client.zzl;
import com.google.android.gms.ads.internal.client.zzq;
import com.google.android.gms.ads.internal.util.client.VersionInfoParcel;
import com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable;
import com.google.android.gms.common.internal.safeparcel.SafeParcelWriter;
import com.google.android.gms.internal.ads.zzbhk;
import com.google.android.gms.internal.ads.zzbnz;
import com.google.android.gms.internal.ads.zzbwt;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public final class zzbws
extends AbstractSafeParcelable {
    public static final Parcelable.Creator CREATOR;
    public final long zzA;
    public final String zzB;
    public final float zzC;
    public final int zzD;
    public final int zzE;
    public final boolean zzF;
    public final String zzG;
    public final boolean zzH;
    public final String zzI;
    public final boolean zzJ;
    public final int zzK;
    public final Bundle zzL;
    public final String zzM;
    public final zzdu zzN;
    public final boolean zzO;
    public final Bundle zzP;
    public final String zzQ;
    public final String zzR;
    public final String zzS;
    public final boolean zzT;
    public final List zzU;
    public final String zzV;
    public final List zzW;
    public final int zzX;
    public final boolean zzY;
    public final boolean zzZ;
    public final int zza;
    public final boolean zzaa;
    public final ArrayList zzab;
    public final String zzac;
    public final zzbnz zzad;
    public final String zzae;
    public final Bundle zzaf;
    public final Bundle zzb;
    public final zzl zzc;
    public final zzq zzd;
    public final String zze;
    public final ApplicationInfo zzf;
    public final PackageInfo zzg;
    public final String zzh;
    public final String zzi;
    public final String zzj;
    public final VersionInfoParcel zzk;
    public final Bundle zzl;
    public final int zzm;
    public final List zzn;
    public final Bundle zzo;
    public final boolean zzp;
    public final int zzq;
    public final int zzr;
    public final float zzs;
    public final String zzt;
    public final long zzu;
    public final String zzv;
    public final List zzw;
    public final String zzx;
    public final zzbhk zzy;
    public final List zzz;

    static {
        zzbwt zzbwt2 = new zzbwt();
        CREATOR = zzbwt2;
    }

    public zzbws(int n3, Bundle bundle, zzl zzl2, zzq zzq2, String string2, ApplicationInfo applicationInfo, PackageInfo packageInfo, String string3, String string4, String string5, VersionInfoParcel versionInfoParcel, Bundle bundle2, int n4, List list, Bundle bundle3, boolean bl2, int n7, int n8, float f5, String string6, long l2, String string7, List list2, String string8, zzbhk zzbhk2, List list3, long l3, String string9, float f6, boolean bl3, int n10, int n14, boolean bl4, String string10, String string11, boolean bl5, int n15, Bundle bundle4, String string12, zzdu zzdu2, boolean bl6, Bundle bundle5, String string13, String string14, String string15, boolean bl7, List list4, String string16, List list5, int n16, boolean bl8, boolean bl9, boolean bl10, ArrayList arrayList, String string17, zzbnz zzbnz2, String string18, Bundle bundle6) {
        zzbws zzbws2 = this;
        this.zza = n3;
        Object object = bundle;
        this.zzb = bundle;
        object = zzl2;
        this.zzc = zzl2;
        object = zzq2;
        this.zzd = zzq2;
        object = string2;
        this.zze = string2;
        object = applicationInfo;
        this.zzf = applicationInfo;
        object = packageInfo;
        this.zzg = packageInfo;
        object = string3;
        this.zzh = string3;
        object = string4;
        this.zzi = string4;
        object = string5;
        this.zzj = string5;
        object = versionInfoParcel;
        this.zzk = versionInfoParcel;
        object = bundle2;
        this.zzl = bundle2;
        this.zzm = n4;
        object = list;
        this.zzn = list;
        object = list3 == null ? Collections.emptyList() : Collections.unmodifiableList(list3);
        zzbws2.zzz = object;
        object = bundle3;
        zzbws2.zzo = bundle3;
        zzbws2.zzp = bl2;
        zzbws2.zzq = n7;
        zzbws2.zzr = n8;
        zzbws2.zzs = f5;
        object = string6;
        zzbws2.zzt = string6;
        zzbws2.zzu = l2;
        object = string7;
        zzbws2.zzv = string7;
        object = list2 == null ? Collections.emptyList() : Collections.unmodifiableList(list2);
        zzbws2.zzw = object;
        object = string8;
        zzbws2.zzx = string8;
        object = zzbhk2;
        zzbws2.zzy = zzbhk2;
        zzbws2.zzA = l3;
        object = string9;
        zzbws2.zzB = string9;
        zzbws2.zzC = f6;
        zzbws2.zzH = bl3;
        zzbws2.zzD = n10;
        zzbws2.zzE = n14;
        zzbws2.zzF = bl4;
        object = string10;
        zzbws2.zzG = string10;
        object = string11;
        zzbws2.zzI = string11;
        zzbws2.zzJ = bl5;
        zzbws2.zzK = n15;
        object = bundle4;
        zzbws2.zzL = bundle4;
        object = string12;
        zzbws2.zzM = string12;
        object = zzdu2;
        zzbws2.zzN = zzdu2;
        zzbws2.zzO = bl6;
        object = bundle5;
        zzbws2.zzP = bundle5;
        object = string13;
        zzbws2.zzQ = string13;
        object = string14;
        zzbws2.zzR = string14;
        object = string15;
        zzbws2.zzS = string15;
        zzbws2.zzT = bl7;
        object = list4;
        zzbws2.zzU = list4;
        object = string16;
        zzbws2.zzV = string16;
        object = list5;
        zzbws2.zzW = list5;
        zzbws2.zzX = n16;
        zzbws2.zzY = bl8;
        zzbws2.zzZ = bl9;
        zzbws2.zzaa = bl10;
        object = arrayList;
        zzbws2.zzab = arrayList;
        object = string17;
        zzbws2.zzac = string17;
        object = zzbnz2;
        zzbws2.zzad = zzbnz2;
        object = string18;
        zzbws2.zzae = string18;
        object = bundle6;
        zzbws2.zzaf = bundle6;
    }

    public final void writeToParcel(Parcel parcel, int n3) {
        int n4 = this.zza;
        int n7 = SafeParcelWriter.beginObjectHeader(parcel);
        SafeParcelWriter.writeInt(parcel, 1, n4);
        Object object = this.zzb;
        SafeParcelWriter.writeBundle(parcel, 2, object, false);
        Object object2 = this.zzc;
        SafeParcelWriter.writeParcelable(parcel, 3, (Parcelable)object2, n3, false);
        object2 = this.zzd;
        SafeParcelWriter.writeParcelable(parcel, 4, (Parcelable)object2, n3, false);
        object2 = this.zze;
        SafeParcelWriter.writeString(parcel, 5, (String)object2, false);
        object2 = this.zzf;
        SafeParcelWriter.writeParcelable(parcel, 6, (Parcelable)object2, n3, false);
        object2 = this.zzg;
        SafeParcelWriter.writeParcelable(parcel, 7, (Parcelable)object2, n3, false);
        object2 = this.zzh;
        SafeParcelWriter.writeString(parcel, 8, (String)object2, false);
        object2 = this.zzi;
        SafeParcelWriter.writeString(parcel, 9, (String)object2, false);
        object2 = this.zzj;
        SafeParcelWriter.writeString(parcel, 10, (String)object2, false);
        object2 = this.zzk;
        SafeParcelWriter.writeParcelable(parcel, 11, (Parcelable)object2, n3, false);
        object2 = this.zzl;
        SafeParcelWriter.writeBundle(parcel, 12, (Bundle)object2, false);
        int bl2 = this.zzm;
        SafeParcelWriter.writeInt(parcel, 13, bl2);
        object2 = this.zzn;
        SafeParcelWriter.writeStringList(parcel, 14, (List)object2, false);
        object2 = this.zzo;
        SafeParcelWriter.writeBundle(parcel, 15, (Bundle)object2, false);
        boolean bl3 = this.zzp;
        SafeParcelWriter.writeBoolean(parcel, 16, bl3);
        int n8 = this.zzq;
        SafeParcelWriter.writeInt(parcel, 18, n8);
        int n10 = this.zzr;
        SafeParcelWriter.writeInt(parcel, 19, n10);
        float f5 = this.zzs;
        SafeParcelWriter.writeFloat(parcel, 20, f5);
        object2 = this.zzt;
        SafeParcelWriter.writeString(parcel, 21, (String)object2, false);
        long l2 = this.zzu;
        SafeParcelWriter.writeLong(parcel, 25, l2);
        object2 = this.zzv;
        SafeParcelWriter.writeString(parcel, 26, (String)object2, false);
        object2 = this.zzw;
        SafeParcelWriter.writeStringList(parcel, 27, (List)object2, false);
        object2 = this.zzx;
        SafeParcelWriter.writeString(parcel, 28, (String)object2, false);
        object2 = this.zzy;
        SafeParcelWriter.writeParcelable(parcel, 29, (Parcelable)object2, n3, false);
        object2 = this.zzz;
        SafeParcelWriter.writeStringList(parcel, 30, (List)object2, false);
        l2 = this.zzA;
        SafeParcelWriter.writeLong(parcel, 31, l2);
        object2 = this.zzB;
        SafeParcelWriter.writeString(parcel, 33, (String)object2, false);
        f5 = this.zzC;
        SafeParcelWriter.writeFloat(parcel, 34, f5);
        int n14 = this.zzD;
        SafeParcelWriter.writeInt(parcel, 35, n14);
        int n15 = this.zzE;
        SafeParcelWriter.writeInt(parcel, 36, n15);
        boolean bl4 = this.zzF;
        SafeParcelWriter.writeBoolean(parcel, 37, bl4);
        object2 = this.zzG;
        SafeParcelWriter.writeString(parcel, 39, (String)object2, false);
        boolean bl5 = this.zzH;
        SafeParcelWriter.writeBoolean(parcel, 40, bl5);
        object2 = this.zzI;
        SafeParcelWriter.writeString(parcel, 41, (String)object2, false);
        boolean bl6 = this.zzJ;
        SafeParcelWriter.writeBoolean(parcel, 42, bl6);
        int n16 = this.zzK;
        SafeParcelWriter.writeInt(parcel, 43, n16);
        object2 = this.zzL;
        SafeParcelWriter.writeBundle(parcel, 44, (Bundle)object2, false);
        object2 = this.zzM;
        SafeParcelWriter.writeString(parcel, 45, (String)object2, false);
        object2 = this.zzN;
        SafeParcelWriter.writeParcelable(parcel, 46, (Parcelable)object2, n3, false);
        boolean bl7 = this.zzO;
        SafeParcelWriter.writeBoolean(parcel, 47, bl7);
        object2 = this.zzP;
        SafeParcelWriter.writeBundle(parcel, 48, (Bundle)object2, false);
        object2 = this.zzQ;
        SafeParcelWriter.writeString(parcel, 49, (String)object2, false);
        object2 = this.zzR;
        SafeParcelWriter.writeString(parcel, 50, (String)object2, false);
        object2 = this.zzS;
        SafeParcelWriter.writeString(parcel, 51, (String)object2, false);
        boolean bl8 = this.zzT;
        SafeParcelWriter.writeBoolean(parcel, 52, bl8);
        object2 = this.zzU;
        SafeParcelWriter.writeIntegerList(parcel, 53, (List)object2, false);
        object2 = this.zzV;
        SafeParcelWriter.writeString(parcel, 54, (String)object2, false);
        object2 = this.zzW;
        SafeParcelWriter.writeStringList(parcel, 55, (List)object2, false);
        int n17 = this.zzX;
        SafeParcelWriter.writeInt(parcel, 56, n17);
        boolean bl9 = this.zzY;
        SafeParcelWriter.writeBoolean(parcel, 57, bl9);
        boolean bl10 = this.zzZ;
        SafeParcelWriter.writeBoolean(parcel, 58, bl10);
        boolean bl11 = this.zzaa;
        SafeParcelWriter.writeBoolean(parcel, 59, bl11);
        object2 = this.zzab;
        SafeParcelWriter.writeStringList(parcel, 60, (List)object2, false);
        object2 = this.zzac;
        SafeParcelWriter.writeString(parcel, 61, (String)object2, false);
        object2 = this.zzad;
        SafeParcelWriter.writeParcelable(parcel, 63, (Parcelable)object2, n3, false);
        object = this.zzae;
        SafeParcelWriter.writeString(parcel, 64, (String)object, false);
        object = this.zzaf;
        SafeParcelWriter.writeBundle(parcel, 65, object, false);
        SafeParcelWriter.finishObjectHeader(parcel, n7);
    }
}

