/*
 * Decompiled with CFR 0.152.
 */
package com.google.android.gms.internal.ads;

import com.google.android.gms.internal.ads.zzhcf;

public final class zzhbe
extends Enum {
    public static final /* enum */ zzhbe zzA;
    public static final /* enum */ zzhbe zzB;
    public static final /* enum */ zzhbe zzC;
    public static final /* enum */ zzhbe zzD;
    public static final /* enum */ zzhbe zzE;
    public static final /* enum */ zzhbe zzF;
    public static final /* enum */ zzhbe zzG;
    public static final /* enum */ zzhbe zzH;
    public static final /* enum */ zzhbe zzI;
    public static final /* enum */ zzhbe zzJ;
    public static final /* enum */ zzhbe zzK;
    public static final /* enum */ zzhbe zzL;
    public static final /* enum */ zzhbe zzM;
    public static final /* enum */ zzhbe zzN;
    public static final /* enum */ zzhbe zzO;
    public static final /* enum */ zzhbe zzP;
    public static final /* enum */ zzhbe zzQ;
    public static final /* enum */ zzhbe zzR;
    public static final /* enum */ zzhbe zzS;
    public static final /* enum */ zzhbe zzT;
    public static final /* enum */ zzhbe zzU;
    public static final /* enum */ zzhbe zzV;
    public static final /* enum */ zzhbe zzW;
    public static final /* enum */ zzhbe zzX;
    public static final /* enum */ zzhbe zzY;
    private static final zzhbe[] zzZ;
    public static final /* enum */ zzhbe zza;
    private static final /* synthetic */ zzhbe[] zzaa;
    public static final /* enum */ zzhbe zzb;
    public static final /* enum */ zzhbe zzc;
    public static final /* enum */ zzhbe zzd;
    public static final /* enum */ zzhbe zze;
    public static final /* enum */ zzhbe zzf;
    public static final /* enum */ zzhbe zzg;
    public static final /* enum */ zzhbe zzh;
    public static final /* enum */ zzhbe zzi;
    public static final /* enum */ zzhbe zzj;
    public static final /* enum */ zzhbe zzk;
    public static final /* enum */ zzhbe zzl;
    public static final /* enum */ zzhbe zzm;
    public static final /* enum */ zzhbe zzn;
    public static final /* enum */ zzhbe zzo;
    public static final /* enum */ zzhbe zzp;
    public static final /* enum */ zzhbe zzq;
    public static final /* enum */ zzhbe zzr;
    public static final /* enum */ zzhbe zzs;
    public static final /* enum */ zzhbe zzt;
    public static final /* enum */ zzhbe zzu;
    public static final /* enum */ zzhbe zzv;
    public static final /* enum */ zzhbe zzw;
    public static final /* enum */ zzhbe zzx;
    public static final /* enum */ zzhbe zzy;
    public static final /* enum */ zzhbe zzz;
    private final zzhcf zzab;
    private final int zzac;
    private final Class zzad;

    static {
        zzhbe zzhbe2;
        zzhbe zzhbe3;
        zzhbe zzhbe4;
        zzhbe zzhbe5;
        zzhbe zzhbe6;
        zzhbe zzhbe7;
        zzhbe zzhbe8;
        zzhbe zzhbe9;
        zzhbe zzhbe10;
        zzhbe zzhbe11;
        zzhbe zzhbe12;
        zzhbe zzhbe13;
        zzhbe zzhbe14;
        zzhbe zzhbe15;
        zzhbe zzhbe16;
        zzhbe zzhbe17;
        zzhbe zzhbe18;
        zzhbe zzhbe19;
        zzhbe zzhbe20;
        zzhbe zzhbe21;
        zzhbe zzhbe22;
        zzhbe zzhbe23;
        zzhbe zzhbe24;
        zzhbe zzhbe25;
        zzhbe zzhbe26;
        zzhbe zzhbe27;
        zzhbe zzhbe28;
        zzhbe zzhbe29;
        zzhbe zzhbe30;
        zzhbe zzhbe31;
        zzhbe zzhbe32;
        zzhbe zzhbe33;
        zzhbe[] zzhbeArray;
        Enum enum_ = zzhcf.zze;
        int n3 = 1;
        zzhbe[] zzhbeArray2 = zzhbeArray;
        zzhbeArray = new zzhbe("DOUBLE", 0, 0, n3, (zzhcf)enum_);
        zza = zzhbeArray;
        Enum enum_2 = zzhcf.zzd;
        int n4 = 1;
        int n7 = 1;
        int n8 = 1;
        zzhbe zzhbe34 = zzhbe33;
        Enum enum_3 = enum_2;
        zzb = zzhbe33 = new zzhbe("FLOAT", n8, n4, n7, (zzhcf)enum_2);
        Enum enum_4 = zzhcf.zzc;
        zzhbeArray2 = zzhbe34;
        zzc = zzhbe34 = new zzhbe("INT64", 2, 2, n3, (zzhcf)enum_4);
        zzhbeArray2 = zzhbe32;
        zzd = zzhbe32 = new zzhbe("UINT64", 3, 3, n3, (zzhcf)enum_4);
        Enum enum_5 = zzhcf.zzb;
        int n10 = 4;
        zzhbe zzhbe35 = zzhbe31;
        Enum enum_6 = enum_5;
        zze = zzhbe31 = new zzhbe("INT32", n10, 4, 1, (zzhcf)enum_5);
        zzhbeArray2 = enum_3;
        zzf = enum_3 = new zzhbe("FIXED64", 5, 5, n3, (zzhcf)enum_4);
        int n14 = 6;
        zzhbeArray2 = zzhbe35;
        int n15 = n14;
        zzg = zzhbe35 = new zzhbe("FIXED32", n14, n14, n3, (zzhcf)enum_5);
        Enum enum_7 = zzhcf.zzf;
        int n16 = 7;
        int n17 = 1;
        zzhbe zzhbe36 = zzhbe30;
        Enum enum_8 = enum_7;
        zzh = zzhbe30 = new zzhbe("BOOL", n16, n16, n17, (zzhcf)enum_7);
        Enum enum_9 = zzhcf.zzg;
        n14 = 8;
        zzhbeArray2 = zzhbe36;
        n15 = n14;
        zzi = zzhbe36 = new zzhbe("STRING", n14, n14, n3, (zzhcf)enum_9);
        zzhcf zzhcf2 = zzhcf.zzj;
        int n18 = 9;
        zzhbe zzhbe37 = zzhbe29;
        Enum enum_10 = zzhcf2;
        zzj = zzhbe29 = new zzhbe("MESSAGE", n18, n18, 1, zzhcf2);
        enum_8 = zzhcf.zzh;
        n14 = 10;
        zzhbeArray2 = enum_6;
        n15 = n14;
        zzk = enum_6 = new zzhbe("BYTES", n14, n14, n3, (zzhcf)enum_8);
        n14 = 11;
        zzhbeArray2 = zzhbe37;
        n15 = n14;
        zzl = zzhbe37 = new zzhbe("UINT32", n14, n14, n3, (zzhcf)enum_5);
        Enum enum_11 = zzhcf.zzi;
        int n19 = 12;
        int n20 = 1;
        zzhbe zzhbe38 = zzhbe28;
        n18 = n19;
        Enum enum_12 = enum_11;
        zzm = zzhbe28 = new zzhbe("ENUM", n19, n19, n20, (zzhcf)enum_11);
        n14 = 13;
        zzhbeArray2 = zzhbe38;
        n15 = n14;
        zzn = zzhbe38 = new zzhbe("SFIXED32", n14, n14, n3, (zzhcf)enum_5);
        n14 = 14;
        zzhbeArray2 = zzhbe27;
        n15 = n14;
        zzo = zzhbe27 = new zzhbe("SFIXED64", n14, n14, n3, (zzhcf)enum_4);
        n14 = 15;
        zzhbeArray2 = zzhbe26;
        n15 = n14;
        zzp = zzhbe26 = new zzhbe("SINT32", n14, n14, n3, (zzhcf)enum_5);
        n14 = 16;
        zzhbeArray2 = zzhbe25;
        n15 = n14;
        zzq = zzhbe25 = new zzhbe("SINT64", n14, n14, n3, (zzhcf)enum_4);
        n14 = 17;
        zzhbeArray2 = enum_10;
        n15 = n14;
        zzr = enum_10 = new zzhbe("GROUP", n14, n14, n3, zzhcf2);
        n14 = 18;
        n3 = 2;
        zzhbeArray2 = enum_12;
        n15 = n14;
        zzs = enum_12 = new zzhbe("DOUBLE_LIST", n14, n14, n3, (zzhcf)enum_);
        n14 = 19;
        zzhbeArray2 = zzhbe24;
        n15 = n14;
        zzt = zzhbe24 = new zzhbe("FLOAT_LIST", n14, n14, n3, (zzhcf)enum_2);
        n14 = 20;
        zzhbeArray2 = zzhbe23;
        n15 = n14;
        zzu = zzhbe23 = new zzhbe("INT64_LIST", n14, n14, n3, (zzhcf)enum_4);
        n14 = 21;
        zzhbeArray2 = zzhbe22;
        n15 = n14;
        zzv = zzhbe22 = new zzhbe("UINT64_LIST", n14, n14, n3, (zzhcf)enum_4);
        n14 = 22;
        zzhbeArray2 = zzhbe21;
        n15 = n14;
        zzw = zzhbe21 = new zzhbe("INT32_LIST", n14, n14, n3, (zzhcf)enum_5);
        n14 = 23;
        zzhbeArray2 = zzhbe20;
        n15 = n14;
        zzx = zzhbe20 = new zzhbe("FIXED64_LIST", n14, n14, n3, (zzhcf)enum_4);
        n14 = 24;
        zzhbeArray2 = zzhbe19;
        n15 = n14;
        zzy = zzhbe19 = new zzhbe("FIXED32_LIST", n14, n14, n3, (zzhcf)enum_5);
        n14 = 25;
        zzhbeArray2 = zzhbe18;
        n15 = n14;
        zzz = zzhbe18 = new zzhbe("BOOL_LIST", n14, n14, n3, (zzhcf)enum_7);
        n14 = 26;
        zzhbeArray2 = zzhbe17;
        n15 = n14;
        zzA = zzhbe17 = new zzhbe("STRING_LIST", n14, n14, n3, (zzhcf)enum_9);
        n14 = 27;
        zzhbeArray2 = enum_9;
        n15 = n14;
        zzB = enum_9 = new zzhbe("MESSAGE_LIST", n14, n14, n3, zzhcf2);
        n14 = 28;
        zzhbeArray2 = zzhbe16;
        n15 = n14;
        zzC = zzhbe16 = new zzhbe("BYTES_LIST", n14, n14, n3, (zzhcf)enum_8);
        n14 = 29;
        zzhbeArray2 = enum_8;
        n15 = n14;
        zzD = enum_8 = new zzhbe("UINT32_LIST", n14, n14, n3, (zzhcf)enum_5);
        n14 = 30;
        zzhbeArray2 = zzhbe15;
        n15 = n14;
        zzE = zzhbe15 = new zzhbe("ENUM_LIST", n14, n14, n3, (zzhcf)enum_11);
        n14 = 31;
        zzhbeArray2 = zzhbe14;
        n15 = n14;
        zzF = zzhbe14 = new zzhbe("SFIXED32_LIST", n14, n14, n3, (zzhcf)enum_5);
        n14 = 32;
        zzhbeArray2 = zzhbe13;
        n15 = n14;
        zzG = zzhbe13 = new zzhbe("SFIXED64_LIST", n14, n14, n3, (zzhcf)enum_4);
        n14 = 33;
        zzhbeArray2 = zzhbe12;
        n15 = n14;
        zzH = zzhbe12 = new zzhbe("SINT32_LIST", n14, n14, n3, (zzhcf)enum_5);
        n14 = 34;
        zzhbeArray2 = zzhbe11;
        n15 = n14;
        zzI = zzhbe11 = new zzhbe("SINT64_LIST", n14, n14, n3, (zzhcf)enum_4);
        n14 = 35;
        n3 = 3;
        zzhbeArray2 = zzhbe10;
        n15 = n14;
        zzJ = zzhbe10 = new zzhbe("DOUBLE_LIST_PACKED", n14, n14, n3, (zzhcf)enum_);
        n14 = 36;
        zzhbeArray2 = enum_;
        n15 = n14;
        zzK = enum_ = new zzhbe("FLOAT_LIST_PACKED", n14, n14, n3, (zzhcf)enum_2);
        n14 = 37;
        zzhbeArray2 = enum_2;
        n15 = n14;
        zzL = enum_2 = new zzhbe("INT64_LIST_PACKED", n14, n14, n3, (zzhcf)enum_4);
        n14 = 38;
        zzhbeArray2 = zzhbe9;
        n15 = n14;
        zzM = zzhbe9 = new zzhbe("UINT64_LIST_PACKED", n14, n14, n3, (zzhcf)enum_4);
        n14 = 39;
        zzhbeArray2 = zzhbe8;
        n15 = n14;
        zzN = zzhbe8 = new zzhbe("INT32_LIST_PACKED", n14, n14, n3, (zzhcf)enum_5);
        n14 = 40;
        zzhbeArray2 = zzhbe7;
        n15 = n14;
        zzO = zzhbe7 = new zzhbe("FIXED64_LIST_PACKED", n14, n14, n3, (zzhcf)enum_4);
        n14 = 41;
        zzhbeArray2 = zzhbe6;
        n15 = n14;
        zzP = zzhbe6 = new zzhbe("FIXED32_LIST_PACKED", n14, n14, n3, (zzhcf)enum_5);
        n14 = 42;
        zzhbeArray2 = zzhbe5;
        n15 = n14;
        zzQ = zzhbe5 = new zzhbe("BOOL_LIST_PACKED", n14, n14, n3, (zzhcf)enum_7);
        n14 = 43;
        zzhbeArray2 = enum_7;
        n15 = n14;
        zzR = enum_7 = new zzhbe("UINT32_LIST_PACKED", n14, n14, n3, (zzhcf)enum_5);
        n14 = 44;
        zzhbeArray2 = zzhbe4;
        n15 = n14;
        zzS = zzhbe4 = new zzhbe("ENUM_LIST_PACKED", n14, n14, n3, (zzhcf)enum_11);
        n14 = 45;
        zzhbeArray2 = enum_11;
        n15 = n14;
        zzT = enum_11 = new zzhbe("SFIXED32_LIST_PACKED", n14, n14, n3, (zzhcf)enum_5);
        n14 = 46;
        zzhbeArray2 = zzhbe3;
        n15 = n14;
        zzU = zzhbe3 = new zzhbe("SFIXED64_LIST_PACKED", n14, n14, n3, (zzhcf)enum_4);
        n14 = 47;
        zzhbeArray2 = zzhbe2;
        n15 = n14;
        zzV = zzhbe2 = new zzhbe("SINT32_LIST_PACKED", n14, n14, n3, (zzhcf)enum_5);
        n14 = 48;
        zzhbeArray2 = enum_5;
        n15 = n14;
        zzW = enum_5 = new zzhbe("SINT64_LIST_PACKED", n14, n14, n3, (zzhcf)enum_4);
        n14 = 49;
        n3 = 2;
        zzhbeArray2 = enum_4;
        n15 = n14;
        zzX = enum_4 = new zzhbe("GROUP_LIST", n14, n14, n3, zzhcf2);
        int n21 = 4;
        zzhcf zzhcf3 = zzhcf.zza;
        String string2 = "MAP";
        int n22 = 50;
        zzhbeArray2 = new zzhbe(string2, n22, n22, n21, zzhcf3);
        zzY = zzhbeArray2;
        zzhbe[] zzhbeArray3 = new zzhbe[51];
        zzhbeArray3[0] = zzhbeArray;
        n14 = 1;
        zzhbeArray3[n14] = zzhbe33;
        zzhbeArray3[n3] = zzhbe34;
        zzhbeArray3[3] = zzhbe32;
        zzhbeArray3[4] = zzhbe31;
        zzhbeArray3[5] = enum_3;
        zzhbeArray3[6] = zzhbe35;
        zzhbeArray3[7] = zzhbe30;
        zzhbeArray3[8] = zzhbe36;
        zzhbeArray3[9] = zzhbe29;
        zzhbeArray3[10] = enum_6;
        zzhbeArray3[11] = zzhbe37;
        zzhbeArray3[12] = zzhbe28;
        zzhbeArray3[13] = zzhbe38;
        zzhbeArray3[14] = zzhbe27;
        zzhbeArray3[15] = zzhbe26;
        zzhbeArray3[16] = zzhbe25;
        zzhbeArray3[17] = enum_10;
        zzhbeArray3[18] = enum_12;
        zzhbeArray3[19] = zzhbe24;
        zzhbeArray3[20] = zzhbe23;
        zzhbeArray3[21] = zzhbe22;
        zzhbeArray3[22] = zzhbe21;
        zzhbeArray3[23] = zzhbe20;
        zzhbeArray3[24] = zzhbe19;
        zzhbeArray3[25] = zzhbe18;
        zzhbeArray3[26] = zzhbe17;
        zzhbeArray3[27] = enum_9;
        zzhbeArray3[28] = zzhbe16;
        zzhbeArray3[29] = enum_8;
        zzhbeArray3[30] = zzhbe15;
        zzhbeArray3[31] = zzhbe14;
        zzhbeArray3[32] = zzhbe13;
        zzhbeArray3[33] = zzhbe12;
        zzhbeArray3[34] = zzhbe11;
        zzhbeArray3[35] = zzhbe10;
        zzhbeArray3[36] = enum_;
        zzhbeArray3[37] = enum_2;
        zzhbeArray3[38] = zzhbe9;
        zzhbeArray3[39] = zzhbe8;
        zzhbeArray3[40] = zzhbe7;
        zzhbeArray3[41] = zzhbe6;
        zzhbeArray3[42] = zzhbe5;
        zzhbeArray3[43] = enum_7;
        zzhbeArray3[44] = zzhbe4;
        zzhbeArray3[45] = enum_11;
        zzhbeArray3[46] = zzhbe3;
        zzhbeArray3[47] = zzhbe2;
        zzhbeArray3[48] = enum_5;
        zzhbeArray3[49] = enum_4;
        n3 = 50;
        zzhbeArray3[n3] = zzhbeArray2;
        zzaa = zzhbeArray3;
        zzhbeArray2 = zzhbe.values();
        int n24 = zzhbeArray2.length;
        Object object = new zzhbe[n24];
        zzZ = object;
        for (n15 = 0; n15 < n24; n15 += n14) {
            object = zzhbeArray2[n15];
            int n25 = object.zzac;
            zzhbeArray = zzZ;
            zzhbeArray[n25] = object;
        }
    }

    /*
     * WARNING - Possible parameter corruption
     * WARNING - void declaration
     */
    private zzhbe(zzhcf object) {
        Object object2;
        void var4_2;
        void var5_3;
        void var2_-1;
        void var1_-1;
        this.zzac = (int)object;
        this.zzab = var5_3;
        boolean bl2 = var4_2 + -1;
        boolean bl3 = true;
        if (bl2 != bl3) {
            object = 3;
            if (bl2 != object) {
                bl2 = false;
                object2 = null;
                this.zzad = null;
            } else {
                this.zzad = object2 = var5_3.zza();
            }
        } else {
            this.zzad = object2 = var5_3.zza();
        }
        if (var4_2 == bl3) {
            object2 = zzhcf.zza;
            var5_3.ordinal();
        }
    }

    public static zzhbe[] values() {
        return (zzhbe[])zzaa.clone();
    }

    public final int zza() {
        return this.zzac;
    }
}

