/*
 * Decompiled with CFR 0.152.
 */
public final class CF3 {
    public static final mm$d a;
    public static final mm$d b;
    public static final mm$d c;
    public static final mm$d d;

    static {
        String string2 = "VISUAL_STATE_CALLBACK";
        mm mm2 = new mm(string2, string2);
        string2 = "OFF_SCREEN_PRERASTER";
        mm2 = new mm(string2, string2);
        string2 = "SAFE_BROWSING_ENABLE";
        mm2 = new mm(string2, string2);
        string2 = "DISABLED_ACTION_MODE_MENU_ITEMS";
        mm2 = new mm(string2, string2);
        string2 = "START_SAFE_BROWSING";
        mm2 = new mm(string2, string2);
        string2 = "SAFE_BROWSING_WHITELIST";
        mm2 = new mm(string2, string2);
        String string3 = "SAFE_BROWSING_ALLOWLIST";
        mm2 = new mm(string2, string3);
        new mm(string3, string2);
        new mm(string3, string3);
        string2 = "SAFE_BROWSING_PRIVACY_POLICY_URL";
        mm2 = new mm(string2, string2);
        string2 = "SERVICE_WORKER_BASIC_USAGE";
        mm2 = new mm(string2, string2);
        string2 = "SERVICE_WORKER_CACHE_MODE";
        mm2 = new mm(string2, string2);
        string2 = "SERVICE_WORKER_CONTENT_ACCESS";
        mm2 = new mm(string2, string2);
        string2 = "SERVICE_WORKER_FILE_ACCESS";
        mm2 = new mm(string2, string2);
        string2 = "SERVICE_WORKER_BLOCK_NETWORK_LOADS";
        mm2 = new mm(string2, string2);
        string2 = "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST";
        mm2 = new mm(string2, string2);
        string2 = "RECEIVE_WEB_RESOURCE_ERROR";
        mm2 = new mm(string2, string2);
        string2 = "RECEIVE_HTTP_ERROR";
        mm2 = new mm(string2, string2);
        string2 = "SHOULD_OVERRIDE_WITH_REDIRECTS";
        mm2 = new mm(string2, string2);
        string2 = "SAFE_BROWSING_HIT";
        mm2 = new mm(string2, string2);
        string2 = "WEB_RESOURCE_REQUEST_IS_REDIRECT";
        mm2 = new mm(string2, string2);
        string2 = "WEB_RESOURCE_ERROR_GET_DESCRIPTION";
        mm2 = new mm(string2, string2);
        string2 = "WEB_RESOURCE_ERROR_GET_CODE";
        mm2 = new mm(string2, string2);
        string2 = "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY";
        mm2 = new mm(string2, string2);
        string2 = "SAFE_BROWSING_RESPONSE_PROCEED";
        mm2 = new mm(string2, string2);
        string2 = "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL";
        mm2 = new mm(string2, string2);
        string2 = "WEB_MESSAGE_PORT_POST_MESSAGE";
        mm2 = new mm(string2, string2);
        string2 = "WEB_MESSAGE_PORT_CLOSE";
        mm2 = new mm(string2, string2);
        string2 = "WEB_MESSAGE_ARRAY_BUFFER";
        mm2 = new mm(string2, string2);
        a = mm2;
        string2 = "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK";
        mm2 = new mm(string2, string2);
        string2 = "CREATE_WEB_MESSAGE_CHANNEL";
        mm2 = new mm(string2, string2);
        string2 = "POST_WEB_MESSAGE";
        mm2 = new mm(string2, string2);
        string2 = "WEB_MESSAGE_CALLBACK_ON_MESSAGE";
        mm2 = new mm(string2, string2);
        string2 = "GET_WEB_VIEW_CLIENT";
        mm2 = new mm(string2, string2);
        string2 = "GET_WEB_CHROME_CLIENT";
        mm2 = new mm(string2, string2);
        string2 = "GET_WEB_VIEW_RENDERER";
        mm2 = new mm(string2, string2);
        string2 = "WEB_VIEW_RENDERER_TERMINATE";
        mm2 = new mm(string2, string2);
        string2 = "TRACING_CONTROLLER_BASIC_USAGE";
        mm2 = new mm(string2, string2);
        new Db3();
        new Db3();
        string2 = "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE";
        mm2 = new mm(string2, string2);
        new CF3$a();
        new mm("PROXY_OVERRIDE", "PROXY_OVERRIDE:3");
        mm2 = new mm("MULTI_PROCESS", "MULTI_PROCESS_QUERY");
        b = mm2;
        string2 = "FORCE_DARK";
        mm2 = new mm(string2, string2);
        new mm("FORCE_DARK_STRATEGY", "FORCE_DARK_BEHAVIOR");
        string2 = "WEB_MESSAGE_LISTENER";
        mm2 = new mm(string2, string2);
        c = mm2;
        new mm("DOCUMENT_START_SCRIPT", "DOCUMENT_START_SCRIPT:1");
        string2 = "PROXY_OVERRIDE_REVERSE_BYPASS";
        mm2 = new mm(string2, string2);
        string2 = "GET_VARIATIONS_HEADER";
        mm2 = new mm(string2, string2);
        string2 = "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY";
        mm2 = new mm(string2, string2);
        string2 = "GET_COOKIE_INFO";
        mm2 = new mm(string2, string2);
        string2 = "REQUESTED_WITH_HEADER_ALLOW_LIST";
        mm2 = new mm(string2, string2);
        new mm("USER_AGENT_METADATA", "USER_AGENT_METADATA");
        new mm("MULTI_PROFILE", "MULTI_PROFILE");
        new mm("ATTRIBUTION_REGISTRATION_BEHAVIOR", "ATTRIBUTION_BEHAVIOR");
        new mm("WEBVIEW_MEDIA_INTEGRITY_API_STATUS", "WEBVIEW_INTEGRITY_API_STATUS");
        mm2 = new mm("MUTE_AUDIO", "MUTE_AUDIO");
        d = mm2;
    }
}

