/*
 * Decompiled with CFR 0.152.
 */
import java.util.HashMap;
import kotlin.jvm.functions.Function0;
import kotlin.jvm.internal.Intrinsics;

/*
 * Renamed from da3
 */
public final class da3_0 {
    public static final Object a;

    static {
        Object object;
        a = object = new Object();
    }

    public static final void a(ca3 ca32) {
        int n3 = ca32.d;
        int[] nArray = ca32.b;
        Object[] objectArray = ca32.c;
        int n4 = 0;
        for (int i3 = 0; i3 < n3; ++i3) {
            Object object = objectArray[i3];
            Object object2 = a;
            if (object == object2) continue;
            if (i3 != n4) {
                int n7;
                nArray[n4] = n7 = nArray[i3];
                objectArray[n4] = object;
                object = null;
                objectArray[i3] = null;
            }
            ++n4;
        }
        ca32.a = false;
        ca32.d = n4;
    }

    public static void b(HashMap hashMap) {
        Intrinsics.checkNotNullParameter(hashMap, "map");
        hashMap.put("url_misc_backend", "https://www.ajio.com");
        hashMap.put("url_misc_oauth_token_uaas_otp", "https://api.ajio.com/uaas/login/otp");
        hashMap.put("url_misc_oauth_token_uaas_generate_guest", "https://api.ajio.com/uaas/jwt/token/client");
        hashMap.put("url_misc_oauth_token_uaas_generate_refresh_token", "https://api.ajio.com/uaas/jwt/token/refresh");
        hashMap.put("url_misc_weblink", "https://www.ajio.com/rilfnlwebservices/v2/rilfnl/category?url=%s");
        hashMap.put("url_misc_about_us", "https://www.ajio.com/help/AboutUs?uiel=Mobile&isAppsFlag=true");
        hashMap.put("url_misc_terms_and_condition", "https://www.ajio.com/help/termsAndCondition?uiel=Mobile&isAppsFlag=true");
        hashMap.put("url_misc_contact_us", "https://www.ajio.com/contactus?uiel=Mobile&isAppsFlag=true");
        hashMap.put("url_misc_faq_returns", "https://www.ajio.com/faq-returns?uiel=Mobile&isAppsFlag=true");
        hashMap.put("url_misc_faq", "https://www.ajio.com/faq");
        hashMap.put("url_misc_cart_offer_imv", "https://www.ajio.com/_ui/mobile/common/images/offer-tag-filled.png");
        hashMap.put("url_misc_plp_offer_imv", "https://www.ajio.com/_ui/mobile/common/images/plp-off.png");
        hashMap.put("url_misc_size_guide_service", "https://www.ajio.com%s?uiel=Mobile&site=rilfnl");
        hashMap.put("url_misc_search_term", "https://www.ajio.com/%s");
        hashMap.put("url_misc_coupon_bonanza_get_coupons", "https://api.ajio.com/gamification/v1/bonanza/game/%s/email/%s/coupons");
        hashMap.put("url_misc_coupon_bonanza_purchase_coupons", "https://api.ajio.com/gamification/v1/bonanza/game/%s/email/%s/coupons/purchase");
        hashMap.put("url_misc_privacy_policy_link", "https://www.ajio.com/privacypolicy?uiel=Mobile&isAppsFlag=true");
        hashMap.put("url_misc_banner_ad_different_api", "https://cms-edge.services.ajio.com/storefront/cms/component");
        hashMap.put("url_misc_third_party_banner_ads", "https://ajio-ba.o-s.io/v2/bsda/pt");
        hashMap.put("url_login_refresh_token_ucp", "https://www.ajio.com/user-service/app/v1/tokens/refresh");
        hashMap.put("url_login_token_ucp", "https://www.ajio.com/user-service/app/v1/tokens");
        hashMap.put("url_login_account_check_uaas", "https://api.ajio.com/uaas/accountCheck");
        hashMap.put("url_login_send_otp", "https://identity.services.ajio.com/rilfnlwebservices/v2/rilfnl/login/sendOTP");
        hashMap.put("url_login_send_otp_uaas", "https://api.ajio.com/uaas/login/sendOTP");
        hashMap.put("url_login_social_login_uaas", "https://api.ajio.com/uaas/login/socialLogin");
        hashMap.put("url_login_logout_uaas", "https://api.ajio.com/uaas/users/%s/logout");
        hashMap.put("url_login_customertype", "https://api.ajio.com/uaas/v2/rilfnl/users/%s/customertype");
        hashMap.put("url_login_new_registration_uaas", "https://api.ajio.com/uaas/newAppRegisterUser");
        hashMap.put("url_login_new_registration_uaas_newflow", "https://api.ajio.com/uaas/registerUser");
        hashMap.put("url_login_login_signup_banner", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/appsignuploginbanner");
        hashMap.put("url_login_fetch_user_device_id", "https://api.ajio.com/service/am/runtime/cohort/getUserSegmentAndCohort/device/%s");
        hashMap.put("url_login_fetch_user_device_id_v2", "https://api.ajio.com/service/am/runtime/v2/cohort/getUserSegmentAndCohort/device/%s");
        hashMap.put("url_login_delete_account_api", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/deleteAccount");
        hashMap.put("url_address_update_address", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/addresses/%s/put");
        hashMap.put("url_address_address_list", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/addresses?fields=FULL");
        hashMap.put("url_address_delete_address", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/addresses/%s/delete");
        hashMap.put("url_address_check_postalcode", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/checkPostalCode/%s");
        hashMap.put("url_address_create_address", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/addresses");
        hashMap.put("url_address_set_deliveryaddress", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/carts/%s/addresses/delivery/put");
        hashMap.put("url_address_ex_return_selected_address", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/fnluser/serviceability/addresses?fields=FULL&consignmentCode=%s&addressId=%s");
        hashMap.put("url_address_update_address_to_cart", "https://api.ajio.com/service/cart/%s/address/update");
        hashMap.put("url_cart_cart_list", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/carts/%s");
        String string2 = "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/carts";
        hashMap.put("url_cart_new_cart_id", string2);
        hashMap.put("url_cart_add_to_cart", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/carts/%s/entries");
        hashMap.put("url_cart_product_size", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/products/sizeVariants/%s");
        hashMap.put("url_cart_merge_cart_id", string2);
        hashMap.put("url_cart_quickview_list", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/carts/%s/images");
        hashMap.put("url_cart_remove_coupon", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/carts/%s/vouchers/%s");
        hashMap.put("url_cart_delete_entries", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/carts/%s/entries/%s/delete");
        hashMap.put("url_cart_update_entries", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/carts/%s/entries/%s/itemupdate");
        hashMap.put("url_cart_coupon_list", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/carts/%s/sortedlistofvouchers");
        hashMap.put("url_cart_apply_coupon", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/carts/%s/vouchers");
        hashMap.put("url_cart_pick_from_store_list", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/carts/%s/storeNodes");
        hashMap.put("url_cart_cart_inventory_check", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/carts/%s/checkStock");
        hashMap.put("url_cart_product_size_auth", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/products/sizeVariants/stockCheck/%s");
        hashMap.put("url_cart_assured_gift_gamification", "https://api.ajio.com/gamification/v1/assured-gifts/game/AssuredGifts?orderValue=%s");
        hashMap.put("url_cart_bulk_delete", "https://api.ajio.com/service/cart/%s/entries/bulk/delete");
        hashMap.put("url_cart_bulk_move_wishlist", "https://api.ajio.com/wishlist/bulk/add/user/%s");
        hashMap.put("url_cart_bulk_move_wishlist_new", "https://api.ajio.com/wishlist/service/bulk/V2/add/%s");
        hashMap.put("url_cart_calculate_price_cart", "https://api.ajio.com/service/cart/%s/calculate-wallet");
        hashMap.put("url_cart_apply_priority_delivery", "https://api.ajio.com/service/cart/%s/priorityDelivery/apply");
        hashMap.put("url_edd_shipping_edd", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/carts/%s/checkServiceableCart?pincode=%s");
        hashMap.put("url_edd_product_edd", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/checkDeliveryDetails?productCode=%s&postalCode=%s&quantity=%s&isExchange=%s&isPriorityDeliveryEnable=%s");
        hashMap.put("url_payment_place_order", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/payment/%s/placeOrder");
        hashMap.put("url_payment_payment_authtoken", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/payment/getPEOAuthToken");
        hashMap.put("url_payment_cart_checkout", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/payment/getBeginCheckoutInfo");
        hashMap.put("url_payment_pay_now", "https://payment.services.ajio.com/payment-engine/api/v2/payment/pay-now");
        hashMap.put("url_payment_pay_now_json", "https://payment.services.ajio.com/payment-engine/api/v1/payment/pay-now-json");
        hashMap.put("url_payment_lp_resend_otp", "https://payment.services.ajio.com/payment-engine/api/v1/loyalty/resend-otp");
        hashMap.put("url_payment_lp_bulk_stored_card_balance_list", "https://payment.services.ajio.com/payment-engine/api/v1/loyalty/bulk/stored-card-balance-list");
        hashMap.put("url_payment_lp_balance", "https://payment.services.ajio.com/payment-engine/api/v1/loyalty/balance");
        hashMap.put("url_payment_lp_otp", "https://payment.services.ajio.com/payment-engine/api/v1/callback/loyalty/otp");
        hashMap.put("url_payment_instruments", "https://payment.services.ajio.com/payment-engine/api/v1/user/payment-instruments/all");
        hashMap.put("url_payment_transaction_abort", "https://payment.services.ajio.com/payment-engine/api/v1/payment/abort-transaction");
        hashMap.put("url_payment_upi_redirect", "https://payment.services.ajio.com/payment-engine/api/v1/payment/upi-tenant-redirect");
        string2 = "https://payment.services.ajio.com/payment-engine/api/v1/user/payment-instruments/stored";
        hashMap.put("url_payment_saved_card", string2);
        hashMap.put("url_payment_delete_instrument", string2);
        hashMap.put("url_payment_calculate_price", "https://payment.services.ajio.com/payment-engine/api/v1/service/calculate-price");
        hashMap.put("url_payment_bin_info", "https://payment.services.ajio.com/payment-engine/api/v1/service/card-information");
        hashMap.put("url_payment_transaction_status", "https://payment.services.ajio.com/payment-engine/api/v1/payment/status");
        hashMap.put("url_payment_transaction_get_status", "https://payment.services.ajio.com/payment-engine/api/v1/payment/purchase-transaction/get-status");
        hashMap.put("url_payment_generate_captcha", "https://payment.services.ajio.com/payment-engine/api/v1/fraud/captcha/generate");
        hashMap.put("url_payment_validate_captcha", "https://payment.services.ajio.com/payment-engine/api/v1/fraud/captcha/validate");
        hashMap.put("url_payment_verify_vpa", "https://payment.services.ajio.com/payment-engine/api/v1/service/vpa/validate");
        hashMap.put("url_payment_juspay_base_url", "https://payment.services.ajio.com/payment-engine/api/v1");
        hashMap.put("url_payment_fetch_wallets", "https://payment.services.ajio.com/payment-engine/api/v1/user/reliance/wallets");
        hashMap.put("url_payment_send_otp", "https://payment.services.ajio.com/payment-engine/api/v2/service/kiosk/otp/request");
        hashMap.put("url_payment_validate_otp", "https://payment.services.ajio.com/payment-engine/api/v2/service/kiosk/otp/validation");
        hashMap.put("url_payment_fetch_emi_plans", "https://payment.services.ajio.com/payment-engine/api/v1/user/payment-instruments/show-emi-plans");
        hashMap.put("url_customercare_item_status", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/selfcare/itemStatus");
        hashMap.put("url_customercare_create_ticket", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/selfcare/createticket");
        hashMap.put("url_customercare_item_status_qa", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/selfcare/itemDetails");
        hashMap.put("url_customercare_cc_faq", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/selfcare/footer");
        hashMap.put("url_customercare_cc_faq_search", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/searchService/FAQ/search");
        hashMap.put("url_customercare_createnewticket", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/selfcare/createnewticket");
        hashMap.put("url_customercare_ticket_list", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/selfcare/ticketlist");
        hashMap.put("url_customercare_complaint_details", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/selfcare/complaintCardDetails");
        hashMap.put("url_customercare_complaint_attach", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/selfcare/uploadattachment");
        hashMap.put("url_customercare_complaint_attach_new", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/selfcare/uploadNewAttachmentData");
        hashMap.put("url_customercare_callmeback_detail", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/callbackservice/requestCall");
        hashMap.put("url_customercare_submit_callmeback", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/callbackservice/submitCall");
        hashMap.put("url_customercare_initiate_chat", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/selfcare/initiateChat");
        hashMap.put("url_closet_product_with_code", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/products/%s?%s");
        hashMap.put("url_closet_wishlist_view_all", "https://api.ajio.com/wishlist/rilfnl/v2/viewall/user/%s");
        hashMap.put("url_closet_wishlist_add", "https://api.ajio.com/wishlist/rilfnl/fnladdtowishlist/user/%s");
        hashMap.put("url_closet_wishlist_remove", "https://api.ajio.com/wishlist/rilfnl/fnlremovefromwishlist/user/%s?%s");
        hashMap.put("url_closet_option_codes", "https://api.ajio.com/wishlist/v2/optionCodes/%s");
        hashMap.put("url_closet_wishlist_microcart", "https://api.ajio.com/service/cart/%s/microcart");
        hashMap.put("url_closet_wishlist_size_chart", "https://www.ajio.com/sizechart/productLevelSizeGuide");
        hashMap.put("url_order_old_orders_list", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/orders?fields=BASIC&currentPage=%s&pageSize=10");
        hashMap.put("url_order_orders_list", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/ordersItem?active=%s&currentPage=%s&pageSize=10");
        hashMap.put("url_order_feedback_url", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/orderConfirmation/feedback");
        hashMap.put("url_order_order_details", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/orders/%s?fields=FULL");
        hashMap.put("url_order_new_return_order_item", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/returns/returnorderitem?orderCode=%s&consignmentCode=%s&adId=%s&channelType=%s");
        hashMap.put("url_order_initiate_return", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/returns/initiate-return");
        hashMap.put("url_order_invoice_check", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/returns/invoiceCheck?orderCode=%s&consignmentCode=%s&invoiceNum=%s");
        hashMap.put("url_order_cancel_order", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/cancelorderitem/%s/%s");
        hashMap.put("url_order_new_cancel_order", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/cancelorderitemviacom/%s/%s");
        hashMap.put("url_order_new_cancel_order_details", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/cancelorderitemviacom/details/%s/%s");
        hashMap.put("url_order_cancel_reasons", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/cancelorderitemreasons");
        hashMap.put("url_order_new_order_details", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/orderDetails/%s?fields=FULL");
        hashMap.put("url_order_download_invoice", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/orders/%s/%s/invoicedownload");
        hashMap.put("url_order_drop_at_store_list", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/returns/dropAtStoreNodes?pincode=%s");
        hashMap.put("url_order_loyalty_point_status", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/payment/loyaltyPointStatus/%s");
        hashMap.put("url_order_return_upload_image", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/returns/uploadReturnimage");
        hashMap.put("url_order_imps_request", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/initiateImpsRefundRequest");
        hashMap.put("url_order_initiate_return_update", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/returns/initiate-returnUpdate");
        hashMap.put("url_order_ifsc_check", "https://payment.services.ajio.com/payment-engine/api/v1/bank/details/%s");
        hashMap.put("url_homepage_home_content", "https://cms-edge.services.ajio.com/rilfnlwebservices/v2/rilfnl/payloadReductionLandingPage?pageId=%s&uiel=Mobile");
        hashMap.put("url_homepage_home_cms", "https://cms-edge.services.ajio.com/storefront/cms/page");
        hashMap.put("url_homepage_newsletter_subscribe", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/subscribeNewsletter");
        hashMap.put("url_homepage_nav_menu", "https://cms-edge.services.ajio.com/rilfnlwebservices/v2/rilfnl/navigation/navnodes");
        hashMap.put("url_homepage_jio_engage", "https://api.ajio.com/gamification/v1/user/%s/token");
        hashMap.put("url_homepage_cms_nav_menu", "https://cms-edge.services.ajio.com/storefront/cms/navigation");
        hashMap.put("url_homepage_coupon_promotion", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/couponbonanza?fields=FULL");
        hashMap.put("url_homepage_buy_coupon_promotion", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/eosscoupons/");
        hashMap.put("url_homepage_sis_store_cms_meta_data", "https://cms-edge.services.ajio.com/storefront/cms/stores?tenantId=AJIO&apiVersion=V2");
        hashMap.put("url_homepage_sis_store_cms_meta_data_v2", "https://cms-edge.services.ajio.com/storefront/cms/stores?tenantId=AJIO&apiVersion=v2");
        hashMap.put("url_homepage_sis_store_cms_meta_data_v3", "https://cms-edge.services.ajio.com/storefront/cms/stores?tenantId=AJIO&apiVersion=v3");
        hashMap.put("url_homepage_sis_store_info", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/storemetadata?storeId=%s");
        hashMap.put("url_homepage_sis_nav_menu", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/storemetadata");
        hashMap.put("url_homepage_geo_loc", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/geoloc?latitude=%s&longitude=%s");
        hashMap.put("url_homepage_brands_cat", "https://cms-edge.services.ajio.com/rilfnlwebservices/v2/rilfnl/catalogs/%1s/Online/categories/%2s");
        hashMap.put("url_homepage_luxe_categories", "https://cms-edge.services.ajio.com/rilfnlwebservices/v2/rilfnl/newcategoryselection?pageId=firstpageluxemobileapp&uiel=Mobile");
        hashMap.put("url_homepage_products_list_detail", "https://search-edge.services.ajio.com/rilfnlwebservices/v2/rilfnl/searchService/getProductDetails?productCodes=%1s&urgencyDriverEnabled=%2s&includeOutOfStock=%3s");
        string2 = "https://mercury.jio.com/delivery/mapi.php";
        hashMap.put("url_homepage_banner_ads_url", string2);
        hashMap.put("url_homepage_home_curated_widget", "https://search-edge.services.ajio.com/rilfnlwebservices/rilfnl/products/curated/widget/list");
        hashMap.put("url_homepage_fetch_pincode", "https://api.ajio.com/storefront/cms/locale");
        hashMap.put("url_pdp_product_detail", "https://pdpaggregator-edge.services.ajio.com/aggregator/pdp/%s");
        hashMap.put("url_pdp_similar_list", "https://search-edge.services.ajio.com/rilfnlwebservices/v2/rilfnl/recommend/%s");
        hashMap.put("url_pdp_similar_list_2", "https://search-edge.services.ajio.com/rilfnlwebservices/v3/rilfnl/recommend");
        hashMap.put("url_pdp_recently_viewed_list", "https://search-edge.services.ajio.com/rilfnlwebservices/v2/rilfnl/recentlyViewed?productCodes=%s&fields=FULL&format=json");
        hashMap.put("url_pdp_size_guide_data", "https://www.ajio.com/sizeguide-v2/app/%s/%s/%s?productCode=%s&gender=%s&subCategory=%s&seasonCode=%s&vendorCode=%s&fittingType=%s&styleType=%s");
        hashMap.put("url_pdp_uep_get_view", "https://uat.ajio.ril.com/sizechart/recommendUserSize");
        hashMap.put("url_pdp_uep_post_view", "https://www.ajio.com/uep/eventcapture/webservices/v1/%s/event/PDPViewEvent");
        hashMap.put("fraud_engine_serviceability", "https://pdpaggregator.services.ajio.com/aggregator/pdp/serviceability");
        hashMap.put("size_recommendation_v2", "https://api.ajio.com/sizechart/recommendUserSize");
        hashMap.put("url_plp_category_product_v3", "https://search-edge.services.ajio.com/rilfnlwebservices/v3/rilfnl/products/category/%s");
        hashMap.put("url_plp_category_product_v4", "https://search-edge.services.ajio.com/rilfnlwebservices/v4/rilfnl/products/category/%s");
        hashMap.put("url_plp_category_product_v5", "https://search-edge.services.ajio.com/rilfnlwebservices/v5/rilfnl/products/category/%s");
        hashMap.put("url_plp_search_product_v3", "https://search-edge.services.ajio.com/rilfnlwebservices/v3/rilfnl/products/search");
        hashMap.put("url_plp_search_product_v4", "https://search-edge.services.ajio.com/rilfnlwebservices/v4/rilfnl/products/search");
        hashMap.put("url_plp_search_product_v5", "https://search-edge.services.ajio.com/rilfnlwebservices/v5/rilfnl/products/search");
        hashMap.put("url_plp_search_suggestions", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/products/suggestions/?term=%s&max=10");
        hashMap.put("url_plp_new_user_banner", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/plpTopBannerURL");
        hashMap.put("url_plp_get_image_upload_url", "https://api.ajio.com/searchservices/api/v1/cloud_storage/object/upload/url");
        hashMap.put("`url_plp_image_search_url`", "https://api.ajio.com/searchservices/api/v1/products/search_by_image");
        hashMap.put("url_plp_image_search_url_v2", "https://api.ajio.com/searchservices/api/v2/products/search_by_image");
        hashMap.put("url_plp_more_image_search_url", "https://api.ajio.com/searchservices/api/v1/products");
        hashMap.put("url_plp_more_image_search_url_v2", "https://api.ajio.com/searchservices/api/v2/products");
        hashMap.put("url_plp_banner_ads_url", string2);
        hashMap.put("url_plp_widget_product", "https://search-edge.services.ajio.com/rilfnlwebservices/rilfnl/products/widgets/%s");
        hashMap.put("url_plp_widget_product_v2", "https://search-edge.services.ajio.com/rilfnlwebservices/v2/rilfnl/products/widgets/%s");
        hashMap.put("url_my_account_profile_update_uaas", "https://api.ajio.com/uaas/users/updateUser/details");
        hashMap.put("url_my_account_get_profile_uaas", "https://api.ajio.com/uaas/users/current");
        hashMap.put("url_my_account_reset_password", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/forgottenpasswordtokens/change/password");
        hashMap.put("url_my_account_account_nav_bar", "https://api.ajio.com/storefront/cms/page/static?content=navigation&name=myaccount&channel=android");
        hashMap.put("url_my_account_access_profile_otp_request_uaas", "https://api.ajio.com/uaas/users/editaddress/generateOTP");
        hashMap.put("url_my_account_access_profile_otp_verify_uaas", "https://api.ajio.com/uaas/users/editaddress/validateOTP");
        hashMap.put("url_my_account_verify_ril_email_otp_request_uaas", "https://api.ajio.com/uaas/users/verifyEmail/generateOTP");
        hashMap.put("url_my_account_verify_ril_profile_otp_uaas", "https://api.ajio.com/uaas/users/verifyEmail/validateOTP");
        hashMap.put("url_my_account_gamezop_rewards", "https://www.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/game/gamezop/rewards");
        hashMap.put("url_my_account_cancel_request", "https://api.ajio.com/uaas/users/updateMobileNumber/cancel");
        hashMap.put("url_my_account_change_mobile_number_request", "https://api.ajio.com/uaas/users/update/mobileNumber/request");
        hashMap.put("url_my_account_pancard_verification", "https://api.ajio.com/uaas/users/verifyTaxPayerId");
        hashMap.put("url_credit_credit_detail", "https://www.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/creditDetails");
        hashMap.put("url_ajio_cash_cash_bonus", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/ajiocash/walletbalance");
        hashMap.put("url_ajio_cash_point_history", "https://www.ajio.com/rilfnlwebservices/v2/rilfnl/users/%1s/ajiocash/txnhistory");
        hashMap.put("url_ajio_cash_earn_point", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/payment/%s/acEligibleEarn");
        hashMap.put("url_ajio_cash_credit_detail_acash", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/creditDetails?startSerialNo=%s");
        hashMap.put("url_ajio_cash_txn_history", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/users/%s/ajiocash/txnhistoryV2?moneyType=%s&fields=%s&nextPageOffset=%s&transactionLimit=%s");
        hashMap.put("url_ajio_cash_txn_history_v3", "https://payment.services.ajio.com/ajiocash/rilfnl/users/%s/v3/txnHistory?nextRcsPageOffset=%s&nextNtPageOffset=%s&nextLoad=%s&fields=%s&transactionLimit=%s");
        hashMap.put("url_ajio_cash_bank_transfer_status", "https://payment.services.ajio.com/payment-engine/api/v1/refund/bank-transfer-status");
        hashMap.put("url_coupon_offer_coupon_list", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/allOffersCoupon?format=json");
        hashMap.put("url_coupon_offer_bank_list", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/allActiveBankOffer?uiel=APP&format=json");
        hashMap.put("url_referral_referral_faq", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/referral/questions?pageLabel=%s");
        hashMap.put("url_referral_referral_wallet_balance", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/referral/referralWalletbalance?userId=%s");
        hashMap.put("url_referral_referral_configs", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/referral/referralConfigs");
        hashMap.put("url_giftcard_redeem", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/giftCard/redeem");
        hashMap.put("url_giftcard_check_balance", "https://api.ajio.com/rilfnlwebservices/v2/rilfnl/giftCard/getBalance");
        hashMap.put("url_ratings_submit_sub_ratings", "https://api.ajio.com/cem/v1/sub-rating/response");
        hashMap.put("url_ratings_set_ratings_v1", "https://api.ajio.com/cem/v1/ratings/user/%s/all");
        string2 = "https://api.ajio.com/cem/v1/reviews/user/%s/all";
        hashMap.put("url_ratings_set_reviews", string2);
        hashMap.put("url_ratings_delete_review_images", string2);
        hashMap.put("url_ratings_unrated_items_v1", "https://api.ajio.com/cem/v1/unratedItems/user/%s/all");
        hashMap.put("url_reviews_text_review_list", "https://api.ajio.com/cem/v1/reviews");
        hashMap.put("url_reviews_review_like", "https://api.ajio.com/cem/v1/reviews/like/%s/all");
        hashMap.put("url_ajiogram_explore_brands", "https://ajiogram-edge.services.ajio.com/common-aggregator/users/%s/brands/explore");
        hashMap.put("url_ajiogram_feed", "https://ajiogram-edge.services.ajio.com/feed-engine/v1/feed");
        hashMap.put("url_ajiogram_feed_pagination", "https://ajiogram-edge.services.ajio.com/feed-engine/v2/feed");
        hashMap.put("url_ajiogram_stories", "https://ajiogram-edge.services.ajio.com/feed-engine/v1/getstories");
        hashMap.put("url_ajiogram_brand_page", "https://ajiogram-edge.services.ajio.com/common-aggregator/users/%s/brand/%s");
        hashMap.put("url_ajiogram_brands_list", "https://search-edge.services.ajio.com/rilfnlwebservices/v1/rilfnl/brands");
        hashMap.put("url_ajiogram_seen_api", "https://ajiogram.ajio.com/ses/v1/content/seen/%s");
        hashMap.put("url_ajiogram_ses_action_api", "https://ajiogram.ajio.com/ses/v1/%s/action/%s");
        hashMap.put("url_ajiogram_recent_post", "https://ajiogram-edge.services.ajio.com/common-aggregator/users/%s/brand/%s/posts");
        hashMap.put("url_ajiogram_share_content", "https://ajiogram.ajio.com/ses/v1/content/share/%s");
        hashMap.put("url_ajiogram_get_post_details", "https://ajiogram-edge.services.ajio.com/feed-engine/v1/getPost/%s");
    }

    public static final io0_2 c(ea1_2 ea1_22, uf_1 uf_12) {
        Intrinsics.checkNotNullParameter(ea1_22, "<this>");
        Object object = "content";
        Intrinsics.checkNotNullParameter(uf_12, (String)object);
        da1_2 da1_22 = ea1_22.a;
        l41_0 l41_02 = ea1_22.d().getHeaders();
        Intrinsics.checkNotNullParameter(da1_22, "client");
        Intrinsics.checkNotNullParameter(uf_12, (String)object);
        Intrinsics.checkNotNullParameter(ea1_22, "originCall");
        Intrinsics.checkNotNullParameter(l41_02, "responseHeaders");
        object = new ia_2(uf_12, 1);
        io0_2 io0_22 = new io0_2(da1_22, (Function0)object, ea1_22, l41_02);
        return io0_22;
    }
}

