/*
 * Decompiled with CFR 0.152.
 */
/*
 * Renamed from Je0
 */
public final class je0_1 {
    public static final String a;
    public static final String b;
    public static final String c;
    public static final String d;
    public static final String e;
    public static final String f;
    public static final String g;
    public static final String h;
    public static final String i;
    public static final String j;
    public static final String k;
    public static final String l;
    public static final String m;
    public static final String n;
    public static final String o;
    public static final String p;
    public static final String q;
    public static final String r;
    public static final String s;
    public static final String t;

    static {
        Object object = "\n    CREATE TABLE ";
        StringBuilder stringBuilder = new StringBuilder((String)object);
        Object object2 = ci3_1.EVENTS;
        String string2 = object2.getTableName();
        stringBuilder.append(string2);
        string2 = " (\n        _id INTEGER PRIMARY KEY AUTOINCREMENT,\n        data STRING NOT NULL,\n        created_at INTEGER NOT NULL\n    );\n";
        stringBuilder.append(string2);
        a = stringBuilder.toString();
        stringBuilder = new StringBuilder((String)object);
        Object object3 = ci3_1.USER_EVENT_LOGS_TABLE.getTableName();
        stringBuilder.append((String)object3);
        stringBuilder.append(" (\n        deviceID STRING NOT NULL,\n        eventName STRING NOT NULL,\n        normalizedEventName STRING NOT NULL,\n        firstTs INTEGER NOT NULL,\n        lastTs INTEGER NOT NULL,\n        count INTEGER NOT NULL,\n        PRIMARY KEY (deviceID, normalizedEventName)\n    );\n");
        b = stringBuilder.toString();
        stringBuilder = new StringBuilder((String)object);
        object3 = ci3_1.PROFILE_EVENTS;
        Object object4 = ((ci3_1)((Object)object3)).getTableName();
        stringBuilder.append((String)object4);
        stringBuilder.append(string2);
        c = stringBuilder.toString();
        stringBuilder = new StringBuilder(" \n    CREATE TABLE ");
        object4 = ci3_1.INBOX_MESSAGES;
        String string3 = ((ci3_1)((Object)object4)).getTableName();
        stringBuilder.append(string3);
        stringBuilder.append(" (\n        _id STRING NOT NULL,\n        data TEXT NOT NULL,\n        wzrkParams TEXT NOT NULL,\n        campaignId STRING NOT NULL,\n        tags TEXT NOT NULL,\n        isRead INTEGER NOT NULL DEFAULT 0,\n        expires INTEGER NOT NULL,\n        created_at INTEGER NOT NULL,\n        messageUser STRING NOT NULL\n    );\n");
        d = stringBuilder.toString();
        stringBuilder = new StringBuilder("\n    CREATE UNIQUE INDEX IF NOT EXISTS userid_id_idx ON ");
        string3 = ((ci3_1)((Object)object4)).getTableName();
        stringBuilder.append(string3);
        stringBuilder.append(" (\n        messageUser,\n        _id\n    );\n");
        e = stringBuilder.toString();
        string3 = "\n    CREATE INDEX IF NOT EXISTS time_idx ON ";
        stringBuilder = new StringBuilder(string3);
        object2 = object2.getTableName();
        stringBuilder.append((String)object2);
        object2 = " (created_at);\n";
        stringBuilder.append((String)object2);
        f = stringBuilder.toString();
        stringBuilder = new StringBuilder(string3);
        object3 = ((ci3_1)((Object)object3)).getTableName();
        stringBuilder.append((String)object3);
        stringBuilder.append(" ( created_at);\n");
        g = stringBuilder.toString();
        stringBuilder = new StringBuilder((String)object);
        object3 = ci3_1.PUSH_NOTIFICATIONS;
        Object object5 = ((ci3_1)((Object)object3)).getTableName();
        stringBuilder.append((String)object5);
        stringBuilder.append(" (\n        _id INTEGER PRIMARY KEY AUTOINCREMENT,\n        data STRING NOT NULL,\n        created_at INTEGER NOT NULL,\n        isRead INTEGER NOT NULL\n    );\n");
        h = stringBuilder.toString();
        stringBuilder = new StringBuilder(string3);
        object3 = ((ci3_1)((Object)object3)).getTableName();
        stringBuilder.append((String)object3);
        stringBuilder.append((String)object2);
        i = stringBuilder.toString();
        stringBuilder = new StringBuilder((String)object);
        object3 = ci3_1.UNINSTALL_TS;
        object5 = ((ci3_1)((Object)object3)).getTableName();
        stringBuilder.append((String)object5);
        stringBuilder.append(" (\n        _id INTEGER PRIMARY KEY AUTOINCREMENT,\n        created_at INTEGER NOT NULL\n    );\n");
        j = stringBuilder.toString();
        stringBuilder = new StringBuilder(string3);
        object5 = ((ci3_1)((Object)object3)).getTableName();
        stringBuilder.append((String)object5);
        stringBuilder.append((String)object2);
        k = stringBuilder.toString();
        stringBuilder = new StringBuilder((String)object);
        object5 = ci3_1.PUSH_NOTIFICATION_VIEWED;
        String string4 = ((ci3_1)((Object)object5)).getTableName();
        stringBuilder.append(string4);
        stringBuilder.append(string2);
        l = stringBuilder.toString();
        stringBuilder = new StringBuilder(string3);
        string2 = ((ci3_1)((Object)object5)).getTableName();
        stringBuilder.append(string2);
        stringBuilder.append((String)object2);
        m = stringBuilder.toString();
        object2 = "DROP TABLE IF EXISTS ";
        stringBuilder = new StringBuilder((String)object2);
        string2 = ((ci3_1)((Object)object3)).getTableName();
        stringBuilder.append(string2);
        n = stringBuilder.toString();
        stringBuilder = new StringBuilder((String)object2);
        string2 = ((ci3_1)((Object)object4)).getTableName();
        stringBuilder.append(string2);
        o = stringBuilder.toString();
        stringBuilder = new StringBuilder((String)object2);
        object2 = ((ci3_1)((Object)object5)).getTableName();
        stringBuilder.append((String)object2);
        p = stringBuilder.toString();
        stringBuilder = new StringBuilder((String)object);
        object = ci3_1.USER_PROFILES;
        object2 = ((ci3_1)((Object)object)).getTableName();
        stringBuilder.append((String)object2);
        stringBuilder.append(" (\n        deviceID STRING NOT NULL,\n        _id STRING NOT NULL,\n        data STRING NOT NULL,\n        PRIMARY KEY (_id, deviceID)\n    );\n");
        q = stringBuilder.toString();
        stringBuilder = new StringBuilder("\n    CREATE TABLE temp_");
        object2 = ((ci3_1)((Object)object)).getTableName();
        stringBuilder.append((String)object2);
        stringBuilder.append(" (\n        _id STRING NOT NULL,\n        deviceID STRING NOT NULL,\n        data STRING NOT NULL,\n        PRIMARY KEY (_id, deviceID)\n    );\n");
        r = stringBuilder.toString();
        stringBuilder = new StringBuilder("\n    DROP TABLE ");
        object2 = ((ci3_1)((Object)object)).getTableName();
        stringBuilder.append((String)object2);
        object2 = ";\n";
        stringBuilder.append((String)object2);
        s = stringBuilder.toString();
        stringBuilder = new StringBuilder("\n    ALTER TABLE temp_");
        string2 = ((ci3_1)((Object)object)).getTableName();
        stringBuilder.append(string2);
        stringBuilder.append(" RENAME TO ");
        object = ((ci3_1)((Object)object)).getTableName();
        stringBuilder.append((String)object);
        stringBuilder.append((String)object2);
        t = stringBuilder.toString();
    }
}

