/*
 * Decompiled with CFR 0.152.
 */
package com.google.android.play.core.assetpacks;

import com.google.android.play.core.assetpacks.AssetPackExtractionService;
import com.google.android.play.core.assetpacks.AssetPackManager;
import com.google.android.play.core.assetpacks.ExtractionWorker;
import com.google.android.play.core.assetpacks.a;
import com.google.android.play.core.assetpacks.ay;
import com.google.android.play.core.assetpacks.b;
import com.google.android.play.core.assetpacks.bd;
import com.google.android.play.core.assetpacks.bi;
import com.google.android.play.core.assetpacks.bn;
import com.google.android.play.core.assetpacks.cj;
import com.google.android.play.core.assetpacks.cn;
import com.google.android.play.core.assetpacks.cq;
import com.google.android.play.core.assetpacks.ct;
import com.google.android.play.core.assetpacks.cv;
import com.google.android.play.core.assetpacks.cx;
import com.google.android.play.core.assetpacks.cy;
import com.google.android.play.core.assetpacks.db;
import com.google.android.play.core.assetpacks.de;
import com.google.android.play.core.assetpacks.du;
import com.google.android.play.core.assetpacks.dx;
import com.google.android.play.core.assetpacks.eq;
import com.google.android.play.core.assetpacks.es;
import com.google.android.play.core.assetpacks.eu;
import com.google.android.play.core.assetpacks.internal.ae;
import com.google.android.play.core.assetpacks.internal.ap;
import com.google.android.play.core.assetpacks.internal.aq;
import com.google.android.play.core.assetpacks.internal.as;
import com.google.android.play.core.assetpacks.internal.aw;
import com.google.android.play.core.assetpacks.m;
import com.google.android.play.core.assetpacks.p;
import com.google.android.play.core.assetpacks.q;
import com.google.android.play.core.assetpacks.s;
import com.google.android.play.core.assetpacks.t;
import com.google.android.play.core.assetpacks.u;
import com.google.android.play.core.assetpacks.v;
import com.google.android.play.core.assetpacks.w;
import com.google.android.play.core.assetpacks.y;

final class cl
implements a {
    private final as A;
    private final as B;
    private final as C;
    private final as D;
    private final as E;
    private final as F;
    private final as G;
    private final as a;
    private final as b;
    private final as c;
    private final as d;
    private final as e;
    private final as f;
    private final as g;
    private final as h;
    private final as i;
    private final as j;
    private final as k;
    private final as l;
    private final as m;
    private final as n;
    private final as o;
    private final as p;
    private final as q;
    private final as r;
    private final as s;
    private final as t;
    private final as u;
    private final as v;
    private final as w;
    private final as x;
    private final as y;
    private final as z;

    public /* synthetic */ cl(p object, cn object2) {
        Object object3;
        as as2;
        Object object4 = object;
        as as4 = new u((p)object);
        this.a = as4;
        object4 = new eu(as4);
        this.b = as2 = aq.b((as)object4);
        object4 = new bn(as4, as2);
        Object object5 = aq.b((as)object4);
        this.c = object5;
        Object object6 = aq.b(de.a());
        this.d = object6;
        object4 = new es((aw)object5, as2);
        Object object7 = aq.b((as)object4);
        this.e = object7;
        object4 = new ay(as4, (aw)object6, (aw)object7);
        Object object8 = aq.b((as)object4);
        this.f = object8;
        object4 = new v(as4);
        Object object9 = aq.b((as)object4);
        this.g = object9;
        this.h = object4 = new ap();
        Object object10 = aq.b(com.google.android.play.core.assetpacks.q.a());
        this.i = object10;
        Object object11 = new du((aw)object5, (aw)object4, (aw)object6, (aw)object10);
        Object object12 = aq.b((as)object11);
        this.j = object12;
        Object object13 = aq.b(bi.a());
        this.k = object13;
        object11 = object3;
        Object object14 = object5;
        Object object15 = object4;
        Object object16 = object13;
        as as5 = object13;
        object13 = object6;
        object = object12;
        object12 = object7;
        object3 = new cq((aw)object5, (aw)object4, (aw)object16, (aw)object6, (aw)object7);
        object12 = aq.b((as)object3);
        this.l = object12;
        super((aw)object5);
        object13 = aq.b((as)object11);
        this.m = object13;
        super((aw)object5);
        object16 = aq.b((as)object11);
        this.n = object16;
        object11 = object3;
        as as6 = object16;
        object16 = object;
        Object object17 = object13;
        object13 = object10;
        Object object18 = object12;
        object12 = object6;
        as as7 = object10;
        object10 = object7;
        super((aw)object5, (aw)object4, (aw)object, (aw)object13, (aw)object6, (aw)object7);
        object10 = aq.b((as)object3);
        this.o = object10;
        super((aw)object5, (aw)object4);
        object12 = aq.b((as)object11);
        this.p = object12;
        object11 = object3;
        Object object19 = object12;
        object12 = object6;
        super((aw)object5, (aw)object4, (aw)object, (aw)object13, (aw)object6);
        object11 = aq.b((as)object3);
        this.q = object11;
        super((aw)object4);
        object14 = aq.b((as)object14);
        this.r = object14;
        object12 = object;
        object15 = new dx((aw)object, (aw)object5, (aw)object14);
        object14 = aq.b((as)object15);
        this.s = object14;
        object3 = object15;
        Object object20 = object;
        Object object21 = object4;
        Object object22 = object11;
        as as8 = object14;
        object15 = new db((aw)object, (aw)object4, (aw)object18, (aw)object17, as6, (aw)object10, (aw)object19, (aw)object11, (aw)object14);
        object10 = aq.b((as)object15);
        this.t = object10;
        object13 = aq.b(cj.a());
        this.u = object13;
        this.v = object16 = aq.b(com.google.android.play.core.assetpacks.w.a());
        object15 = object4;
        object4 = object3;
        object11 = as4;
        object14 = object;
        object = object15;
        object15 = object10;
        object22 = object16;
        object16 = object21;
        as8 = object13;
        object13 = object6;
        object2 = object12;
        object12 = as8;
        as as9 = object10;
        object10 = as7;
        object20 = object9;
        object9 = object22;
        object21 = object5;
        object5 = object8;
        object8 = object7;
        object3 = new bd(as4, (aw)object14, (aw)object15, (aw)object, (aw)object6, as8, as7, (aw)object22, (aw)object7);
        this.w = object9 = aq.b((as)object3);
        object4 = object8;
        object11 = object20;
        object14 = object9;
        object15 = object6;
        object16 = as4;
        object13 = as2;
        object12 = as7;
        object10 = object7;
        super((aw)object20, (aw)object9, (aw)object6, as4, as2, as7, (aw)object7);
        this.x = object4 = aq.b((as)object8);
        object11 = new t(as4, (aw)object5, (aw)object4);
        object4 = aq.b((as)object11);
        object10 = object;
        ap.b((as)object, (as)object4);
        object4 = new ae(as4);
        this.y = object4 = aq.b((as)object4);
        object12 = object7;
        object7 = object11;
        object8 = object6;
        object6 = object21;
        object14 = object21;
        object5 = object;
        object3 = object9;
        object20 = as5;
        object21 = object4;
        object18 = object2;
        object17 = object15;
        as6 = as8;
        object19 = object12;
        object11 = new m((aw)object6, (aw)object, (aw)object9, as5, (aw)object4, (aw)object2, (aw)object15, as8, as7, (aw)object12);
        this.z = object15 = aq.b((as)object11);
        object4 = new s((aw)object15, as4);
        this.A = object4 = aq.b((as)object4);
        object4 = new ct(as4);
        this.B = object16 = aq.b((as)object4);
        object4 = new eq(as4);
        this.C = object9 = aq.b((as)object4);
        object4 = as2;
        object11 = as4;
        object13 = object9;
        super(as4, (aw)object6, (aw)object15, (aw)object16, (aw)object9);
        this.D = object4 = aq.b(as2);
        object14 = object2;
        object11 = as9;
        object4 = new cy((aw)object2, as9, (aw)object9);
        this.E = object4 = aq.b((as)object4);
        object4 = new y(as4);
        this.F = object4 = aq.b((as)object4);
        object11 = as4;
        object15 = object8;
        object16 = object12;
        object13 = as8;
        object12 = object4;
        object9 = as5;
        object8 = object22;
        super((aw)object2, (aw)object17, (aw)object19, as8, (aw)object4, (aw)object, as5, (aw)object22);
        this.G = object4 = aq.b(as4);
    }

    public final AssetPackManager a() {
        return (AssetPackManager)this.A.a();
    }

    public final cv b() {
        return (cv)this.G.a();
    }

    public final void c(AssetPackExtractionService assetPackExtractionService) {
        b b2;
        assetPackExtractionService.a = b2 = (b)this.D.a();
    }

    public final void d(ExtractionWorker extractionWorker) {
        cx cx2;
        extractionWorker.a = cx2 = (cx)this.E.a();
    }
}

