/*
 * Decompiled with CFR 0.152.
 */
package com.google.android.gms.internal.clearcut;

import com.google.android.gms.internal.clearcut.zzcc;
import com.google.android.gms.internal.clearcut.zzcd;
import com.google.android.gms.internal.clearcut.zzcq;
import java.lang.reflect.Type;

public final class zzcb
extends Enum {
    private static final /* enum */ zzcb zzgy;
    private static final /* enum */ zzcb zzgz;
    private static final /* enum */ zzcb zzha;
    private static final /* enum */ zzcb zzhb;
    private static final /* enum */ zzcb zzhc;
    private static final /* enum */ zzcb zzhd;
    private static final /* enum */ zzcb zzhe;
    private static final /* enum */ zzcb zzhf;
    private static final /* enum */ zzcb zzhg;
    public static final /* enum */ zzcb zzhh;
    private static final /* enum */ zzcb zzhi;
    private static final /* enum */ zzcb zzhj;
    public static final /* enum */ zzcb zzhk;
    private static final /* enum */ zzcb zzhl;
    private static final /* enum */ zzcb zzhm;
    private static final /* enum */ zzcb zzhn;
    private static final /* enum */ zzcb zzho;
    public static final /* enum */ zzcb zzhp;
    public static final /* enum */ zzcb zzhq;
    private static final /* enum */ zzcb zzhr;
    private static final /* enum */ zzcb zzhs;
    private static final /* enum */ zzcb zzht;
    private static final /* enum */ zzcb zzhu;
    private static final /* enum */ zzcb zzhv;
    private static final /* enum */ zzcb zzhw;
    private static final /* enum */ zzcb zzhx;
    private static final /* enum */ zzcb zzhy;
    public static final /* enum */ zzcb zzhz;
    private static final /* enum */ zzcb zzia;
    private static final /* enum */ zzcb zzib;
    public static final /* enum */ zzcb zzic;
    private static final /* enum */ zzcb zzid;
    private static final /* enum */ zzcb zzie;
    private static final /* enum */ zzcb zzif;
    private static final /* enum */ zzcb zzig;
    public static final /* enum */ zzcb zzih;
    private static final /* enum */ zzcb zzii;
    private static final /* enum */ zzcb zzij;
    private static final /* enum */ zzcb zzik;
    private static final /* enum */ zzcb zzil;
    private static final /* enum */ zzcb zzim;
    private static final /* enum */ zzcb zzin;
    private static final /* enum */ zzcb zzio;
    private static final /* enum */ zzcb zzip;
    public static final /* enum */ zzcb zziq;
    private static final /* enum */ zzcb zzir;
    private static final /* enum */ zzcb zzis;
    private static final /* enum */ zzcb zzit;
    public static final /* enum */ zzcb zziu;
    public static final /* enum */ zzcb zziv;
    public static final /* enum */ zzcb zziw;
    private static final zzcb[] zzjb;
    private static final Type[] zzjc;
    private static final /* synthetic */ zzcb[] zzjd;
    private final int id;
    private final zzcq zzix;
    private final zzcd zziy;
    private final Class zziz;
    private final boolean zzja;

    static {
        zzcb zzcb2;
        zzcb zzcb3;
        zzcb zzcb4;
        zzcb zzcb5;
        zzcb zzcb6;
        zzcb zzcb7;
        zzcb zzcb8;
        zzcb zzcb9;
        zzcb zzcb10;
        zzcb zzcb11;
        zzcb zzcb12;
        zzcb zzcb13;
        zzcb zzcb14;
        zzcb zzcb15;
        zzcb zzcb16;
        zzcb zzcb17;
        zzcb zzcb18;
        zzcb zzcb19;
        zzcb zzcb20;
        zzcb zzcb21;
        zzcb zzcb22;
        zzcb zzcb23;
        zzcb zzcb24;
        zzcb zzcb25;
        zzcb zzcb26;
        zzcb zzcb27;
        zzcb zzcb28;
        zzcb zzcb29;
        zzcb zzcb30;
        zzcb zzcb31;
        zzcb zzcb32;
        zzcb zzcb33;
        zzcb zzcb34;
        zzcb zzcb35;
        zzcb zzcb36;
        zzcb zzcb37;
        zzcb zzcb38;
        zzcb zzcb39;
        zzcb zzcb40;
        zzcb zzcb41;
        zzcb zzcb42;
        Enum enum_ = zzcd.zzjg;
        Enum enum_2 = zzcq.zzlb;
        zzcb[] zzcbArray = zzcb42;
        Enum enum_3 = enum_;
        zzcb[] zzcbArray2 = enum_2;
        zzgy = zzcb42 = new zzcb("DOUBLE", 0, 0, (zzcd)enum_, (zzcq)enum_2);
        Enum enum_4 = zzcq.zzla;
        zzcbArray = zzcb41;
        zzcbArray2 = enum_4;
        zzgz = zzcb41 = new zzcb("FLOAT", 1, 1, (zzcd)enum_, (zzcq)enum_4);
        Enum enum_5 = zzcq.zzkz;
        zzcbArray = zzcb40;
        zzcbArray2 = enum_5;
        zzha = zzcb40 = new zzcb("INT64", 2, 2, (zzcd)enum_, (zzcq)enum_5);
        zzcbArray = zzcb39;
        zzhb = zzcb39 = new zzcb("UINT64", 3, 3, (zzcd)enum_, (zzcq)enum_5);
        Enum enum_6 = zzcq.zzky;
        zzcbArray = zzcb38;
        zzcbArray2 = enum_6;
        zzhc = zzcb38 = new zzcb("INT32", 4, 4, (zzcd)enum_, (zzcq)enum_6);
        zzcbArray = zzcb37;
        zzcbArray2 = enum_5;
        zzhd = zzcb37 = new zzcb("FIXED64", 5, 5, (zzcd)enum_, (zzcq)enum_5);
        zzcbArray = zzcb36;
        zzcbArray2 = enum_6;
        zzhe = zzcb36 = new zzcb("FIXED32", 6, 6, (zzcd)enum_, (zzcq)enum_6);
        Enum enum_7 = zzcq.zzlc;
        zzcbArray = zzcb35;
        zzcbArray2 = enum_7;
        zzhf = zzcb35 = new zzcb("BOOL", 7, 7, (zzcd)enum_, (zzcq)enum_7);
        Enum enum_8 = zzcq.zzld;
        zzcbArray = zzcb34;
        zzcbArray2 = enum_8;
        zzhg = zzcb34 = new zzcb("STRING", 8, 8, (zzcd)enum_, (zzcq)enum_8);
        zzcq zzcq2 = zzcq.zzlg;
        zzcbArray = zzcb33;
        zzcbArray2 = zzcq2;
        zzhh = zzcb33 = new zzcb("MESSAGE", 9, 9, (zzcd)enum_, zzcq2);
        Enum enum_9 = zzcq.zzle;
        zzcbArray = zzcb32;
        zzcbArray2 = enum_9;
        zzhi = zzcb32 = new zzcb("BYTES", 10, 10, (zzcd)enum_, (zzcq)enum_9);
        zzcbArray = zzcb31;
        zzcbArray2 = enum_6;
        zzhj = zzcb31 = new zzcb("UINT32", 11, 11, (zzcd)enum_, (zzcq)enum_6);
        Enum enum_10 = zzcq.zzlf;
        zzcbArray = zzcb30;
        zzcbArray2 = enum_10;
        zzhk = zzcb30 = new zzcb("ENUM", 12, 12, (zzcd)enum_, (zzcq)enum_10);
        zzcbArray = zzcb29;
        zzcbArray2 = enum_6;
        zzhl = zzcb29 = new zzcb("SFIXED32", 13, 13, (zzcd)enum_, (zzcq)enum_6);
        zzcbArray = zzcb28;
        zzcbArray2 = enum_5;
        zzhm = zzcb28 = new zzcb("SFIXED64", 14, 14, (zzcd)enum_, (zzcq)enum_5);
        zzcbArray = zzcb27;
        zzcbArray2 = enum_6;
        zzhn = zzcb27 = new zzcb("SINT32", 15, 15, (zzcd)enum_, (zzcq)enum_6);
        zzcbArray = zzcb26;
        zzcbArray2 = enum_5;
        zzho = zzcb26 = new zzcb("SINT64", 16, 16, (zzcd)enum_, (zzcq)enum_5);
        zzcbArray = zzcb25;
        zzcbArray2 = zzcq2;
        zzhp = zzcb25 = new zzcb("GROUP", 17, 17, (zzcd)enum_, zzcq2);
        zzcd zzcd2 = zzcd.zzjh;
        zzcbArray = enum_;
        enum_3 = zzcd2;
        zzcbArray2 = enum_2;
        zzhq = enum_ = new zzcb("DOUBLE_LIST", 18, 18, zzcd2, (zzcq)enum_2);
        zzcbArray = zzcb24;
        zzcbArray2 = enum_4;
        zzhr = zzcb24 = new zzcb("FLOAT_LIST", 19, 19, zzcd2, (zzcq)enum_4);
        zzcbArray = zzcb23;
        zzcbArray2 = enum_5;
        zzhs = zzcb23 = new zzcb("INT64_LIST", 20, 20, zzcd2, (zzcq)enum_5);
        zzcbArray = zzcb22;
        zzht = zzcb22 = new zzcb("UINT64_LIST", 21, 21, zzcd2, (zzcq)enum_5);
        zzcbArray = zzcb21;
        zzcbArray2 = enum_6;
        zzhu = zzcb21 = new zzcb("INT32_LIST", 22, 22, zzcd2, (zzcq)enum_6);
        zzcbArray = zzcb20;
        zzcbArray2 = enum_5;
        zzhv = zzcb20 = new zzcb("FIXED64_LIST", 23, 23, zzcd2, (zzcq)enum_5);
        zzcbArray = zzcb19;
        zzcbArray2 = enum_6;
        zzhw = zzcb19 = new zzcb("FIXED32_LIST", 24, 24, zzcd2, (zzcq)enum_6);
        zzcbArray = zzcb18;
        zzcbArray2 = enum_7;
        zzhx = zzcb18 = new zzcb("BOOL_LIST", 25, 25, zzcd2, (zzcq)enum_7);
        zzcbArray = zzcb17;
        zzcbArray2 = enum_8;
        zzhy = zzcb17 = new zzcb("STRING_LIST", 26, 26, zzcd2, (zzcq)enum_8);
        zzcbArray = enum_8;
        zzcbArray2 = zzcq2;
        zzhz = enum_8 = new zzcb("MESSAGE_LIST", 27, 27, zzcd2, zzcq2);
        zzcbArray = zzcb16;
        zzcbArray2 = enum_9;
        zzia = zzcb16 = new zzcb("BYTES_LIST", 28, 28, zzcd2, (zzcq)enum_9);
        zzcbArray = enum_9;
        zzcbArray2 = enum_6;
        zzib = enum_9 = new zzcb("UINT32_LIST", 29, 29, zzcd2, (zzcq)enum_6);
        zzcbArray = zzcb15;
        zzcbArray2 = enum_10;
        zzic = zzcb15 = new zzcb("ENUM_LIST", 30, 30, zzcd2, (zzcq)enum_10);
        zzcbArray = zzcb14;
        zzcbArray2 = enum_6;
        zzid = zzcb14 = new zzcb("SFIXED32_LIST", 31, 31, zzcd2, (zzcq)enum_6);
        zzcbArray = zzcb13;
        zzcbArray2 = enum_5;
        zzie = zzcb13 = new zzcb("SFIXED64_LIST", 32, 32, zzcd2, (zzcq)enum_5);
        zzcbArray = zzcb12;
        zzcbArray2 = enum_6;
        zzif = zzcb12 = new zzcb("SINT32_LIST", 33, 33, zzcd2, (zzcq)enum_6);
        zzcbArray = zzcb11;
        zzcbArray2 = enum_5;
        zzig = zzcb11 = new zzcb("SINT64_LIST", 34, 34, zzcd2, (zzcq)enum_5);
        zzcd zzcd3 = zzcd.zzji;
        zzcbArray = zzcb10;
        enum_3 = zzcd3;
        zzcbArray2 = enum_2;
        zzih = zzcb10 = new zzcb("DOUBLE_LIST_PACKED", 35, 35, zzcd3, (zzcq)enum_2);
        zzcbArray = enum_2;
        zzcbArray2 = enum_4;
        zzii = enum_2 = new zzcb("FLOAT_LIST_PACKED", 36, 36, zzcd3, (zzcq)enum_4);
        zzcbArray = enum_4;
        zzcbArray2 = enum_5;
        zzij = enum_4 = new zzcb("INT64_LIST_PACKED", 37, 37, zzcd3, (zzcq)enum_5);
        zzcbArray = zzcb9;
        zzik = zzcb9 = new zzcb("UINT64_LIST_PACKED", 38, 38, zzcd3, (zzcq)enum_5);
        zzcbArray = zzcb8;
        zzcbArray2 = enum_6;
        zzil = zzcb8 = new zzcb("INT32_LIST_PACKED", 39, 39, zzcd3, (zzcq)enum_6);
        zzcbArray = zzcb7;
        zzcbArray2 = enum_5;
        zzim = zzcb7 = new zzcb("FIXED64_LIST_PACKED", 40, 40, zzcd3, (zzcq)enum_5);
        zzcbArray = zzcb6;
        zzcbArray2 = enum_6;
        zzin = zzcb6 = new zzcb("FIXED32_LIST_PACKED", 41, 41, zzcd3, (zzcq)enum_6);
        zzcbArray = zzcb5;
        zzcbArray2 = enum_7;
        zzio = zzcb5 = new zzcb("BOOL_LIST_PACKED", 42, 42, zzcd3, (zzcq)enum_7);
        zzcbArray = enum_7;
        zzcbArray2 = enum_6;
        zzip = enum_7 = new zzcb("UINT32_LIST_PACKED", 43, 43, zzcd3, (zzcq)enum_6);
        zzcbArray = zzcb4;
        zzcbArray2 = enum_10;
        zziq = zzcb4 = new zzcb("ENUM_LIST_PACKED", 44, 44, zzcd3, (zzcq)enum_10);
        zzcbArray = enum_10;
        zzcbArray2 = enum_6;
        zzir = enum_10 = new zzcb("SFIXED32_LIST_PACKED", 45, 45, zzcd3, (zzcq)enum_6);
        zzcbArray = zzcb3;
        zzcbArray2 = enum_5;
        zzis = zzcb3 = new zzcb("SFIXED64_LIST_PACKED", 46, 46, zzcd3, (zzcq)enum_5);
        zzcbArray = zzcb2;
        zzcbArray2 = enum_6;
        zzit = zzcb2 = new zzcb("SINT32_LIST_PACKED", 47, 47, zzcd3, (zzcq)enum_6);
        zzcbArray = enum_6;
        zzcbArray2 = enum_5;
        zziu = enum_6 = new zzcb("SINT64_LIST_PACKED", 48, 48, zzcd3, (zzcq)enum_5);
        zzcbArray = enum_5;
        enum_3 = zzcd2;
        zzcbArray2 = zzcq2;
        zziv = enum_5 = new zzcb("GROUP_LIST", 49, 49, zzcd2, zzcq2);
        zzcd zzcd4 = zzcd.zzjj;
        zzcq zzcq3 = zzcq.zzkx;
        String string2 = "MAP";
        int n3 = 50;
        int n4 = 50;
        zzcbArray = new zzcb(string2, n3, n4, zzcd4, zzcq3);
        zziw = zzcbArray;
        zzcb[] zzcbArray3 = new zzcb[51];
        zzcbArray3[0] = zzcb42;
        int n7 = 1;
        zzcbArray3[n7] = zzcb41;
        zzcbArray3[2] = zzcb40;
        zzcbArray3[3] = zzcb39;
        zzcbArray3[4] = zzcb38;
        zzcbArray3[5] = zzcb37;
        zzcbArray3[6] = zzcb36;
        zzcbArray3[7] = zzcb35;
        zzcbArray3[8] = zzcb34;
        zzcbArray3[9] = zzcb33;
        zzcbArray3[10] = zzcb32;
        zzcbArray3[11] = zzcb31;
        zzcbArray3[12] = zzcb30;
        zzcbArray3[13] = zzcb29;
        zzcbArray3[14] = zzcb28;
        zzcbArray3[15] = zzcb27;
        zzcbArray3[16] = zzcb26;
        zzcbArray3[17] = zzcb25;
        zzcbArray3[18] = enum_;
        zzcbArray3[19] = zzcb24;
        zzcbArray3[20] = zzcb23;
        zzcbArray3[21] = zzcb22;
        zzcbArray3[22] = zzcb21;
        zzcbArray3[23] = zzcb20;
        zzcbArray3[24] = zzcb19;
        zzcbArray3[25] = zzcb18;
        zzcbArray3[26] = zzcb17;
        zzcbArray3[27] = enum_8;
        zzcbArray3[28] = zzcb16;
        zzcbArray3[29] = enum_9;
        zzcbArray3[30] = zzcb15;
        zzcbArray3[31] = zzcb14;
        zzcbArray3[32] = zzcb13;
        zzcbArray3[33] = zzcb12;
        zzcbArray3[34] = zzcb11;
        zzcbArray3[35] = zzcb10;
        zzcbArray3[36] = enum_2;
        zzcbArray3[37] = enum_4;
        zzcbArray3[38] = zzcb9;
        zzcbArray3[39] = zzcb8;
        zzcbArray3[40] = zzcb7;
        zzcbArray3[41] = zzcb6;
        zzcbArray3[42] = zzcb5;
        zzcbArray3[43] = enum_7;
        zzcbArray3[44] = zzcb4;
        zzcbArray3[45] = enum_10;
        zzcbArray3[46] = zzcb3;
        zzcbArray3[47] = zzcb2;
        zzcbArray3[48] = enum_6;
        zzcbArray3[49] = enum_5;
        int n8 = 50;
        zzcbArray3[n8] = zzcbArray;
        zzjd = zzcbArray3;
        zzjc = new Type[0];
        zzcbArray = zzcb.values();
        zzcbArray3 = new zzcb[zzcbArray.length];
        zzjb = zzcbArray3;
        int n10 = zzcbArray.length;
        for (int i3 = 0; i3 < n10; i3 += n7) {
            enum_3 = zzcbArray[i3];
            zzcbArray2 = zzjb;
            int n14 = ((zzcb)enum_3).id;
            zzcbArray2[n14] = enum_3;
        }
    }

    /*
     * WARNING - Possible parameter corruption
     * WARNING - void declaration
     * Enabled aggressive block sorting
     */
    private zzcb(zzcq zzcq2) {
        int n4;
        int[] nArray;
        void var1_7;
        void var5_4;
        void var4_3;
        void var2_-1;
        void var1_-1;
        this.id = (int)zzcq2;
        this.zziy = var4_3;
        this.zzix = var5_4;
        int[] nArray2 = zzcc.zzje;
        int n7 = var4_3.ordinal();
        int n8 = nArray2[n7];
        n7 = 2;
        int n10 = 1;
        if (n8 != n10 && n8 != n7) {
            n8 = 0;
            Object var1_6 = null;
        } else {
            Class clazz = var5_4.zzbq();
        }
        this.zziz = var1_7;
        zzcd zzcd2 = zzcd.zzjg;
        if (var4_3 != zzcd2 || (n8 = (nArray = zzcc.zzjf)[n4 = var5_4.ordinal()]) == n10 || n8 == n7 || n8 == (n7 = 3)) {
            n10 = 0;
        }
        this.zzja = n10;
    }

    public static zzcb[] values() {
        return (zzcb[])zzjd.clone();
    }

    public final int id() {
        return this.id;
    }
}

