/*
 * Decompiled with CFR 0.152.
 */
package com.google.zxing.oned.rss.expanded.decoders;

import com.google.zxing.NotFoundException;

final class FieldParser {
    private static final Object[][] FOUR_DIGIT_DATA_LENGTH;
    private static final Object[][] THREE_DIGIT_DATA_LENGTH;
    private static final Object[][] THREE_DIGIT_PLUS_DIGIT_DATA_LENGTH;
    private static final Object[][] TWO_DIGIT_DATA_LENGTH;
    private static final Object VARIABLE_LENGTH;

    static {
        Object[] objectArray = new Object();
        VARIABLE_LENGTH = objectArray;
        Object[] objectArray2 = Integer.valueOf(18);
        int n3 = 2;
        Object[] objectArray3 = new Object[n3];
        objectArray3[0] = "00";
        int n4 = 1;
        objectArray3[n4] = objectArray2;
        Object[] objectArray4 = Integer.valueOf(14);
        Object[] objectArray5 = new Object[n3];
        objectArray5[0] = "01";
        objectArray5[n4] = objectArray4;
        Object[] objectArray6 = new Object[n3];
        objectArray6[0] = "02";
        objectArray6[n4] = objectArray4;
        Object[] objectArray7 = Integer.valueOf(20);
        Object[] objectArray8 = new Object[3];
        objectArray8[0] = "10";
        objectArray8[n4] = objectArray;
        objectArray8[n3] = objectArray7;
        Object[] objectArray9 = Integer.valueOf(6);
        Object[] objectArray10 = new Object[n3];
        objectArray10[0] = "11";
        objectArray10[n4] = objectArray9;
        Object[] objectArray11 = new Object[n3];
        objectArray11[0] = "12";
        objectArray11[n4] = objectArray9;
        Object[] objectArray12 = new Object[n3];
        objectArray12[0] = "13";
        objectArray12[n4] = objectArray9;
        Object[] objectArray13 = new Object[n3];
        objectArray13[0] = "15";
        objectArray13[n4] = objectArray9;
        Object[] objectArray14 = new Object[n3];
        objectArray14[0] = "17";
        objectArray14[n4] = objectArray9;
        Integer n7 = n3;
        Object[] objectArray15 = new Object[n3];
        objectArray15[0] = "20";
        int n8 = 1;
        objectArray15[n8] = n7;
        Object[] objectArray16 = objectArray4;
        n3 = 3;
        objectArray4 = new Object[n3];
        objectArray4[0] = "21";
        objectArray4[n8] = objectArray;
        int n10 = 2;
        objectArray4[n10] = objectArray7;
        Integer n14 = 29;
        Object[] objectArray17 = objectArray2;
        objectArray2 = new Object[n3];
        objectArray2[0] = "22";
        objectArray2[n8] = objectArray;
        objectArray2[n10] = n14;
        int n15 = 8;
        n14 = n15;
        Object[] objectArray18 = objectArray7;
        objectArray7 = new Object[n3];
        objectArray7[0] = "30";
        objectArray7[n8] = objectArray;
        objectArray7[n10] = n14;
        Object[] objectArray19 = objectArray7;
        objectArray7 = new Object[n3];
        objectArray7[0] = "37";
        objectArray7[n8] = objectArray;
        objectArray7[n10] = n14;
        Integer n16 = 30;
        Object[] objectArray20 = objectArray7;
        objectArray7 = new Object[n3];
        objectArray7[0] = "90";
        objectArray7[n8] = objectArray;
        objectArray7[n10] = n16;
        Object[] objectArray21 = objectArray7;
        objectArray7 = new Object[n3];
        objectArray7[0] = "91";
        objectArray7[n8] = objectArray;
        objectArray7[n10] = n16;
        Object[] objectArray22 = objectArray7;
        objectArray7 = new Object[n3];
        objectArray7[0] = "92";
        objectArray7[n8] = objectArray;
        objectArray7[n10] = n16;
        Object[] objectArray23 = objectArray7;
        objectArray7 = new Object[n3];
        objectArray7[0] = "93";
        objectArray7[n8] = objectArray;
        objectArray7[n10] = n16;
        Object[] objectArray24 = objectArray7;
        objectArray7 = new Object[n3];
        objectArray7[0] = "94";
        objectArray7[n8] = objectArray;
        objectArray7[n10] = n16;
        Object[] objectArray25 = objectArray7;
        objectArray7 = new Object[n3];
        objectArray7[0] = "95";
        objectArray7[n8] = objectArray;
        objectArray7[n10] = n16;
        Object[] objectArray26 = objectArray7;
        objectArray7 = new Object[n3];
        objectArray7[0] = "96";
        objectArray7[n8] = objectArray;
        objectArray7[n10] = n16;
        Object[] objectArray27 = objectArray7;
        objectArray7 = new Object[n3];
        objectArray7[0] = "97";
        objectArray7[n8] = objectArray;
        objectArray7[n10] = n16;
        Object[] objectArray28 = objectArray7;
        objectArray7 = new Object[n3];
        objectArray7[0] = "98";
        objectArray7[n8] = objectArray;
        objectArray7[n10] = n16;
        Object[] objectArray29 = objectArray7;
        objectArray7 = new Object[n3];
        objectArray7[0] = "99";
        objectArray7[n8] = objectArray;
        objectArray7[n10] = n16;
        Object object = new Object[24][];
        object[0] = objectArray3;
        object[n8] = objectArray5;
        object[n10] = objectArray6;
        object[3] = objectArray8;
        object[4] = objectArray10;
        object[5] = objectArray11;
        object[6] = objectArray12;
        object[7] = objectArray13;
        object[n15] = objectArray14;
        object[9] = objectArray15;
        object[10] = objectArray4;
        object[11] = objectArray2;
        object[12] = objectArray19;
        int n17 = 13;
        object[n17] = objectArray20;
        object[14] = objectArray21;
        object[15] = objectArray22;
        object[16] = objectArray23;
        int n18 = 17;
        object[n18] = objectArray24;
        object[18] = objectArray25;
        object[19] = objectArray26;
        object[20] = objectArray27;
        int n19 = 21;
        object[n19] = objectArray28;
        object[22] = objectArray29;
        object[23] = objectArray7;
        TWO_DIGIT_DATA_LENGTH = object;
        n3 = 3;
        objectArray7 = new Object[n3];
        objectArray7[0] = "240";
        n8 = 1;
        objectArray7[n8] = objectArray;
        int n20 = 2;
        objectArray7[n20] = n16;
        objectArray14 = new Object[n3];
        objectArray14[0] = "241";
        objectArray14[n8] = objectArray;
        objectArray14[n20] = n16;
        objectArray2 = new Object[n3];
        objectArray2[0] = "242";
        objectArray2[n8] = objectArray;
        objectArray2[n20] = objectArray9;
        objectArray4 = new Object[n3];
        objectArray4[0] = "250";
        objectArray4[n8] = objectArray;
        objectArray4[n20] = n16;
        objectArray15 = new Object[n3];
        objectArray15[0] = "251";
        objectArray15[n8] = objectArray;
        objectArray15[n20] = n16;
        Object object2 = n18;
        objectArray8 = new Object[n3];
        objectArray8[0] = "253";
        objectArray8[n8] = objectArray;
        objectArray8[n20] = object2;
        objectArray12 = new Object[n3];
        objectArray12[0] = "254";
        objectArray12[n8] = objectArray;
        objectArray12[n20] = objectArray18;
        objectArray11 = new Object[n3];
        objectArray11[0] = "400";
        objectArray11[n8] = objectArray;
        objectArray11[n20] = n16;
        objectArray5 = new Object[n3];
        objectArray5[0] = "401";
        objectArray5[n8] = objectArray;
        objectArray5[n20] = n16;
        objectArray3 = new Object[n20];
        objectArray3[0] = "402";
        objectArray3[n8] = object2;
        objectArray10 = new Object[n3];
        objectArray10[0] = "403";
        objectArray10[n8] = objectArray;
        objectArray10[n20] = n16;
        object = n17;
        objectArray6 = new Object[n20];
        objectArray6[0] = "410";
        objectArray6[n8] = object;
        Object[] objectArray30 = objectArray6;
        objectArray6 = new Object[n20];
        objectArray6[0] = "411";
        objectArray6[n8] = object;
        Object[] objectArray31 = objectArray6;
        objectArray6 = new Object[n20];
        objectArray6[0] = "412";
        objectArray6[n8] = object;
        Object[] objectArray32 = objectArray6;
        objectArray6 = new Object[n20];
        objectArray6[0] = "413";
        objectArray6[n8] = object;
        Object[] objectArray33 = objectArray6;
        objectArray6 = new Object[n20];
        objectArray6[0] = "414";
        objectArray6[n8] = object;
        Object object3 = object;
        n20 = 3;
        object = new Object[n20];
        object[0] = "420";
        object[n8] = objectArray;
        object[2] = objectArray18;
        Object[] objectArray34 = Integer.valueOf(15);
        Object object4 = new Object[n20];
        object4[0] = "421";
        object4[n8] = objectArray;
        Object object5 = object;
        n3 = 2;
        object4[n3] = objectArray34;
        n14 = n20;
        objectArray13 = new Object[n3];
        objectArray13[0] = "422";
        objectArray13[n8] = n14;
        Object[] objectArray35 = objectArray13;
        objectArray13 = new Object[3];
        objectArray13[0] = "423";
        objectArray13[n8] = objectArray;
        n3 = 2;
        objectArray13[n3] = objectArray34;
        Object[] objectArray36 = objectArray;
        objectArray = new Object[n3];
        objectArray[0] = "424";
        objectArray[n8] = n14;
        Object[] objectArray37 = objectArray;
        objectArray = new Object[n3];
        objectArray[0] = "425";
        objectArray[n8] = n14;
        Object[] objectArray38 = objectArray;
        objectArray = new Object[n3];
        objectArray[0] = "426";
        objectArray[n8] = n14;
        object = new Object[23][];
        object[0] = objectArray7;
        object[n8] = objectArray14;
        object[2] = objectArray2;
        object[3] = objectArray4;
        object[4] = objectArray15;
        object[5] = objectArray8;
        object[6] = objectArray12;
        object[7] = objectArray11;
        object[n15] = objectArray5;
        object[9] = objectArray3;
        object[10] = objectArray10;
        object[11] = objectArray30;
        object[12] = objectArray31;
        object[13] = objectArray32;
        object[14] = objectArray33;
        object[15] = objectArray6;
        object[16] = object5;
        object[17] = object4;
        object[18] = objectArray35;
        object[19] = objectArray13;
        object[20] = objectArray37;
        object[n19] = objectArray38;
        object[22] = objectArray;
        THREE_DIGIT_DATA_LENGTH = object;
        int n21 = 2;
        objectArray11 = new Object[n21];
        objectArray11[0] = "310";
        int n22 = 1;
        objectArray11[n22] = objectArray9;
        objectArray3 = new Object[n21];
        objectArray3[0] = "311";
        objectArray3[n22] = objectArray9;
        objectArray15 = new Object[n21];
        objectArray15[0] = "312";
        objectArray15[n22] = objectArray9;
        object4 = new Object[n21];
        object4[0] = "313";
        object4[n22] = objectArray9;
        objectArray12 = new Object[n21];
        objectArray12[0] = "314";
        objectArray12[n22] = objectArray9;
        objectArray4 = new Object[n21];
        objectArray4[0] = "315";
        objectArray4[n22] = objectArray9;
        objectArray5 = new Object[n21];
        objectArray5[0] = "316";
        objectArray5[n22] = objectArray9;
        objectArray6 = new Object[n21];
        objectArray6[0] = "320";
        objectArray6[n22] = objectArray9;
        objectArray10 = new Object[n21];
        objectArray10[0] = "321";
        objectArray10[n22] = objectArray9;
        objectArray7 = new Object[n21];
        objectArray7[0] = "322";
        objectArray7[n22] = objectArray9;
        objectArray14 = new Object[n21];
        objectArray14[0] = "323";
        objectArray14[n22] = objectArray9;
        objectArray8 = new Object[n21];
        objectArray8[0] = "324";
        objectArray8[n22] = objectArray9;
        objectArray13 = new Object[n21];
        objectArray13[0] = "325";
        objectArray13[n22] = objectArray9;
        objectArray2 = new Object[n21];
        objectArray2[0] = "326";
        n8 = 1;
        objectArray2[n8] = objectArray9;
        objectArray30 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "327";
        objectArray2[n8] = objectArray9;
        objectArray31 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "328";
        objectArray2[n8] = objectArray9;
        objectArray32 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "329";
        objectArray2[n8] = objectArray9;
        objectArray33 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "330";
        objectArray2[n8] = objectArray9;
        object5 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "331";
        objectArray2[n8] = objectArray9;
        objectArray35 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "332";
        objectArray2[n8] = objectArray9;
        objectArray37 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "333";
        objectArray2[n8] = objectArray9;
        objectArray38 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "334";
        objectArray2[n8] = objectArray9;
        Object[] objectArray39 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "335";
        objectArray2[n8] = objectArray9;
        Object[] objectArray40 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "336";
        objectArray2[n8] = objectArray9;
        Object[] objectArray41 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "340";
        objectArray2[n8] = objectArray9;
        Object[] objectArray42 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "341";
        objectArray2[n8] = objectArray9;
        Object[] objectArray43 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "342";
        objectArray2[n8] = objectArray9;
        Object[] objectArray44 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "343";
        objectArray2[n8] = objectArray9;
        Object[] objectArray45 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "344";
        objectArray2[n8] = objectArray9;
        Object[] objectArray46 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "345";
        objectArray2[n8] = objectArray9;
        Object[] objectArray47 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "346";
        objectArray2[n8] = objectArray9;
        Object[] objectArray48 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "347";
        objectArray2[n8] = objectArray9;
        Object[] objectArray49 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "348";
        objectArray2[n8] = objectArray9;
        Object[] objectArray50 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "349";
        objectArray2[n8] = objectArray9;
        Object[] objectArray51 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "350";
        objectArray2[n8] = objectArray9;
        Object[] objectArray52 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "351";
        objectArray2[n8] = objectArray9;
        Object[] objectArray53 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "352";
        objectArray2[n8] = objectArray9;
        Object[] objectArray54 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "353";
        objectArray2[n8] = objectArray9;
        Object[] objectArray55 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "354";
        objectArray2[n8] = objectArray9;
        Object[] objectArray56 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "355";
        objectArray2[n8] = objectArray9;
        Object[] objectArray57 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "356";
        objectArray2[n8] = objectArray9;
        Object[] objectArray58 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "357";
        objectArray2[n8] = objectArray9;
        Object[] objectArray59 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "360";
        objectArray2[n8] = objectArray9;
        Object[] objectArray60 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "361";
        objectArray2[n8] = objectArray9;
        Object[] objectArray61 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "362";
        objectArray2[n8] = objectArray9;
        Object[] objectArray62 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "363";
        objectArray2[n8] = objectArray9;
        Object[] objectArray63 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "364";
        objectArray2[n8] = objectArray9;
        Object[] objectArray64 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "365";
        objectArray2[n8] = objectArray9;
        Object[] objectArray65 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "366";
        objectArray2[n8] = objectArray9;
        Object[] objectArray66 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "367";
        objectArray2[n8] = objectArray9;
        Object[] objectArray67 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "368";
        objectArray2[n8] = objectArray9;
        Object[] objectArray68 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "369";
        objectArray2[n8] = objectArray9;
        Object[] objectArray69 = objectArray2;
        n21 = 3;
        objectArray2 = new Object[n21];
        objectArray2[0] = "390";
        objectArray2[n8] = objectArray36;
        n10 = 2;
        objectArray2[n10] = objectArray34;
        Object[] objectArray70 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "391";
        objectArray2[n8] = objectArray36;
        objectArray2[n10] = objectArray17;
        Object[] objectArray71 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "392";
        objectArray2[n8] = objectArray36;
        objectArray2[n10] = objectArray34;
        objectArray34 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "393";
        objectArray2[n8] = objectArray36;
        objectArray2[n10] = objectArray17;
        Object[] objectArray72 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "703";
        objectArray2[n8] = objectArray36;
        objectArray2[n10] = n16;
        objectArray = new Object[57][];
        objectArray[0] = objectArray11;
        objectArray[n8] = objectArray3;
        objectArray[n10] = objectArray15;
        objectArray[3] = object4;
        objectArray[4] = objectArray12;
        objectArray[5] = objectArray4;
        objectArray[6] = objectArray5;
        objectArray[7] = objectArray6;
        objectArray[n15] = objectArray10;
        objectArray[9] = objectArray7;
        objectArray[10] = objectArray14;
        objectArray[11] = objectArray8;
        objectArray[12] = objectArray13;
        objectArray[13] = objectArray30;
        objectArray[14] = objectArray31;
        objectArray[15] = objectArray32;
        objectArray[16] = objectArray33;
        objectArray[17] = object5;
        objectArray[18] = objectArray35;
        objectArray[19] = objectArray37;
        objectArray[20] = objectArray38;
        objectArray[n19] = objectArray39;
        objectArray[22] = objectArray40;
        objectArray[23] = objectArray41;
        objectArray[24] = objectArray42;
        objectArray[25] = objectArray43;
        objectArray[26] = objectArray44;
        objectArray[27] = objectArray45;
        objectArray[28] = objectArray46;
        objectArray[29] = objectArray47;
        objectArray[30] = objectArray48;
        objectArray[31] = objectArray49;
        objectArray[32] = objectArray50;
        objectArray[33] = objectArray51;
        objectArray[34] = objectArray52;
        objectArray[35] = objectArray53;
        objectArray[36] = objectArray54;
        objectArray[37] = objectArray55;
        objectArray[38] = objectArray56;
        objectArray[39] = objectArray57;
        objectArray[40] = objectArray58;
        objectArray[41] = objectArray59;
        objectArray[42] = objectArray60;
        objectArray[43] = objectArray61;
        objectArray[44] = objectArray62;
        objectArray[45] = objectArray63;
        objectArray[46] = objectArray64;
        objectArray[47] = objectArray65;
        objectArray[48] = objectArray66;
        objectArray[49] = objectArray67;
        objectArray[50] = objectArray68;
        objectArray[51] = objectArray69;
        objectArray[52] = objectArray70;
        objectArray[53] = objectArray71;
        objectArray[54] = objectArray34;
        objectArray[55] = objectArray72;
        objectArray[56] = objectArray2;
        THREE_DIGIT_PLUS_DIGIT_DATA_LENGTH = objectArray;
        n21 = 2;
        objectArray11 = new Object[n21];
        objectArray11[0] = "7001";
        n22 = 1;
        objectArray11[n22] = object3;
        objectArray15 = new Object[3];
        objectArray15[0] = "7002";
        objectArray15[n22] = objectArray36;
        objectArray15[n21] = n16;
        object4 = 10;
        objectArray3 = new Object[n21];
        objectArray3[0] = "7003";
        objectArray3[n22] = object4;
        objectArray12 = new Object[n21];
        objectArray12[0] = "8001";
        objectArray12[n22] = objectArray16;
        int n24 = 3;
        objectArray5 = new Object[n24];
        objectArray5[0] = "8002";
        objectArray5[n22] = objectArray36;
        objectArray5[n21] = objectArray18;
        objectArray6 = new Object[n24];
        objectArray6[0] = "8003";
        objectArray6[n22] = objectArray36;
        objectArray6[n21] = n16;
        objectArray10 = new Object[n24];
        objectArray10[0] = "8004";
        objectArray10[n22] = objectArray36;
        objectArray10[n21] = n16;
        objectArray4 = new Object[n21];
        objectArray4[0] = "8005";
        objectArray4[n22] = objectArray9;
        objectArray7 = new Object[n21];
        objectArray7[0] = "8006";
        objectArray7[n22] = objectArray17;
        int n25 = 3;
        objectArray8 = new Object[n25];
        objectArray8[0] = "8007";
        objectArray8[n22] = objectArray36;
        objectArray8[n21] = n16;
        Object[] objectArray73 = Integer.valueOf(12);
        objectArray13 = new Object[n25];
        objectArray13[0] = "8008";
        objectArray13[n22] = objectArray36;
        objectArray13[n21] = objectArray73;
        objectArray14 = new Object[n21];
        objectArray14[0] = "8018";
        objectArray14[n22] = objectArray17;
        objectArray73 = 25;
        objectArray2 = new Object[3];
        objectArray2[0] = "8020";
        objectArray2[1] = objectArray36;
        n21 = 2;
        objectArray2[n21] = objectArray73;
        objectArray73 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "8100";
        n8 = 1;
        objectArray2[n8] = objectArray9;
        objectArray9 = objectArray2;
        objectArray2 = new Object[n21];
        objectArray2[0] = "8101";
        objectArray2[n8] = object4;
        object4 = new Object[n21];
        object4[0] = "8102";
        object4[n8] = n7;
        n7 = 70;
        object2 = object4;
        n21 = 3;
        object4 = new Object[n21];
        object4[0] = "8110";
        object4[n8] = objectArray36;
        int n26 = 2;
        object4[n26] = n7;
        objectArray16 = object4;
        object4 = new Object[n21];
        object4[0] = "8200";
        object4[n8] = objectArray36;
        object4[n26] = n7;
        objectArray = new Object[18][];
        objectArray[0] = objectArray11;
        objectArray[n8] = objectArray15;
        objectArray[n26] = objectArray3;
        objectArray[3] = objectArray12;
        objectArray[4] = objectArray5;
        objectArray[5] = objectArray6;
        objectArray[6] = objectArray10;
        objectArray[7] = objectArray4;
        objectArray[n15] = objectArray7;
        objectArray[9] = objectArray8;
        objectArray[10] = objectArray13;
        objectArray[11] = objectArray14;
        objectArray[12] = objectArray73;
        objectArray[13] = objectArray9;
        objectArray[14] = objectArray2;
        objectArray[15] = object2;
        objectArray[16] = objectArray16;
        objectArray[17] = object4;
        FOUR_DIGIT_DATA_LENGTH = objectArray;
    }

    private FieldParser() {
    }

    public static String parseFieldsInGeneralPurpose(String string2) {
        int n3;
        int n4 = string2.isEmpty();
        if (n4 != 0) {
            return null;
        }
        n4 = string2.length();
        if (n4 >= (n3 = 2)) {
            int n7;
            Object[] objectArray5;
            Object[] objectArray2;
            int n8;
            n4 = 0;
            Object object = null;
            Object object2 = string2.substring(0, n3);
            Object[][] objectArray3 = TWO_DIGIT_DATA_LENGTH;
            int n10 = objectArray3.length;
            int n14 = 0;
            while (true) {
                n8 = 1;
                if (n14 >= n10) break;
                objectArray2 = objectArray3[n14];
                objectArray5 = objectArray2[0];
                boolean bl2 = objectArray5.equals(object2);
                if (bl2) {
                    object = objectArray2[n8];
                    object2 = VARIABLE_LENGTH;
                    if (object == object2) {
                        n4 = (Integer)objectArray2[n3];
                        return FieldParser.processVariableAI(n3, n4, string2);
                    }
                    n4 = (Integer)object;
                    return FieldParser.processFixedAI(n3, n4, string2);
                }
                ++n14;
            }
            int n15 = string2.length();
            if (n15 >= (n7 = 3)) {
                boolean bl3;
                Object object3;
                int n16;
                object2 = string2.substring(0, n7);
                Object[][] objectArray4 = THREE_DIGIT_DATA_LENGTH;
                n14 = objectArray4.length;
                objectArray2 = null;
                for (n16 = 0; n16 < n14; ++n16) {
                    objectArray5 = objectArray4[n16];
                    object3 = objectArray5[0];
                    bl3 = object3.equals(object2);
                    if (!bl3) continue;
                    object = objectArray5[n8];
                    object2 = VARIABLE_LENGTH;
                    if (object == object2) {
                        n4 = (Integer)objectArray5[n3];
                        return FieldParser.processVariableAI(n7, n4, string2);
                    }
                    n4 = (Integer)object;
                    return FieldParser.processFixedAI(n7, n4, string2);
                }
                objectArray3 = THREE_DIGIT_PLUS_DIGIT_DATA_LENGTH;
                n10 = objectArray3.length;
                n14 = 0;
                while (true) {
                    n16 = 4;
                    if (n14 >= n10) break;
                    objectArray5 = objectArray3[n14];
                    object3 = objectArray5[0];
                    bl3 = object3.equals(object2);
                    if (bl3) {
                        object = objectArray5[n8];
                        object2 = VARIABLE_LENGTH;
                        if (object == object2) {
                            n4 = (Integer)objectArray5[n3];
                            return FieldParser.processVariableAI(n16, n4, string2);
                        }
                        n4 = (Integer)object;
                        return FieldParser.processFixedAI(n16, n4, string2);
                    }
                    ++n14;
                }
                n15 = string2.length();
                if (n15 >= n16) {
                    object2 = string2.substring(0, n16);
                    for (Object[] objectArray5 : FOUR_DIGIT_DATA_LENGTH) {
                        object3 = objectArray5[0];
                        bl3 = object3.equals(object2);
                        if (!bl3) continue;
                        object = objectArray5[n8];
                        object2 = VARIABLE_LENGTH;
                        if (object == object2) {
                            n4 = (Integer)objectArray5[n3];
                            return FieldParser.processVariableAI(n16, n4, string2);
                        }
                        n4 = (Integer)object;
                        return FieldParser.processFixedAI(n16, n4, string2);
                    }
                    throw NotFoundException.getNotFoundInstance();
                }
                throw NotFoundException.getNotFoundInstance();
            }
            throw NotFoundException.getNotFoundInstance();
        }
        throw NotFoundException.getNotFoundInstance();
    }

    private static String processFixedAI(int n3, int n4, String charSequence) {
        int n7 = ((String)charSequence).length();
        if (n7 >= n3) {
            n7 = 0;
            String string2 = ((String)charSequence).substring(0, n3);
            int n8 = ((String)charSequence).length();
            if (n8 >= (n4 += n3)) {
                String string3 = ((String)charSequence).substring(n3, n4);
                String string4 = ((String)charSequence).substring(n4);
                String string5 = "(";
                charSequence = new StringBuilder(string5);
                ((StringBuilder)charSequence).append(string2);
                n7 = 41;
                ((StringBuilder)charSequence).append((char)n7);
                ((StringBuilder)charSequence).append(string3);
                string3 = ((StringBuilder)charSequence).toString();
                string4 = FieldParser.parseFieldsInGeneralPurpose(string4);
                if (string4 == null) {
                    return string3;
                }
                return Ft2.a(string3, string4);
            }
            throw NotFoundException.getNotFoundInstance();
        }
        throw NotFoundException.getNotFoundInstance();
    }

    private static String processVariableAI(int n3, int n4, String charSequence) {
        char c2 = '\u0000';
        String string2 = ((String)charSequence).substring(0, n3);
        int n7 = ((String)charSequence).length();
        if (n7 < (n4 += n3)) {
            n4 = ((String)charSequence).length();
        }
        String string3 = ((String)charSequence).substring(n3, n4);
        String string4 = ((String)charSequence).substring(n4);
        String string5 = "(";
        charSequence = new StringBuilder(string5);
        ((StringBuilder)charSequence).append(string2);
        c2 = ')';
        ((StringBuilder)charSequence).append(c2);
        ((StringBuilder)charSequence).append(string3);
        string3 = ((StringBuilder)charSequence).toString();
        string4 = FieldParser.parseFieldsInGeneralPurpose(string4);
        if (string4 == null) {
            return string3;
        }
        return Ft2.a(string3, string4);
    }
}

