/*
 * Decompiled with CFR 0.152.
 */
package com.google.zxing.oned;

import java.util.ArrayList;
import java.util.List;

final class EANManufacturerOrgSupport {
    private final List countryIdentifiers;
    private final List ranges;

    public EANManufacturerOrgSupport() {
        ArrayList arrayList;
        this.ranges = arrayList = new ArrayList();
        this.countryIdentifiers = arrayList = new ArrayList();
    }

    private void add(int[] nArray, String string2) {
        this.ranges.add(nArray);
        this.countryIdentifiers.add(string2);
    }

    /*
     * Enabled aggressive block sorting
     * Enabled unnecessary exception pruning
     * Enabled aggressive exception aggregation
     */
    private void initIfNeeded() {
        synchronized (this) {
            Object object = this.ranges;
            int n3 = object.isEmpty();
            if (n3 == 0) {
                return;
            }
            n3 = 19;
            int n4 = 0;
            String string2 = null;
            object = new int[]{0, n3};
            string2 = "US/CA";
            this.add((int[])object, string2);
            n3 = 39;
            n4 = 30;
            object = new int[]{n4, n3};
            string2 = "US";
            this.add((int[])object, string2);
            n3 = 139;
            n4 = 60;
            object = new int[]{n4, n3};
            string2 = "US/CA";
            this.add((int[])object, string2);
            n3 = 379;
            n4 = 300;
            object = new int[]{n4, n3};
            string2 = "FR";
            this.add((int[])object, string2);
            n3 = 380;
            object = new int[]{n3};
            string2 = "BG";
            this.add((int[])object, string2);
            n3 = 383;
            object = new int[]{n3};
            string2 = "SI";
            this.add((int[])object, string2);
            n3 = 385;
            object = new int[]{n3};
            string2 = "HR";
            this.add((int[])object, string2);
            n3 = 387;
            object = new int[]{n3};
            string2 = "BA";
            this.add((int[])object, string2);
            n3 = 440;
            n4 = 400;
            object = new int[]{n4, n3};
            string2 = "DE";
            this.add((int[])object, string2);
            n3 = 459;
            n4 = 450;
            object = new int[]{n4, n3};
            string2 = "JP";
            this.add((int[])object, string2);
            n3 = 469;
            n4 = 460;
            object = new int[]{n4, n3};
            string2 = "RU";
            this.add((int[])object, string2);
            n3 = 471;
            object = new int[]{n3};
            string2 = "TW";
            this.add((int[])object, string2);
            n3 = 474;
            object = new int[]{n3};
            string2 = "EE";
            this.add((int[])object, string2);
            n3 = 475;
            object = new int[]{n3};
            string2 = "LV";
            this.add((int[])object, string2);
            n3 = 476;
            object = new int[]{n3};
            string2 = "AZ";
            this.add((int[])object, string2);
            n3 = 477;
            object = new int[]{n3};
            string2 = "LT";
            this.add((int[])object, string2);
            n3 = 478;
            object = new int[]{n3};
            string2 = "UZ";
            this.add((int[])object, string2);
            n3 = 479;
            object = new int[]{n3};
            string2 = "LK";
            this.add((int[])object, string2);
            n3 = 480;
            object = new int[]{n3};
            string2 = "PH";
            this.add((int[])object, string2);
            n3 = 481;
            object = new int[]{n3};
            string2 = "BY";
            this.add((int[])object, string2);
            n3 = 482;
            object = new int[]{n3};
            string2 = "UA";
            this.add((int[])object, string2);
            n3 = 484;
            object = new int[]{n3};
            string2 = "MD";
            this.add((int[])object, string2);
            n3 = 485;
            object = new int[]{n3};
            string2 = "AM";
            this.add((int[])object, string2);
            n3 = 486;
            object = new int[]{n3};
            string2 = "GE";
            this.add((int[])object, string2);
            n3 = 487;
            object = new int[]{n3};
            string2 = "KZ";
            this.add((int[])object, string2);
            n3 = 489;
            object = new int[]{n3};
            string2 = "HK";
            this.add((int[])object, string2);
            n3 = 499;
            n4 = 490;
            object = new int[]{n4, n3};
            string2 = "JP";
            this.add((int[])object, string2);
            n3 = 509;
            n4 = 500;
            object = new int[]{n4, n3};
            string2 = "GB";
            this.add((int[])object, string2);
            n3 = 520;
            object = new int[]{n3};
            string2 = "GR";
            this.add((int[])object, string2);
            n3 = 528;
            object = new int[]{n3};
            string2 = "LB";
            this.add((int[])object, string2);
            n3 = 529;
            object = new int[]{n3};
            string2 = "CY";
            this.add((int[])object, string2);
            n3 = 531;
            object = new int[]{n3};
            string2 = "MK";
            this.add((int[])object, string2);
            n3 = 535;
            object = new int[]{n3};
            string2 = "MT";
            this.add((int[])object, string2);
            n3 = 539;
            object = new int[]{n3};
            string2 = "IE";
            this.add((int[])object, string2);
            n3 = 549;
            n4 = 540;
            object = new int[]{n4, n3};
            string2 = "BE/LU";
            this.add((int[])object, string2);
            n3 = 560;
            object = new int[]{n3};
            string2 = "PT";
            this.add((int[])object, string2);
            n3 = 569;
            object = new int[]{n3};
            string2 = "IS";
            this.add((int[])object, string2);
            n3 = 579;
            n4 = 570;
            object = new int[]{n4, n3};
            string2 = "DK";
            this.add((int[])object, string2);
            n3 = 590;
            object = new int[]{n3};
            string2 = "PL";
            this.add((int[])object, string2);
            n3 = 594;
            object = new int[]{n3};
            string2 = "RO";
            this.add((int[])object, string2);
            n3 = 599;
            object = new int[]{n3};
            string2 = "HU";
            this.add((int[])object, string2);
            n3 = 601;
            n4 = 600;
            object = new int[]{n4, n3};
            string2 = "ZA";
            this.add((int[])object, string2);
            n3 = 603;
            object = new int[]{n3};
            string2 = "GH";
            this.add((int[])object, string2);
            n3 = 608;
            object = new int[]{n3};
            string2 = "BH";
            this.add((int[])object, string2);
            n3 = 609;
            object = new int[]{n3};
            string2 = "MU";
            this.add((int[])object, string2);
            n3 = 611;
            object = new int[]{n3};
            string2 = "MA";
            this.add((int[])object, string2);
            n3 = 613;
            object = new int[]{n3};
            string2 = "DZ";
            this.add((int[])object, string2);
            n3 = 616;
            object = new int[]{n3};
            string2 = "KE";
            this.add((int[])object, string2);
            n3 = 618;
            object = new int[]{n3};
            string2 = "CI";
            this.add((int[])object, string2);
            n3 = 619;
            object = new int[]{n3};
            string2 = "TN";
            this.add((int[])object, string2);
            n3 = 621;
            object = new int[]{n3};
            string2 = "SY";
            this.add((int[])object, string2);
            n3 = 622;
            object = new int[]{n3};
            string2 = "EG";
            this.add((int[])object, string2);
            n3 = 624;
            object = new int[]{n3};
            string2 = "LY";
            this.add((int[])object, string2);
            n3 = 625;
            object = new int[]{n3};
            string2 = "JO";
            this.add((int[])object, string2);
            n3 = 626;
            object = new int[]{n3};
            string2 = "IR";
            this.add((int[])object, string2);
            n3 = 627;
            object = new int[]{n3};
            string2 = "KW";
            this.add((int[])object, string2);
            n3 = 628;
            object = new int[]{n3};
            string2 = "SA";
            this.add((int[])object, string2);
            n3 = 629;
            object = new int[]{n3};
            string2 = "AE";
            this.add((int[])object, string2);
            n3 = 649;
            n4 = 640;
            object = new int[]{n4, n3};
            string2 = "FI";
            this.add((int[])object, string2);
            n3 = 695;
            n4 = 690;
            object = new int[]{n4, n3};
            string2 = "CN";
            this.add((int[])object, string2);
            n3 = 709;
            n4 = 700;
            object = new int[]{n4, n3};
            string2 = "NO";
            this.add((int[])object, string2);
            n3 = 729;
            object = new int[]{n3};
            string2 = "IL";
            this.add((int[])object, string2);
            n3 = 739;
            n4 = 730;
            object = new int[]{n4, n3};
            string2 = "SE";
            this.add((int[])object, string2);
            n3 = 740;
            object = new int[]{n3};
            string2 = "GT";
            this.add((int[])object, string2);
            n3 = 741;
            object = new int[]{n3};
            string2 = "SV";
            this.add((int[])object, string2);
            n3 = 742;
            object = new int[]{n3};
            string2 = "HN";
            this.add((int[])object, string2);
            n3 = 743;
            object = new int[]{n3};
            string2 = "NI";
            this.add((int[])object, string2);
            n3 = 744;
            object = new int[]{n3};
            string2 = "CR";
            this.add((int[])object, string2);
            n3 = 745;
            object = new int[]{n3};
            string2 = "PA";
            this.add((int[])object, string2);
            n3 = 746;
            object = new int[]{n3};
            string2 = "DO";
            this.add((int[])object, string2);
            n3 = 750;
            object = new int[]{n3};
            string2 = "MX";
            this.add((int[])object, string2);
            n3 = 755;
            n4 = 754;
            object = new int[]{n4, n3};
            string2 = "CA";
            this.add((int[])object, string2);
            n3 = 759;
            object = new int[]{n3};
            string2 = "VE";
            this.add((int[])object, string2);
            n3 = 769;
            n4 = 760;
            object = new int[]{n4, n3};
            string2 = "CH";
            this.add((int[])object, string2);
            n3 = 770;
            object = new int[]{n3};
            string2 = "CO";
            this.add((int[])object, string2);
            n3 = 773;
            object = new int[]{n3};
            string2 = "UY";
            this.add((int[])object, string2);
            n3 = 775;
            object = new int[]{n3};
            string2 = "PE";
            this.add((int[])object, string2);
            n3 = 777;
            object = new int[]{n3};
            string2 = "BO";
            this.add((int[])object, string2);
            n3 = 779;
            object = new int[]{n3};
            string2 = "AR";
            this.add((int[])object, string2);
            n3 = 780;
            object = new int[]{n3};
            string2 = "CL";
            this.add((int[])object, string2);
            n3 = 784;
            object = new int[]{n3};
            string2 = "PY";
            this.add((int[])object, string2);
            n3 = 785;
            object = new int[]{n3};
            string2 = "PE";
            this.add((int[])object, string2);
            n3 = 786;
            object = new int[]{n3};
            string2 = "EC";
            this.add((int[])object, string2);
            n3 = 790;
            n4 = 789;
            object = new int[]{n4, n3};
            string2 = "BR";
            this.add((int[])object, string2);
            n3 = 839;
            n4 = 800;
            object = new int[]{n4, n3};
            string2 = "IT";
            this.add((int[])object, string2);
            n3 = 849;
            n4 = 840;
            object = new int[]{n4, n3};
            string2 = "ES";
            this.add((int[])object, string2);
            n3 = 850;
            object = new int[]{n3};
            string2 = "CU";
            this.add((int[])object, string2);
            n3 = 858;
            object = new int[]{n3};
            string2 = "SK";
            this.add((int[])object, string2);
            n3 = 859;
            object = new int[]{n3};
            string2 = "CZ";
            this.add((int[])object, string2);
            n3 = 860;
            object = new int[]{n3};
            string2 = "YU";
            this.add((int[])object, string2);
            n3 = 865;
            object = new int[]{n3};
            string2 = "MN";
            this.add((int[])object, string2);
            n3 = 867;
            object = new int[]{n3};
            string2 = "KP";
            this.add((int[])object, string2);
            n3 = 869;
            n4 = 868;
            object = new int[]{n4, n3};
            string2 = "TR";
            this.add((int[])object, string2);
            n3 = 879;
            n4 = 870;
            object = new int[]{n4, n3};
            string2 = "NL";
            this.add((int[])object, string2);
            n3 = 880;
            object = new int[]{n3};
            string2 = "KR";
            this.add((int[])object, string2);
            n3 = 885;
            object = new int[]{n3};
            string2 = "TH";
            this.add((int[])object, string2);
            n3 = 888;
            object = new int[]{n3};
            string2 = "SG";
            this.add((int[])object, string2);
            n3 = 890;
            object = new int[]{n3};
            string2 = "IN";
            this.add((int[])object, string2);
            n3 = 893;
            object = new int[]{n3};
            string2 = "VN";
            this.add((int[])object, string2);
            n3 = 896;
            object = new int[]{n3};
            string2 = "PK";
            this.add((int[])object, string2);
            n3 = 899;
            object = new int[]{n3};
            string2 = "ID";
            this.add((int[])object, string2);
            n3 = 919;
            n4 = 900;
            object = new int[]{n4, n3};
            string2 = "AT";
            this.add((int[])object, string2);
            n3 = 939;
            n4 = 930;
            object = new int[]{n4, n3};
            string2 = "AU";
            this.add((int[])object, string2);
            n3 = 949;
            n4 = 940;
            object = new int[]{n4, n3};
            string2 = "AZ";
            this.add((int[])object, string2);
            n3 = 955;
            object = new int[]{n3};
            string2 = "MY";
            this.add((int[])object, string2);
            n3 = 958;
            object = new int[]{n3};
            string2 = "MO";
            this.add((int[])object, string2);
            return;
        }
    }

    public String lookupCountryIdentifier(String string2) {
        this.initIfNeeded();
        string2 = string2.substring(0, 3);
        int n3 = Integer.parseInt(string2);
        List list = this.ranges;
        int n4 = list.size();
        int n7 = 0;
        while (true) {
            int n8 = 0;
            if (n7 >= n4) break;
            int[] nArray = (int[])this.ranges.get(n7);
            int n10 = nArray[0];
            if (n3 < n10) {
                return null;
            }
            n8 = nArray.length;
            int n14 = 1;
            if (n8 != n14) {
                n10 = nArray[n14];
            }
            if (n3 <= n10) {
                return (String)this.countryIdentifiers.get(n7);
            }
            ++n7;
        }
        return null;
    }
}

