/*
 * Decompiled with CFR 0.152.
 */
package com.google.android.gms.internal.icing;

import com.google.android.gms.internal.icing.zzdk;

public final class zzcv
extends Enum {
    public static final /* enum */ zzcv zzA;
    public static final /* enum */ zzcv zzB;
    public static final /* enum */ zzcv zzC;
    public static final /* enum */ zzcv zzD;
    public static final /* enum */ zzcv zzE;
    public static final /* enum */ zzcv zzF;
    public static final /* enum */ zzcv zzG;
    public static final /* enum */ zzcv zzH;
    public static final /* enum */ zzcv zzI;
    public static final /* enum */ zzcv zzJ;
    public static final /* enum */ zzcv zzK;
    public static final /* enum */ zzcv zzL;
    public static final /* enum */ zzcv zzM;
    public static final /* enum */ zzcv zzN;
    public static final /* enum */ zzcv zzO;
    public static final /* enum */ zzcv zzP;
    public static final /* enum */ zzcv zzQ;
    public static final /* enum */ zzcv zzR;
    public static final /* enum */ zzcv zzS;
    public static final /* enum */ zzcv zzT;
    public static final /* enum */ zzcv zzU;
    public static final /* enum */ zzcv zzV;
    public static final /* enum */ zzcv zzW;
    public static final /* enum */ zzcv zzX;
    public static final /* enum */ zzcv zzY;
    public static final /* enum */ zzcv zza;
    private static final zzcv[] zzac;
    private static final /* synthetic */ zzcv[] zzad;
    public static final /* enum */ zzcv zzb;
    public static final /* enum */ zzcv zzc;
    public static final /* enum */ zzcv zzd;
    public static final /* enum */ zzcv zze;
    public static final /* enum */ zzcv zzf;
    public static final /* enum */ zzcv zzg;
    public static final /* enum */ zzcv zzh;
    public static final /* enum */ zzcv zzi;
    public static final /* enum */ zzcv zzj;
    public static final /* enum */ zzcv zzk;
    public static final /* enum */ zzcv zzl;
    public static final /* enum */ zzcv zzm;
    public static final /* enum */ zzcv zzn;
    public static final /* enum */ zzcv zzo;
    public static final /* enum */ zzcv zzp;
    public static final /* enum */ zzcv zzq;
    public static final /* enum */ zzcv zzr;
    public static final /* enum */ zzcv zzs;
    public static final /* enum */ zzcv zzt;
    public static final /* enum */ zzcv zzu;
    public static final /* enum */ zzcv zzv;
    public static final /* enum */ zzcv zzw;
    public static final /* enum */ zzcv zzx;
    public static final /* enum */ zzcv zzy;
    public static final /* enum */ zzcv zzz;
    private final zzdk zzZ;
    private final int zzaa;
    private final Class zzab;

    static {
        zzcv zzcv2;
        zzcv zzcv3;
        zzcv zzcv4;
        zzcv zzcv5;
        zzcv zzcv6;
        zzcv zzcv7;
        zzcv zzcv8;
        zzcv zzcv9;
        zzcv zzcv10;
        zzcv zzcv11;
        zzcv zzcv12;
        zzcv zzcv13;
        zzcv zzcv14;
        zzcv zzcv15;
        zzcv zzcv16;
        zzcv zzcv17;
        zzcv zzcv18;
        zzcv zzcv19;
        zzcv zzcv20;
        zzcv zzcv21;
        zzcv zzcv22;
        zzcv zzcv23;
        zzcv zzcv24;
        zzcv zzcv25;
        zzcv zzcv26;
        zzcv zzcv27;
        zzcv zzcv28;
        zzcv zzcv29;
        zzcv zzcv30;
        zzcv zzcv31;
        zzcv zzcv32;
        zzcv zzcv33;
        zzcv zzcv34;
        Enum enum_ = zzdk.zze;
        int n3 = 1;
        zzcv[] zzcvArray = zzcv34;
        zzcv[] zzcvArray2 = enum_;
        zza = zzcv34 = new zzcv("DOUBLE", 0, 0, n3, (zzdk)enum_);
        Enum enum_2 = zzdk.zzd;
        int n4 = 1;
        int n7 = 1;
        int n8 = 1;
        zzcv zzcv35 = zzcv33;
        Enum enum_3 = enum_2;
        zzb = zzcv33 = new zzcv("FLOAT", n4, n7, n8, (zzdk)enum_2);
        Enum enum_4 = zzdk.zzc;
        zzcvArray = zzcv35;
        zzcvArray2 = enum_4;
        zzc = zzcv35 = new zzcv("INT64", 2, 2, n3, (zzdk)enum_4);
        zzcvArray = zzcv32;
        zzd = zzcv32 = new zzcv("UINT64", 3, 3, n3, (zzdk)enum_4);
        Enum enum_5 = zzdk.zzb;
        int n10 = 4;
        zzcv zzcv36 = zzcv31;
        Enum enum_6 = enum_5;
        zze = zzcv31 = new zzcv("INT32", n10, 4, 1, (zzdk)enum_5);
        zzcvArray = enum_3;
        zzf = enum_3 = new zzcv("FIXED64", 5, 5, n3, (zzdk)enum_4);
        zzcvArray = zzcv36;
        zzcvArray2 = enum_5;
        zzg = zzcv36 = new zzcv("FIXED32", 6, 6, n3, (zzdk)enum_5);
        Enum enum_7 = zzdk.zzf;
        int n14 = 7;
        int n15 = 7;
        int n16 = 1;
        zzcv zzcv37 = zzcv30;
        Enum enum_8 = enum_7;
        zzh = zzcv30 = new zzcv("BOOL", n14, n15, n16, (zzdk)enum_7);
        Enum enum_9 = zzdk.zzg;
        zzcvArray = zzcv37;
        zzcvArray2 = enum_9;
        zzi = zzcv37 = new zzcv("STRING", 8, 8, n3, (zzdk)enum_9);
        zzdk zzdk2 = zzdk.zzj;
        int n17 = 9;
        zzcv zzcv38 = zzcv29;
        Enum enum_10 = zzdk2;
        zzj = zzcv29 = new zzcv("MESSAGE", n17, 9, 1, zzdk2);
        enum_8 = zzdk.zzh;
        zzcvArray = enum_6;
        zzcvArray2 = enum_8;
        zzk = enum_6 = new zzcv("BYTES", 10, 10, n3, (zzdk)enum_8);
        zzcvArray = zzcv38;
        zzcvArray2 = enum_5;
        zzl = zzcv38 = new zzcv("UINT32", 11, 11, n3, (zzdk)enum_5);
        Enum enum_11 = zzdk.zzi;
        int n18 = 12;
        int n19 = 12;
        int n20 = 1;
        zzcv zzcv39 = zzcv28;
        Enum enum_12 = enum_11;
        zzm = zzcv28 = new zzcv("ENUM", n18, n19, n20, (zzdk)enum_11);
        zzcvArray = zzcv39;
        zzn = zzcv39 = new zzcv("SFIXED32", 13, 13, n3, (zzdk)enum_5);
        zzcvArray = zzcv27;
        zzcvArray2 = enum_4;
        zzo = zzcv27 = new zzcv("SFIXED64", 14, 14, n3, (zzdk)enum_4);
        zzcvArray = zzcv26;
        zzcvArray2 = enum_5;
        zzp = zzcv26 = new zzcv("SINT32", 15, 15, n3, (zzdk)enum_5);
        zzcvArray = zzcv25;
        zzcvArray2 = enum_4;
        zzq = zzcv25 = new zzcv("SINT64", 16, 16, n3, (zzdk)enum_4);
        zzcvArray = enum_10;
        zzcvArray2 = zzdk2;
        zzr = enum_10 = new zzcv("GROUP", 17, 17, n3, zzdk2);
        n3 = 2;
        zzcvArray = enum_12;
        zzcvArray2 = enum_;
        zzs = enum_12 = new zzcv("DOUBLE_LIST", 18, 18, n3, (zzdk)enum_);
        zzcvArray = zzcv24;
        zzcvArray2 = enum_2;
        zzt = zzcv24 = new zzcv("FLOAT_LIST", 19, 19, n3, (zzdk)enum_2);
        zzcvArray = zzcv23;
        zzcvArray2 = enum_4;
        zzu = zzcv23 = new zzcv("INT64_LIST", 20, 20, n3, (zzdk)enum_4);
        zzcvArray = zzcv22;
        zzv = zzcv22 = new zzcv("UINT64_LIST", 21, 21, n3, (zzdk)enum_4);
        zzcvArray = zzcv21;
        zzcvArray2 = enum_5;
        zzw = zzcv21 = new zzcv("INT32_LIST", 22, 22, n3, (zzdk)enum_5);
        zzcvArray = zzcv20;
        zzcvArray2 = enum_4;
        zzx = zzcv20 = new zzcv("FIXED64_LIST", 23, 23, n3, (zzdk)enum_4);
        zzcvArray = zzcv19;
        zzcvArray2 = enum_5;
        zzy = zzcv19 = new zzcv("FIXED32_LIST", 24, 24, n3, (zzdk)enum_5);
        zzcvArray = zzcv18;
        zzcvArray2 = enum_7;
        zzz = zzcv18 = new zzcv("BOOL_LIST", 25, 25, n3, (zzdk)enum_7);
        zzcvArray = zzcv17;
        zzcvArray2 = enum_9;
        zzA = zzcv17 = new zzcv("STRING_LIST", 26, 26, n3, (zzdk)enum_9);
        zzcvArray = enum_9;
        zzcvArray2 = zzdk2;
        zzB = enum_9 = new zzcv("MESSAGE_LIST", 27, 27, n3, zzdk2);
        zzcvArray = zzcv16;
        zzcvArray2 = enum_8;
        zzC = zzcv16 = new zzcv("BYTES_LIST", 28, 28, n3, (zzdk)enum_8);
        zzcvArray = enum_8;
        zzcvArray2 = enum_5;
        zzD = enum_8 = new zzcv("UINT32_LIST", 29, 29, n3, (zzdk)enum_5);
        zzcvArray = zzcv15;
        zzcvArray2 = enum_11;
        zzE = zzcv15 = new zzcv("ENUM_LIST", 30, 30, n3, (zzdk)enum_11);
        zzcvArray = zzcv14;
        zzcvArray2 = enum_5;
        zzF = zzcv14 = new zzcv("SFIXED32_LIST", 31, 31, n3, (zzdk)enum_5);
        zzcvArray = zzcv13;
        zzcvArray2 = enum_4;
        zzG = zzcv13 = new zzcv("SFIXED64_LIST", 32, 32, n3, (zzdk)enum_4);
        zzcvArray = zzcv12;
        zzcvArray2 = enum_5;
        zzH = zzcv12 = new zzcv("SINT32_LIST", 33, 33, n3, (zzdk)enum_5);
        zzcvArray = zzcv11;
        zzcvArray2 = enum_4;
        zzI = zzcv11 = new zzcv("SINT64_LIST", 34, 34, n3, (zzdk)enum_4);
        n3 = 3;
        zzcvArray = zzcv10;
        zzcvArray2 = enum_;
        zzJ = zzcv10 = new zzcv("DOUBLE_LIST_PACKED", 35, 35, n3, (zzdk)enum_);
        zzcvArray = enum_;
        zzcvArray2 = enum_2;
        zzK = enum_ = new zzcv("FLOAT_LIST_PACKED", 36, 36, n3, (zzdk)enum_2);
        zzcvArray = enum_2;
        zzcvArray2 = enum_4;
        zzL = enum_2 = new zzcv("INT64_LIST_PACKED", 37, 37, n3, (zzdk)enum_4);
        zzcvArray = zzcv9;
        zzM = zzcv9 = new zzcv("UINT64_LIST_PACKED", 38, 38, n3, (zzdk)enum_4);
        zzcvArray = zzcv8;
        zzcvArray2 = enum_5;
        zzN = zzcv8 = new zzcv("INT32_LIST_PACKED", 39, 39, n3, (zzdk)enum_5);
        zzcvArray = zzcv7;
        zzcvArray2 = enum_4;
        zzO = zzcv7 = new zzcv("FIXED64_LIST_PACKED", 40, 40, n3, (zzdk)enum_4);
        zzcvArray = zzcv6;
        zzcvArray2 = enum_5;
        zzP = zzcv6 = new zzcv("FIXED32_LIST_PACKED", 41, 41, n3, (zzdk)enum_5);
        zzcvArray = zzcv5;
        zzcvArray2 = enum_7;
        zzQ = zzcv5 = new zzcv("BOOL_LIST_PACKED", 42, 42, n3, (zzdk)enum_7);
        zzcvArray = enum_7;
        zzcvArray2 = enum_5;
        zzR = enum_7 = new zzcv("UINT32_LIST_PACKED", 43, 43, n3, (zzdk)enum_5);
        zzcvArray = zzcv4;
        zzcvArray2 = enum_11;
        zzS = zzcv4 = new zzcv("ENUM_LIST_PACKED", 44, 44, n3, (zzdk)enum_11);
        zzcvArray = enum_11;
        zzcvArray2 = enum_5;
        zzT = enum_11 = new zzcv("SFIXED32_LIST_PACKED", 45, 45, n3, (zzdk)enum_5);
        zzcvArray = zzcv3;
        zzcvArray2 = enum_4;
        zzU = zzcv3 = new zzcv("SFIXED64_LIST_PACKED", 46, 46, n3, (zzdk)enum_4);
        zzcvArray = zzcv2;
        zzcvArray2 = enum_5;
        zzV = zzcv2 = new zzcv("SINT32_LIST_PACKED", 47, 47, n3, (zzdk)enum_5);
        zzcvArray = enum_5;
        zzcvArray2 = enum_4;
        zzW = enum_5 = new zzcv("SINT64_LIST_PACKED", 48, 48, n3, (zzdk)enum_4);
        n3 = 2;
        zzcvArray = enum_4;
        zzcvArray2 = zzdk2;
        zzX = enum_4 = new zzcv("GROUP_LIST", 49, 49, n3, zzdk2);
        int n21 = 4;
        zzdk zzdk3 = zzdk.zza;
        String string2 = "MAP";
        int n22 = 50;
        int n24 = 50;
        zzcvArray = new zzcv(string2, n22, n24, n21, zzdk3);
        zzY = zzcvArray;
        zzcv[] zzcvArray3 = new zzcv[51];
        zzcvArray3[0] = zzcv34;
        int n25 = 1;
        zzcvArray3[n25] = zzcv33;
        zzcvArray3[n3] = zzcv35;
        zzcvArray3[3] = zzcv32;
        zzcvArray3[4] = zzcv31;
        zzcvArray3[5] = enum_3;
        zzcvArray3[6] = zzcv36;
        zzcvArray3[7] = zzcv30;
        zzcvArray3[8] = zzcv37;
        zzcvArray3[9] = zzcv29;
        zzcvArray3[10] = enum_6;
        zzcvArray3[11] = zzcv38;
        zzcvArray3[12] = zzcv28;
        zzcvArray3[13] = zzcv39;
        zzcvArray3[14] = zzcv27;
        zzcvArray3[15] = zzcv26;
        zzcvArray3[16] = zzcv25;
        zzcvArray3[17] = enum_10;
        zzcvArray3[18] = enum_12;
        zzcvArray3[19] = zzcv24;
        zzcvArray3[20] = zzcv23;
        zzcvArray3[21] = zzcv22;
        zzcvArray3[22] = zzcv21;
        zzcvArray3[23] = zzcv20;
        zzcvArray3[24] = zzcv19;
        zzcvArray3[25] = zzcv18;
        zzcvArray3[26] = zzcv17;
        zzcvArray3[27] = enum_9;
        zzcvArray3[28] = zzcv16;
        zzcvArray3[29] = enum_8;
        zzcvArray3[30] = zzcv15;
        zzcvArray3[31] = zzcv14;
        zzcvArray3[32] = zzcv13;
        zzcvArray3[33] = zzcv12;
        zzcvArray3[34] = zzcv11;
        zzcvArray3[35] = zzcv10;
        zzcvArray3[36] = enum_;
        zzcvArray3[37] = enum_2;
        zzcvArray3[38] = zzcv9;
        zzcvArray3[39] = zzcv8;
        zzcvArray3[40] = zzcv7;
        zzcvArray3[41] = zzcv6;
        zzcvArray3[42] = zzcv5;
        zzcvArray3[43] = enum_7;
        zzcvArray3[44] = zzcv4;
        zzcvArray3[45] = enum_11;
        zzcvArray3[46] = zzcv3;
        zzcvArray3[47] = zzcv2;
        zzcvArray3[48] = enum_5;
        zzcvArray3[49] = enum_4;
        n3 = 50;
        zzcvArray3[n3] = zzcvArray;
        zzad = zzcvArray3;
        zzcvArray = zzcv.values();
        int n26 = zzcvArray.length;
        Object object = new zzcv[n26];
        zzac = object;
        for (int i3 = 0; i3 < n26; i3 += n25) {
            object = zzcvArray[i3];
            zzcvArray2 = zzac;
            int n27 = object.zzaa;
            zzcvArray2[n27] = object;
        }
    }

    /*
     * WARNING - Possible parameter corruption
     * WARNING - void declaration
     */
    private zzcv(zzdk object) {
        void var4_2;
        void var5_3;
        void var2_-1;
        void var1_-1;
        this.zzaa = (int)object;
        this.zzZ = var5_3;
        Object object2 = zzdk.zza;
        boolean bl2 = var4_2 + -1;
        boolean bl3 = true;
        if (bl2 != bl3) {
            object = 3;
            if (bl2 != object) {
                bl2 = false;
                object2 = null;
                this.zzab = null;
            } else {
                object2 = var5_3.zza();
                this.zzab = object2;
            }
        } else {
            object2 = var5_3.zza();
            this.zzab = object2;
        }
        if (var4_2 == bl3) {
            var5_3.ordinal();
        }
    }

    public static zzcv[] values() {
        return (zzcv[])zzad.clone();
    }

    public final int zza() {
        return this.zzaa;
    }
}

