/*
 * Decompiled with CFR 0.152.
 */
package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult$StatusListener;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.api.TransformedResult;
import com.google.android.gms.common.internal.Preconditions;
import java.util.concurrent.TimeUnit;

public final class zacp
extends PendingResult {
    private final Status zaa;

    public zacp(Status status) {
        Preconditions.checkNotNull(status, "Status must not be null");
        Preconditions.checkArgument(status.isSuccess() ^ true, "Status must not be success");
        this.zaa = status;
    }

    public final void addStatusListener(PendingResult$StatusListener object) {
        object = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        throw object;
    }

    public final Result await() {
        UnsupportedOperationException unsupportedOperationException = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        throw unsupportedOperationException;
    }

    public final Result await(long l2, TimeUnit timeUnit) {
        UnsupportedOperationException unsupportedOperationException = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        throw unsupportedOperationException;
    }

    public final void cancel() {
        UnsupportedOperationException unsupportedOperationException = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        throw unsupportedOperationException;
    }

    public final boolean isCanceled() {
        UnsupportedOperationException unsupportedOperationException = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        throw unsupportedOperationException;
    }

    public final void setResultCallback(ResultCallback object) {
        object = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        throw object;
    }

    public final void setResultCallback(ResultCallback object, long l2, TimeUnit timeUnit) {
        object = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        throw object;
    }

    public final TransformedResult then(ResultTransform object) {
        object = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        throw object;
    }

    public final Status zaa() {
        return this.zaa;
    }
}

